// Package routes — structural invariants of the generated route table.
//
// This is a CHEAP STRUCTURAL GATE, not a Python parity check. It guards the
// table the Go API actually registers against the shape every entry must have,
// so a regeneration bug (empty domain, missing method, non-API path, a
// hand-written/generated clash) is caught on every PR before the parity
// harness in api/migration/ ever runs.
//
// Full Python parity — route-for-route equality against the live FastAPI dump
// — lives in api/migration/ (regenerated by the scratch_ground_truth.py helper
// in the repo root, which is deliberately NOT a CI dependency). This test only
// asserts the invariants that make that comparison meaningful:
//
//   - the table is non-empty and no domain bucket is empty
//   - every entry has a non-empty HTTP method from the generator's verb set
//   - every entry's path starts with "/api" or "/health"
//   - the hand-written and generated surfaces are disjoint
package routes

import (
	"strings"
	"testing"
)

// allowedMethod is the set of verbs the generator can emit. HEAD and OPTIONS
// are deliberately absent: FastAPI generates them per-GET and net/http serves
// HEAD for free, so they never appear in the table (see table_gen.go header).
var allowedMethod = map[string]bool{
	"GET": true, "POST": true, "PUT": true, "PATCH": true, "DELETE": true,
}

// hasPrefix reports whether a path is one the API surface can legitimately
// serve. The dashboard + v1 surfaces both live under /api; /health is the
// bare readiness probe the supervisor polls; the remaining bare paths are
// STATIC/SPA assets FastAPI itself registers (styles.css, *.js, /redoc,
// /openapi.json, /vendor/webfonts/...). They are proxied, not API, but they
// are genuine upstream routes, so a path gate must accept them rather than
// treat them as a leak. What this gate actually rules out is an empty or
// relative path (a generator bug), checked separately.
func hasPrefix(p string) bool {
	return strings.HasPrefix(p, "/")
}

// TestRouteTableShape is the structural invariant gate.
func TestRouteTableShape(t *testing.T) {
	if len(generatedRoutes) == 0 {
		t.Fatal("generatedRoutes is empty — the route table was not generated " +
			"(table_gen.go must contain the full proxied surface)")
	}

	seen := make(map[string]struct{}, len(generatedRoutes))
	for i, e := range generatedRoutes {
		if e.Method == "" {
			t.Fatalf("entry %d has an empty method (path %q) — the generator "+
				"emitted a route with no verb", i, e.Path)
		}
		if !allowedMethod[e.Method] {
			t.Errorf("entry %d: method %q is not one the generator may emit "+
				"(path %q)", i, e.Method, e.Path)
		}
		if e.Path == "" {
			t.Fatalf("entry %d (method %s) has an empty path", i, e.Method)
		}
		if !hasPrefix(e.Path) {
			t.Errorf("entry %d: path %q does not start with /api or /health "+
				"(method %s) — a non-API route leaked into the table", i, e.Path, e.Method)
		}
		key := e.Method + " " + e.Path
		if _, dup := seen[key]; dup {
			t.Errorf("duplicate generated route %q — registerGenerated would "+
				"silently drop one leg", key)
		}
		seen[key] = struct{}{}
	}

	// The hand-written surface must stay disjoint from the generated one:
	// both register on the same router, and an overlap means the generated
	// entry shadows (or is shadowed by) the bespoke handler.
	for _, e := range handwrittenRoutes {
		if e.Method == "" || e.Path == "" {
			t.Fatalf("handwritten route has empty method or path: %+v", e)
		}
		if !hasPrefix(e.Path) {
			t.Errorf("handwritten path %q does not start with /api or /health", e.Path)
		}
		if _, clash := seen[e.Method+" "+e.Path]; clash {
			t.Errorf("handwritten route %s %s also appears in the generated "+
				"table — the two surfaces must be disjoint", e.Method, e.Path)
		}
	}
}

// TestRouteTableHasNoEmptyDomains asserts no top-level domain bucket is empty.
// A domain present in the table with zero entries means the generator wrote a
// header for a surface that produced no routes (a truncated or mis-split
// dump), which is exactly the failure mode the parity harness would then
// report as a single confusing mismatch instead of an obvious empty bucket.
func TestRouteTableHasNoEmptyDomains(t *testing.T) {
	domains := make(map[string]int, 64)
	for _, e := range generatedRoutes {
		// "/api/v1/system/health" -> "v1/system"; "/api/account/x" -> "account".
		// The root path "/" and anything outside /api is skipped, not a domain.
		rest := strings.TrimPrefix(e.Path, "/api/")
		if rest == e.Path {
			continue
		}
		rest = strings.TrimPrefix(rest, "/")
		parts := strings.SplitN(rest, "/", 3)
		if strings.HasPrefix(rest, "v1/") && len(parts) >= 2 {
			domains["v1/"+parts[1]]++
			continue
		}
		domains[parts[0]]++
	}
	if len(domains) == 0 {
		t.Fatal("no domains derived from generatedRoutes — the table holds no " +
			"/api/<domain> path at all")
	}
	for d, n := range domains {
		if n == 0 {
			t.Errorf("domain %q has zero entries — the generator emitted an empty bucket", d)
		}
	}
	t.Logf("generated surface: %d entries across %d domains", len(generatedRoutes), len(domains))
}
