// Package routing — Wave 3 cross-table parity gate.
//
// Two generated tables describe the SAME route surface:
//
//   - go-api/internal/api/routes/table_gen.go + table_handwritten.go is the
//     full surface Go registers (built from the live FastAPI route dump).
//   - deps_table.go (this package) is the dependency classification, built
//     from the profiler output in api/migration/route_dependencies.json.
//
// They are regenerated by DIFFERENT commands, so they can drift: if Python
// gains a route and only the route table is regenerated, deps_table.go is
// silently one entry short and NeedsPython() falls back to forwarding. That
// is SAFE at runtime (forwarding is always the correct default), but the
// classification is then quietly incomplete, and the next wave would be
// deciding on a table that no longer matches the surface it claims to cover.
//
// This test pins the two together. It parses the route entries out of the
// generated Go source — the route table lives in a package that imports this
// one (routes -> handlers -> routing), so importing it here would close an
// import cycle — and compares them against the JSON the deps table was
// generated from. Every route Go serves must have a dependency entry.
package routing

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// routeTablePaths are the generated and hand-written route tables, relative
// to this package's directory.
var routeTablePaths = []string{
	"../api/routes/table_gen.go",
	"../api/routes/table_handwritten.go",
}

// depsJSONPath is the profiler output deps_table.go is generated from.
const depsJSONPath = "../../../api/migration/route_dependencies.json"

// routeEntryPattern matches one `{Method: "GET", Path: "/api/...", IsV1: false}`
// literal in either route table. Method is anchored to the generator's verb
// set so a struct literal with differently ordered or extra fields still
// parses.
var routeEntryPattern = regexp.MustCompile(`\{Method: "([A-Z]+)", Path: "([^"]*)"`)

// profilerDoc mirrors the shape of api/migration/route_dependencies.json.
// Only the fields this gate needs: the per-route body samples are large and
// irrelevant here, so they are deliberately not decoded. json.RawMessage
// keeps the unmarshal cheap while the second test decodes the classification
// fields it actually compares.
type profilerDoc struct {
	Routes map[string]struct {
		NeedsPython bool   `json:"needs_python"`
		Why         string `json:"why"`
	} `json:"routes"`
	Skipped []string `json:"skipped"`
}

// loadRouteKeys reads the generated route tables and returns the set of
// "METHOD /path" keys they register, plus the raw entry count.
func loadRouteKeys(t *testing.T) (map[string]bool, int) {
	t.Helper()

	keys := make(map[string]bool)
	n := 0
	for _, rel := range routeTablePaths {
		path := filepath.Join(".", rel)
		f, err := os.Open(path)
		if err != nil {
			t.Fatalf("cannot open route table %s: %v\n"+
				"(running this test from outside the package directory is not "+
				"supported — run it via `go test ./internal/routing/`)", path, err)
		}
		s := bufio.NewScanner(f)
		s.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		for s.Scan() {
			for _, m := range routeEntryPattern.FindAllSubmatch(s.Bytes(), -1) {
				keys[string(m[1])+" "+string(m[2])] = true
				n++
			}
		}
		f.Close()
		if err := s.Err(); err != nil {
			t.Fatalf("scanning route table %s: %v", path, err)
		}
	}
	if n == 0 {
		t.Fatalf("parsed 0 route literals from %v — the entry shape changed "+
			"and routeEntryPattern no longer matches the generator's output",
			routeTablePaths)
	}
	return keys, n
}

// loadProfiler reads the profiler output and returns the parsed document.
func loadProfiler(t *testing.T) profilerDoc {
	t.Helper()

	path := filepath.Join(".", depsJSONPath)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot open profiler output %s: %v", path, err)
	}
	var doc profilerDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("cannot parse %s as the profiler document: %v", path, err)
	}
	if len(doc.Routes) == 0 {
		t.Fatalf("%s contains no classified routes — the profiler has not "+
			"been run, or its output format changed", path)
	}
	return doc
}

// TestDepsTableCoversRouteSurface is the anti-drift gate: every route the Go
// API registers must carry a dependency classification.
//
// A route present in the route tables but missing from DepsTable is an
// incomplete classification, not a crash: Decide() forwards it safely. But
// silent incompleteness is how a stale table survives until the day someone
// treats a missing entry as evidence, so it fails the build here instead.
func TestDepsTableCoversRouteSurface(t *testing.T) {
	surface, parsed := loadRouteKeys(t)
	doc := loadProfiler(t)
	classified := doc.Routes
	skipped := doc.Skipped

	// The JSON is generated 1:1 into DepsTable (see scripts/dev/
	// gen_deps_table.py, which emits one entry per routes key). A count
	// mismatch means the generated file is not the JSON on disk.
	if len(classified) != len(DepsTable) {
		t.Errorf("DepsTable has %d entries, but %s classifies %d routes — "+
			"deps_table.go is stale: rerun scripts/dev/gen_deps_table.py",
			len(DepsTable), filepath.Join(".", depsJSONPath), len(classified))
	}

	// Every DepsTable key must also be a real profiler key: an entry the
	// profiler never emitted is a hand-edit or a generator bug.
	for key := range DepsTable {
		if _, ok := classified[key]; !ok {
			t.Errorf("DepsTable[%q]: no such route in the profiler output — "+
				"the table holds a classification for a route that was never "+
				"profiled", key)
		}
	}

	// The profiler skips SSE/WebSocket routes (streaming, not
	// request/response — they would hang the replay probe). They are part of
	// the served surface and are expected to be unclassified, so they are
	// subtracted before the coverage comparison rather than counted as drift.
	exempt := make(map[string]bool, len(skipped))
	for _, k := range skipped {
		exempt[k] = true
	}

	var missing []string
	for key := range surface {
		if _, ok := DepsTable[key]; ok {
			continue
		}
		if exempt[key] {
			continue
		}
		missing = append(missing, key)
	}
	if len(missing) > 0 {
		// Deterministic output: a sorted list reads better than map
		// iteration order and makes the failure diff-able.
		sorted := append([]string(nil), missing...)
		sortStrings(sorted)
		t.Errorf("DepsTable does not classify %d of the %d routes Go registers "+
			"(parsed %d route literals; profiler classified %d, skipped %d "+
			"streaming routes). Missing classification for:\n  %s\n"+
			"Python grew a route that the dependency profiler has not seen: "+
			"rerun scripts/dev/profile_route_deps.py + scripts/dev/"+
			"classify_route_deps.py + scripts/dev/gen_deps_table.py.",
			len(missing), len(surface), parsed, len(classified), len(exempt),
			strings.Join(sorted, "\n  "))
		return
	}

	t.Logf("coverage OK: %d registered routes, %d classified, %d streaming "+
		"routes exempt (profiler skipped), deps table holds %d entries",
		len(surface), len(classified), len(exempt), len(DepsTable))
}

// TestDepsTableMatchesProfiler pins the generated table's CONTENT to the
// profiler output, not just its key set. gen_deps_table.py copies
// needs_python and why verbatim, so a divergence here means the file on disk
// is not the file the generator would emit — a hand-edit, or a table left
// behind after the classifier changed its mind.
func TestDepsTableMatchesProfiler(t *testing.T) {
	doc := loadProfiler(t)

	var stale []string
	for key, rec := range doc.Routes {
		got, ok := DepsTable[key]
		if !ok {
			continue // key-set drift is reported by the coverage test above
		}
		if got.NeedsPython != rec.NeedsPython || got.Why != rec.Why {
			stale = append(stale, key)
		}
	}
	if len(stale) > 0 {
		sortStrings(stale)
		t.Errorf("DepsTable disagrees with the profiler on %d routes "+
			"(needs_python or why differ). deps_table.go is stale: rerun "+
			"scripts/dev/gen_deps_table.py.\n  %s",
			len(stale), strings.Join(stale, "\n  "))
	}
}

// sortStrings sorts in place; the surface is small enough that pulling in
// sort for this would cost more import surface than it saves.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}
