"""EU-RELEASE-001 — application icon regression tests.

Root cause (end-user release audit, 2026-09-23): the release build never
passed ``--icon`` to PyInstaller, so both shipped executables
(``NexusScalpEngine.exe``, ``NexusScalpEngine-CLI.exe``) carried PyInstaller's
generic placeholder. ``installer/NexusScalpEngine.iss`` points
``UninstallDisplayIcon`` at the installed EXE, so the placeholder also leaked
into the Start Menu / uninstall entry — the product looked unfinished in
exactly the surfaces a normal user judges it on (taskbar, explorer, shortcut).

The icon is generated from ``frontend/public/icon-512.png`` (the canonical
brand asset already used by the PWA manifest / Apple touch icon / OG card)
by ``scripts/build/generate_app_icon.py``.

These tests pin the THREE build paths that stamp the icon, so a future
refactor that drops it fails loudly instead of shipping a placeholder again:

  1. ``scripts/build/build_release.ps1`` (local / operator release build)
  2. ``scripts/release/build_artifact.py`` (artifact builder)
  3. ``.github/workflows/release.yml`` (CI release pipeline)

All assertions are static (no PyInstaller run, no network) — a packaging
lane must not need a full Windows toolchain to prove its icon contract.
"""

from __future__ import annotations

import struct
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]

ICON = REPO / "installer" / "NexusScalpEngine.ico"
SOURCE_PNG = REPO / "frontend" / "public" / "icon-512.png"
GENERATOR = REPO / "scripts" / "build" / "generate_app_icon.py"

BUILD_RELEASE_PS1 = REPO / "scripts" / "build" / "build_release.ps1"
BUILD_ARTIFACT_PY = REPO / "scripts" / "release" / "build_artifact.py"
RELEASE_YML = REPO / ".github" / "workflows" / "release.yml"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


class TestIconAsset:
    """The canonical brand asset and the generated Windows icon exist."""

    def test_canonical_brand_png_exists(self):
        assert SOURCE_PNG.exists(), (
            f"canonical brand asset missing: {SOURCE_PNG} — the icon generator "
            "and the PWA manifest both depend on it"
        )

    def test_generator_script_exists(self):
        assert GENERATOR.exists(), f"icon generator missing: {GENERATOR}"

    def test_icon_file_exists(self):
        assert ICON.exists(), (
            f"{ICON} missing — run: python scripts/build/generate_app_icon.py "
            "(it converts frontend/public/icon-512.png; Pillow is build-time only)"
        )

    @pytest.mark.skipif(not ICON.exists(), reason="icon not generated yet")
    def test_icon_is_a_real_multi_resolution_ico(self):
        """A placeholder/garbage file must not pass. Reads the ICO directory:
        6 bytes of header (reserved=0, type=1) then one 16-byte entry per size.
        """
        data = ICON.read_bytes()
        assert len(data) > 100, "ICO suspiciously small"
        reserved, ico_type, count = struct.unpack_from("<HHH", data, 0)
        assert reserved == 0, f"ICO reserved header must be 0 (got {reserved})"
        assert ico_type == 1, f"ICO resource type must be 1 (got {ico_type})"
        assert count >= 5, f"expected >=5 resolutions for crisp shell surfaces (got {count})"

        sizes: set[tuple[int, int]] = set()
        offset = 6
        for _ in range(count):
            w = data[offset] or 256  # 0 means 256
            h = data[offset + 1] or 256
            sizes.add((w, h))
            offset += 16
        # The desktop surfaces that matter: 256 (large tiles / hi-dpi taskbar),
        # 32 (classic desktop / Alt-Tab), 16 (small icons / title bar).
        for needed in ((256, 256), (32, 32), (16, 16)):
            assert needed in sizes, (
                f"ICO missing the {needed[0]}x{needed[1]} entry (has {sorted(sizes)})"
            )


class TestBuildWiring:
    """Every build path that produces a Windows EXE must stamp the icon.

    A dropped ``--icon`` is silent at build time and only visible as a
    placeholder glyph in the user's taskbar — pin it in the tree instead.
    """

    def test_build_release_ps1_stamps_icon_on_both_binaries(self):
        text = _read(BUILD_RELEASE_PS1)
        assert "--icon $IconPath" in text, "build_release.ps1 lost the --icon flag"
        # The guard must exist too: a missing icon with no fail-loud check
        # degrades into a broken build instead of a clean rejection.
        assert "Application icon missing" in text, (
            "build_release.ps1 lost the fail-loud guard for the icon"
        )
        # The icon is GENERATED by the build (from the canonical PNG), not
        # hand-committed binary art that can silently drift.
        assert "generate_app_icon.py" in text, (
            "build_release.ps1 must generate the icon from frontend/public/icon-512.png"
        )
        # Both binaries: the onedir app EXE and the onefile CLI EXE.
        onedir = text.split("--onedir", 1)[-1].split("onefile", 1)[0]
        cli = text.split("NexusScalpEngine-CLI", 1)[-1].split("exclude-module", 1)[0]
        assert "--icon" in onedir, "build_release.ps1: onedir NexusScalpEngine.exe has no icon"
        assert "--icon" in cli, "build_release.ps1: onefile NexusScalpEngine-CLI.exe has no icon"

    def test_build_artifact_py_stamps_icon(self):
        text = _read(BUILD_ARTIFACT_PY)
        assert "--icon" in text, "build_artifact.py lost the --icon flag"
        assert "NexusScalpEngine.ico" in text, "build_artifact.py resolves the wrong icon path"

    def test_release_ci_workflow_stamps_icon(self):
        text = _read(RELEASE_YML)
        assert "generate_app_icon.py" in text, (
            "release.yml must generate the icon before PyInstaller runs"
        )
        onedir = text.split("--onedir", 1)[-1].split("onefile", 1)[0]
        cli = text.split("NexusScalpEngine-CLI", 1)[-1]
        assert "--icon" in onedir, "release.yml: onedir build has no icon"
        assert "--icon" in cli, "release.yml: onefile CLI build has no icon"


class TestInnoSetup:
    """The installer surface: the uninstall/Start Menu entry resolves the icon
    through the installed EXE (UninstallDisplayIcon={app}\\NexusScalpEngine.exe),
    so the EXE icon IS the installer icon. Pin that contract."""

    @pytest.mark.skipif(
        not (REPO / "installer" / "NexusScalpEngine.iss").exists(), reason="no .iss"
    )
    def test_installer_resolves_icon_from_installed_exe(self):
        text = _read(REPO / "installer" / "NexusScalpEngine.iss")
        assert "UninstallDisplayIcon={app}" in text, (
            "Inno Setup must resolve the uninstall icon from the installed EXE "
            "(which now carries the real icon)"
        )
