/**
 * i18n messages — scope: lib/errors (backend error-code map, i18n rules
 * §31/§32/§70). DATA-ONLY file. Resolved by lib/errorMessages.ts.
 *
 * Keys mirror the backend machine codes verbatim: ENGINE_UNAVAILABLE becomes
 * errors.engine_unavailable. Both backend registries (web/errors.py and
 * web/api_v1/common.py) share keys where codes coincide (6 do).
 * The unknown-code fallback (errors.unknown_reference) is mandatory: the
 * backend emits ~110 unregistered route-local codes, some with raw exception
 * text in `message`, which must never be displayed. Unknown codes get a safe
 * generic localized message plus the code as a monospace token and the
 * request id as a reference — never raw exception prose (rule §70).
 */
import type { FeatureMessages } from "@/lib/i18n";

export const MESSAGES: FeatureMessages = {
  "errors.internal": {  fa: "سرور نتوانست این درخواست را کامل کند.", de: "Der Server konnte diese Anfrage nicht abschließen.", es: "El servidor no pudo completar esta solicitud.", ar: "تعذّر على الخادم إكمال هذا الطلب." , en: "The server could not complete this request." },
  "errors.not_found": {  fa: "منبع درخواستی یافت نشد.", de: "Die angeforderte Ressource wurde nicht gefunden.", es: "No se encontró el recurso solicitado.", ar: "لم يُعثر على المورد المطلوب." , en: "The requested resource was not found." },
  "errors.unavailable": {  fa: "منبع درخواستی موقتاً در دسترس نیست.", de: "Die angeforderte Ressource ist vorübergehend nicht verfügbar.", es: "El recurso solicitado no está disponible temporalmente.", ar: "المورد المطلوب غير متاح مؤقتًا." , en: "The requested resource is temporarily unavailable." },
  "errors.bad_request": {  fa: "درخواست قابل پردازش نبود.", de: "Die Anfrage konnte nicht verarbeitet werden.", es: "No se pudo procesar la solicitud.", ar: "تعذّرت معالجة الطلب." , en: "The request could not be processed." },
  "errors.validation": {  fa: "محتویات درخواست نامعتبر بود.", de: "Die Anfragedaten waren ungültig.", es: "Los datos de la solicitud no eran válidos.", ar: "كانت بيانات الطلب غير صالحة." , en: "The request payload was invalid." },
  "errors.engine_unavailable": {  fa: "موتور معاملاتی متصل نیست.", de: "Die Trading-Engine ist nicht verbunden.", es: "El motor de trading no está conectado.", ar: "محرك التداول غير متصل." , en: "The trading engine is not connected." },
  "errors.operation_failed": {  fa: "عملیات قابل انجام نبود.", de: "Der Vorgang konnte nicht abgeschlossen werden.", es: "No se pudo completar la operación.", ar: "تعذّر إكمال العملية." , en: "The operation could not be completed." },
  "errors.sse_stream": {  fa: "جریان زنده قطع شد.", de: "Der Live-Stream wurde unterbrochen.", es: "Se interrumpió la transmisión en vivo.", ar: "انقطع البث المباشر." , en: "The live stream was interrupted." },
  "errors.ws_stream": {  fa: "نشست بلادرنگ قطع شد.", de: "Die Echtzeit-Sitzung wurde unterbrochen.", es: "Se interrumpió la sesión en tiempo real.", ar: "انقطعت الجلسة الفورية." , en: "The realtime session was interrupted." },
  "errors.method_not_allowed": {  fa: "این روش HTTP برای این منبع مجاز نیست.", de: "Die HTTP-Methode ist für diese Ressource nicht erlaubt.", es: "El método HTTP no está permitido para este recurso.", ar: "طريقة HTTP غير مسموح بها لهذا المورد." , en: "The HTTP method is not allowed for this resource." },
  "errors.payload_too_large": {  fa: "محتویات درخواست از اندازه مجاز فراتر است.", de: "Die Anfragedaten überschreiten die zulässige Größe.", es: "Los datos de la solicitud superan el tamaño permitido.", ar: "تتجاوز بيانات الطلب الحجم المسموح." , en: "The request payload exceeds the allowed size." },
  "errors.conflict": {  fa: "درخواست با وضعیت فعلی در تضاد است.", de: "Die Anfrage steht im Konflikt mit dem aktuellen Zustand.", es: "La solicitud entra en conflicto con el estado actual.", ar: "الطلب يتعارض مع الحالة الحالية." , en: "The request conflicts with the current state." },
  "errors.forbidden": {  fa: "عملیات درخواستی مجاز نیست.", de: "Der angeforderte Vorgang ist nicht erlaubt.", es: "La operación solicitada no está permitida.", ar: "العملية المطلوبة غير مسموح بها." , en: "The requested operation is not allowed." },
  "errors.dependency_unavailable": {  fa: "یک وابستگی مورد نیاز در دسترس نیست.", de: "Eine erforderliche Abhängigkeit ist nicht verfügbar.", es: "Una dependencia requerida no está disponible.", ar: "إحدى التبعيات المطلوبة غير متاحة." , en: "A required dependency is not available." },
  "errors.timeout": {  fa: "زمان درخواست به پایان رسید.", de: "Die Anfrage hat das Zeitlimit überschritten.", es: "La solicitud superó el tiempo límite.", ar: "انتهت مهلة الطلب." , en: "The request timed out." },
  "errors.unauthorized": {  fa: "توکن وب گم یا نامعتبر است.", de: "Web-Auth-Token fehlt oder ist ungültig.", es: "Falta el token de autenticación web o no es válido.", ar: "رمز مصادقة الويب مفقود أو غير صالح." , en: "Missing or invalid web auth token." },
  "errors.auth_config_error": {  fa: "تنظیمات احراز هویت وب قابل حل نیست (محافظت در حالت بسته).", de: "Die Web-Auth-Konfiguration ist nicht auflösbar (fail-closed).", es: "La configuración de autenticación web no se puede resolver (fail-closed).", ar: "لا يمكن تحليل إعداد مصادقة الويب (وضع الفشل المغلق)." , en: "Web auth token unresolvable (fail-closed)." },
  "errors.sse_serialization_error": {  fa: "خطا در تبدیل داده‌های جریان زنده.", de: "Fehler beim Serialisieren der Live-Stream-Daten.", es: "Error al serializar los datos de la transmisión en vivo.", ar: "خطأ في تسلسل بيانات البث المباشر." , en: "The live stream payload could not be serialized." },
  "errors.trace_stream_error": {  fa: "جریان تصمیم قطع شد.", de: "Der Entscheidungs-Stream wurde unterbrochen.", es: "Se interrumpió la transmisión de decisiones.", ar: "انقطع بث القرارات." , en: "The decision stream was interrupted." },
  "errors.trace_stream_tick_error": {  fa: "تیک جریان تصمیم نامعتبر بود.", de: "Ein Entscheidungs-Stream-Tick war ungültig.", es: "Un tick de la transmisión de decisiones no era válido.", ar: "كانت علامة بث القرارات غير صالحة." , en: "A decision stream tick was invalid." },
  "errors.trace_observer_error": {  fa: "ناظر تصمیم دچار خطا شد.", de: "Der Entscheidungs-Beobachter meldete einen Fehler.", es: "El observador de decisiones reportó un error.", ar: "أبلغ مراقب القرارات عن خطأ." , en: "The decision observer reported an error." },
  "errors.news_unavailable": {  fa: "زیرسیستم اخبار در دسترس نیست.", de: "Das Nachrichten-Subsystem ist nicht verfügbar.", es: "El subsistema de noticias no está disponible.", ar: "نظام الأخبار الفرعي غير متاح." , en: "The news subsystem is unavailable." },
  "errors.news_toggle_failed": {  fa: "تغییر وضعیت اخبار ناموفق بود.", de: "Der Nachrichten-Schalter konnte nicht umgestellt werden.", es: "No se pudo cambiar el estado de las noticias.", ar: "فشل تبديل حالة الأخبار." , en: "The news toggle could not be changed." },
  "errors.news_toggle_rejected": {  fa: "تغییر وضعیت اخبار رد شد.", de: "Der Nachrichten-Schalter wurde abgelehnt.", es: "Se rechazó el cambio de estado de las noticias.", ar: "رُفض تبديل حالة الأخبار." , en: "The news toggle was rejected." },
  "errors.news_toggle_state_failed": {  fa: "خواندن وضعیت فعلی اخبار ناموفق بود.", de: "Der aktuelle Nachrichten-Status konnte nicht gelesen werden.", es: "No se pudo leer el estado actual de las noticias.", ar: "فشلت قراءة الحالة الحالية للأخبار." , en: "The current news state could not be read." },
  "errors.news_auto_analysis_failed": {  fa: "تحلیل خودکار اخبار ناموفق بود.", de: "Die automatische Nachrichtenanalyse ist fehlgeschlagen.", es: "Falló el análisis automático de noticias.", ar: "فشل التحليل التلقائي للأخبار." , en: "Automatic news analysis failed." },
  "errors.news_auto_analysis_rejected": {  fa: "تحلیل خودکار اخبار رد شد.", de: "Die automatische Nachrichtenanalyse wurde abgelehnt.", es: "Se rechazó el análisis automático de noticias.", ar: "رُفض التحليل التلقائي للأخبار." , en: "Automatic news analysis was rejected." },
  "errors.news_auto_analysis_state_failed": {  fa: "خواندن وضعیت تحلیل خودکار ناموفق بود.", de: "Der Status der automatischen Analyse konnte nicht gelesen werden.", es: "No se pudo leer el estado del análisis automático.", ar: "فشلت قراءة حالة التحليل التلقائي." , en: "The automatic analysis state could not be read." },
  "errors.cooldown": {  fa: "در حالت خنک‌کاری — لطفاً کمی بعد تلاش کنید.", de: "Abkühlphase — bitte etwas später erneut versuchen.", es: "En período de espera — inténtelo de nuevo más tarde.", ar: "في فترة التهدئة — حاول مرة أخرى لاحقًا." , en: "Cooling down — please try again shortly." },
  "errors.ai_not_configured": {  fa: "تحلیلگر هوش مصنوعی پیکربندی نشده است.", de: "Die KI-Analyse ist nicht konfiguriert.", es: "El análisis por IA no está configurado.", ar: "تحليل الذكاء الاصطناعي غير مُهيّأ." , en: "The AI analyst is not configured." },
  "errors.article_not_found": {  fa: "مقاله یافت نشد.", de: "Der Artikel wurde nicht gefunden.", es: "No se encontró el artículo.", ar: "لم يُعثر على المقال." , en: "The article was not found." },
  "errors.liquidity_toggle_failed": {  fa: "تغییر وضعیت نقدشوندگی ناموفق بود.", de: "Der Liquiditäts-Schalter konnte nicht umgestellt werden.", es: "No se pudo cambiar el estado de la liquidez.", ar: "فشل تبديل حالة السيولة." , en: "The liquidity toggle could not be changed." },
  "errors.skipped_already_analyzed": {  fa: "رد شد — همین محتوا پیش‌تر تحلیل شده است.", de: "Übersprungen — dieser Inhalt wurde bereits analysiert.", es: "Omitido — este contenido ya fue analizado.", ar: "تم تخطّيه — حُلل هذا المحتوى مسبقًا." , en: "Skipped — this content was already analyzed." },
  "errors.research_engine_unavailable": {  fa: "موتور پژوهش در دسترس نیست.", de: "Die Research-Engine ist nicht verfügbar.", es: "El motor de investigación no está disponible.", ar: "محرك البحث غير متاح." , en: "The research engine is unavailable." },
  "errors.strategy_not_found": {  fa: "استراتژی یافت نشد.", de: "Die Strategie wurde nicht gefunden.", es: "No se encontró la estrategia.", ar: "لم يُعثر على الاستراتيجية." , en: "The strategy was not found." },
  "errors.factory_unavailable": {  fa: "کارخانه استراتژی در دسترس نیست.", de: "Die Strategie-Fabrik ist nicht verfügbar.", es: "La fábrica de estrategias no está disponible.", ar: "مصنع الاستراتيجيات غير متاح." , en: "The strategy factory is unavailable." },
  "errors.strategy_factory_disabled": {  fa: "کارخانه استراتژی غیرفعال است.", de: "Die Strategie-Fabrik ist deaktiviert.", es: "La fábrica de estrategias está deshabilitada.", ar: "مصنع الاستراتيجيات معطّل." , en: "The strategy factory is disabled." },
  "errors.provider_not_configured": {  fa: "ارائه‌دهنده پیکربندی نشده است.", de: "Der Anbieter ist nicht konfiguriert.", es: "El proveedor no está configurado.", ar: "الموفّر غير مُهيّأ." , en: "The provider is not configured." },
  "errors.cannot_enable_config_incomplete": {  fa: "فعال‌سازی ممکن نیست — پیکربندی ناقص است.", de: "Aktivierung nicht möglich — Konfiguration ist unvollständig.", es: "No se puede habilitar — la configuración está incompleta.", ar: "لا يمكن التفعيل — التهيئة غير مكتملة." , en: "Cannot enable — the configuration is incomplete." },
  "errors.db_unreachable": {  fa: "پایگاه داده در دسترس نیست.", de: "Die Datenbank ist nicht erreichbar.", es: "No se puede acceder a la base de datos.", ar: "تعذّر الوصول إلى قاعدة البيانات." , en: "The database is not reachable." },
  "errors.pg_driver_missing": {  fa: "این عملیات به PostgreSQL نیاز دارد، اما psycopg نصب نشده است.", de: "Diese Aktion erfordert PostgreSQL, aber psycopg ist nicht installiert.", es: "Esta acción requiere PostgreSQL, pero psycopg no está instalado.", ar: "تتطلب هذه العملية PostgreSQL، لكن psycopg غير مثبّت." , en: "This action needs PostgreSQL, but psycopg is not installed here." },
  "errors.db_console_error": {  fa: "خطا در کنسول پایگاه داده.", de: "Der Datenbank-Konsolenbefehl ist fehlgeschlagen.", es: "El comando de la consola de la base de datos falló.", ar: "فشل أمر وحدة تحكم قاعدة البيانات." , en: "The database console command failed." },
  "errors.train_input_rejected": {  fa: "ورودی آموزش رد شد.", de: "Die Trainingseingabe wurde abgelehnt.", es: "Se rechazó la entrada de entrenamiento.", ar: "رُفضت مدخلات التدريب." , en: "The training input was rejected." },
  "errors.train_already_running": {  fa: "آموزش از قبل در حال اجرا است.", de: "Das Training läuft bereits.", es: "El entrenamiento ya está en ejecución.", ar: "التدريب قيد التشغيل بالفعل." , en: "Training is already running." },
  "errors.train_backend_invalid": {  fa: "بک‌اند آموزش نامعتبر است.", de: "Das Trainings-Backend ist ungültig.", es: "El backend de entrenamiento no es válido.", ar: "خادم التدريب غير صالح." , en: "The training backend is invalid." },
  "errors.training_env_blocked": {  fa: "محیط آموزش مسدود شده است.", de: "Die Trainingsumgebung ist gesperrt.", es: "El entorno de entrenamiento está bloqueado.", ar: "بيئة التدريب محظورة." , en: "The training environment is blocked." },
  "errors.model_install_engine_running": {  fa: "نصب مدل ممکن نیست — موتور در حال اجراست.", de: "Modellinstallation nicht möglich — die Engine läuft.", es: "No se puede instalar el modelo — el motor está en ejecución.", ar: "لا يمكن تثبيت النموذج — المحرك قيد التشغيل." , en: "Cannot install a model while the engine is running." },
  "errors.promotion_blocked": {  fa: "ارتقای مدل مسدود شد.", de: "Die Modellbeförderung wurde blockiert.", es: "Se bloqueó la promoción del modelo.", ar: "حُجب ترقية النموذج." , en: "The model promotion was blocked." },
  "errors.send_failed": {  fa: "ارسال ناموفق بود.", de: "Der Versand ist fehlgeschlagen.", es: "Falló el envío.", ar: "فشل الإرسال." , en: "Sending failed." },
  "errors.notifier_unavailable": {  fa: "سیستم اعلان در دسترس نیست.", de: "Das Benachrichtigungssystem ist nicht verfügbar.", es: "El sistema de notificaciones no está disponible.", ar: "نظام الإشعارات غير متاح." , en: "The notifier is not available." },
  "errors.notifier_disabled": {  fa: "اعلان‌ها غیرفعال هستند — ابتدا تنظیمات را ذخیره کنید.", de: "Benachrichtigungen sind deaktiviert — zuerst speichern, dann erneut.", es: "Las notificaciones están deshabilitadas — guárdalas primero.", ar: "الإشعارات معطّلة — احفظ الإعدادات أولاً." , en: "Notifications are disabled — save the settings first, then retry." },
  "errors.settings_update_failed": {  fa: "به‌روزرسانی تنظیمات ناموفق بود.", de: "Das Aktualisieren der Einstellungen ist fehlgeschlagen.", es: "Falló la actualización de la configuración.", ar: "فشل تحديث الإعدادات." , en: "The settings update failed." },
  "errors.password_mismatch": {  fa: "رمز عبور مطابقت ندارد.", de: "Die Passwörter stimmen nicht überein.", es: "Las contraseñas no coinciden.", ar: "كلمتا المرور غير متطابقتين." , en: "The passwords do not match." },
  "errors.mt5_rate_history_failed": {  fa: "دریافت تاریخچه نرخ MT5 ناموفق بود.", de: "Das Abrufen der MT5-Kurshistorie ist fehlgeschlagen.", es: "Falló la obtención del historial de cotizaciones de MT5.", ar: "فشل جلب سجل أسعار MT5." , en: "Fetching the MT5 rate history failed." },
  "errors.candidate_not_found": {  fa: "کاندیدای مدل یافت نشد.", de: "Der Modellkandidat wurde nicht gefunden.", es: "No se encontró el candidato del modelo.", ar: "لم يُعثر على مرشح النموذج." , en: "The model candidate was not found." },
  "errors.run_not_found": {  fa: "اجرای پژوهش یافت نشد.", de: "Der Research-Lauf wurde nicht gefunden.", es: "No se encontró la ejecución de investigación.", ar: "لم يُعثر على تشغيل البحث." , en: "The research run was not found." },
  "errors.gate_not_found": {  fa: "گیت یافت نشد.", de: "Das Gate wurde nicht gefunden.", es: "No se encontró el gate.", ar: "لم يُعثر على البوابة." , en: "The gate was not found." },
  "errors.gate_already_running": {  fa: "گیت از قبل در حال اجرا است.", de: "Das Gate läuft bereits.", es: "El gate ya está en ejecución.", ar: "البوابة قيد التشغيل بالفعل." , en: "The gate is already running." },
  "errors.http_0": {  fa: "بک‌اند در دسترس نیست.", de: "Das Backend ist nicht erreichbar.", es: "No se puede acceder al backend.", ar: "تعذّر الوصول إلى الخادم الخلفي." , en: "Backend unreachable." },
  "errors.http_401": {  fa: "احراز هویت لازم است.", de: "Authentifizierung erforderlich.", es: "Se requiere autenticación.", ar: "مطلوب المصادقة." , en: "Authentication required." },
  "errors.http_403": {  fa: "دسترسی مجاز نیست.", de: "Zugriff nicht erlaubt.", es: "Acceso no permitido.", ar: "الوصول غير مسموح." , en: "Access not allowed." },
  "errors.http_404": {  fa: "منبع یافت نشد.", de: "Die Ressource wurde nicht gefunden.", es: "No se encontró el recurso.", ar: "لم يُعثر على المورد." , en: "The resource was not found." },
  "errors.http_422": {  fa: "داده‌های ارسالی نامعتبر بودند.", de: "Die übermittelten Daten waren ungültig.", es: "Los datos enviados no eran válidos.", ar: "كانت البيانات المرسلة غير صالحة." , en: "The submitted data was invalid." },
  "errors.http_429": {  fa: "درخواست‌های بیش از حد — کمی بعد تلاش کنید.", de: "Zu viele Anfragen — bitte später erneut.", es: "Demasiadas solicitudes — inténtelo más tarde.", ar: "طلبات كثيرة — حاول لاحقًا." , en: "Too many requests — please try again shortly." },
  "errors.http_500": {  fa: "خطای داخلی سرور.", de: "Interner Serverfehler.", es: "Error interno del servidor.", ar: "خطأ داخلي في الخادم." , en: "Internal server error." },
  "errors.http_502": {  fa: "بک‌اند در دسترس نیست.", de: "Das Backend ist nicht erreichbar.", es: "No se puede acceder al backend.", ar: "تعذّر الوصول إلى الخادم الخلفي." , en: "Backend unreachable." },
  "errors.http_503": {  fa: "سرویس موقتاً در دسترس نیست.", de: "Der Dienst ist vorübergehend nicht verfügbar.", es: "El servicio no está disponible temporalmente.", ar: "الخدمة غير متاحة مؤقتًا." , en: "The service is temporarily unavailable." },
  "errors.http_504": {  fa: "زمان درخواست به پایان رسید.", de: "Die Anfrage hat das Zeitlimit überschritten.", es: "La solicitud superó el tiempo límite.", ar: "انتهت مهلة الطلب." , en: "The request timed out." },
  "errors.unknown": {  fa: "خطای ناشناخته رخ داد.", de: "Ein unbekannter Fehler ist aufgetreten.", es: "Ocurrió un error desconocido.", ar: "حدث خطأ غير معروف." , en: "Unknown error." },
  "errors.unknown_reference": {  fa: "خطای ناشناخته (کد: {code}) — مرجع: {requestId}", de: "Unbekannter Fehler (Code: {code}) — Referenz: {requestId}", es: "Error desconocido (código: {code}) — referencia: {requestId}", ar: "حدث خطأ غير معروف (الرمز: {code}) — المرجع: {requestId}" , en: "Unknown error (code: {code}) — reference: {requestId}" },
  "errors.backend_unreachable": {  fa: "بک‌اند در دسترس نیست.", de: "Das Backend ist nicht erreichbar.", es: "No se puede acceder al backend.", ar: "تعذّر الوصول إلى الخادم الخلفي." , en: "Backend unreachable." },
};
