"""AI failure triage for CI/CD Telegram summaries (BUG-300).

The Telegram feed already delivers WHAT failed (structured run/release/PR
summaries built from ci-results/). This module adds WHY — a short,
pro-prompt-driven root-cause analysis generated by the operator-configured
OpenAI-compatible endpoint (GitHub Actions secrets ``AI_HOST`` / ``AI_KEY``,
optionally ``AI_MODEL``) — and a hard rule that the notification must
still go out when the AI is not usable.

Reachability gate (the "timer" contract)
-----------------------------------------
Before ANY completion call we probe ``{AI_HOST}/models``:

1. TCP connect phase capped by ``AI_PROBE_CONNECT_SEC`` (default 2.0 s) —
   an unroutable host fails fast instead of hanging the notify step.
2. Full response budget ``AI_PROBE_TIMEOUT_SEC`` (default 4.0 s); HTTP 200
   with a parseable model list means the endpoint is alive.
3. A healthy probe that took longer than ``AI_PROBE_SLOW_SEC`` (default
   2.5 s) is classified SLOW — completion is still attempted once, then
   the endpoint is marked degraded for the rest of the process (circuit
   opened) so a half-alive host cannot stall every notification lane.
4. Probe verdicts are cached per (scheme,host,port) for
   ``AI_PROBE_CACHE_SEC`` (default 120 s) — many notifies in one job share
   one probe instead of re-paying the timer.

Fallback chain (never blocks, never silent)
-------------------------------------------
* endpoint not configured            -> RULES fallback, provenance UNCONFIGURED
* probe refused/timed out/HTTP error -> RULES fallback, provenance DOWN
* completion failed/timeout/bad body -> RULES fallback, provenance CHAT_FAILED
* rules found nothing to say         -> still delivered with provenance
                                        RULES_EMPTY so the gate state is
                                        visible on the channel

Safety
------
* Outbound text is redacted (``redact_secrets``) and additionally scrubbed
  of the literal configured secret values (AI_KEY / bot token) before it
  leaves the process — the AI host never sees repo credentials.
* The AI endpoint's response is HTML-escaped by the caller before it can
  reach Telegram (prompt-injection to a messaging channel is treated as
  untrusted content).
* ``AI_HOST`` over plain http is allowed (operator choice) but flagged
  ``PLAINTEXT_HOST`` in the result so logs/docs keep the audit trail.
* Every public function returns a dict/JSON path; nothing raises into CI.
"""

from __future__ import annotations

import json
import os
import re
import socket
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# Configuration surface
# ---------------------------------------------------------------------------

AI_HOST_ENV = "AI_HOST"
AI_KEY_ENV = "AI_KEY"
AI_MODEL_ENV = "AI_MODEL"
DEFAULT_MODEL = "coding"


def _float_env(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, "") or default)
    except ValueError:
        return default


PROBE_CONNECT_SEC = _float_env("AI_PROBE_CONNECT_SEC", 2.0)
#: /models responses can be large slow-to-serialize even on healthy combo
#: hosts (observed ~5 s for a 500 KB catalog) — the connect timer is what
#: catches DEAD hosts fast; this budget only bounds the response phase.
PROBE_TIMEOUT_SEC = _float_env("AI_PROBE_TIMEOUT_SEC", 8.0)
PROBE_SLOW_SEC = _float_env("AI_PROBE_SLOW_SEC", 2.5)
PROBE_CACHE_SEC = _float_env("AI_PROBE_CACHE_SEC", 120.0)
CHAT_TIMEOUT_SEC = _float_env("AI_CHAT_TIMEOUT_SEC", 45.0)
#: Hard character budget for outbound context (prompt sizing + cost bound).
MAX_CONTEXT_CHARS = int(_float_env("AI_MAX_CONTEXT_CHARS", 10000))

#: provenance vocabulary (stable — tests and docs pin these strings)
PROV_AI = "AI"
PROV_UNCONFIGURED = "AI_UNCONFIGURED"
PROV_DOWN = "AI_UNREACHABLE"
PROV_CHAT_FAILED = "AI_CHAT_FAILED"
PROV_RULES_EMPTY = "AI_RULES_EMPTY"

#: short aliases (stable vocabulary for tests/docs)
AI = PROV_AI


@dataclass
class Endpoint:
    host: str
    key: str
    model: str
    plaintext: bool = False

    @classmethod
    def from_env(cls) -> Endpoint | None:
        host = (os.environ.get(AI_HOST_ENV) or "").strip().rstrip("/")
        key = (os.environ.get(AI_KEY_ENV) or "").strip()
        if not host or not key:
            return None
        if not host.startswith(("http://", "https://")):
            host = "https://" + host
        model = (os.environ.get(AI_MODEL_ENV) or "").strip() or DEFAULT_MODEL
        return cls(host=host, key=key, model=model, plaintext=host.startswith("http://"))


# ---------------------------------------------------------------------------
# Reachability gate (probe + timers + circuit cache)
# ---------------------------------------------------------------------------

#: cache key -> (monotonic_time, verdict dict, ttl_sec). Negative verdicts
#: cache SHORT (15 s) so flaky/intermittent hosts get retried quickly —
#: combo endpoints frequently 500/timeout on 1-in-N calls; positive verdicts
#: cache for PROBE_CACHE_SEC so N notifies in one job pay the probe once.
_PROBE_CACHE: dict[str, tuple[float, dict[str, Any], float]] = {}


def _cache_key(ep: Endpoint) -> str:
    p = urlparse(ep.host)
    return f"{p.scheme}://{p.hostname}:{p.port or (80 if p.scheme == 'http' else 443)}"


def _tcp_reachable(url: str, connect_sec: float) -> tuple[bool, float]:
    """Phase-1 timer: pure socket connect, no HTTP, no TLS handshake wait."""
    p = urlparse(url)
    host = p.hostname or ""
    port = p.port or (80 if p.scheme == "http" else 443)
    t0 = time.monotonic()
    try:
        with socket.create_connection((host, port), timeout=connect_sec):
            return True, time.monotonic() - t0
    except OSError:
        return False, time.monotonic() - t0


def probe_reachable(ep: Endpoint, *, force: bool = False) -> dict[str, Any]:
    """Gate check: status OK | SLOW_OK | TCP_REFUSED | TIMEOUT | HTTP_ERROR | ERROR.

    OK/SLOW_OK mean completions may be attempted (SLOW_OK once before the
    circuit opens). Everything else means: use the fallback right now.
    """
    key = _cache_key(ep)
    now = time.monotonic()
    if not force:
        hit = _PROBE_CACHE.get(key)
        if hit and now - hit[0] < hit[2]:
            cached = dict(hit[1], cached=True)
            # circuit open semantics: a SLOW verdict is attempted once (uncached
            # pass); a CACHED slow verdict means "already tried, still slow" ->
            # degrade to fallback for the rest of the TTL window.
            if cached.get("status") == "SLOW_OK":
                cached["status"] = "SLOW_DEGRADED"
            return cached

    verdict: dict[str, Any] = {
        "status": "ERROR",
        "connect_sec": None,
        "total_sec": None,
        "models": 0,
        "error": "",
    }
    reachable, connect_sec = _tcp_reachable(ep.host, PROBE_CONNECT_SEC)
    verdict["connect_sec"] = round(connect_sec, 3)
    if not reachable:
        verdict["status"] = "TCP_REFUSED"
        verdict["error"] = "connect refused/failed"
        _PROBE_CACHE[key] = (now, verdict, 15.0)
        return dict(verdict)

    t0 = time.monotonic()
    req = urllib.request.Request(
        ep.host + "/models",
        headers={"Authorization": f"Bearer {ep.key}", "Accept": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=PROBE_TIMEOUT_SEC) as resp:
            verdict["status"] = "OK" if resp.status == 200 else "HTTP_ERROR"
            # Read a bounded head only: some hosts serialize the WHOLE model
            # catalog (500KB+) and a full read blows the probe timer budget on
            # healthy endpoints. Presence of the list key is enough evidence.
            head = resp.read(4096).decode("utf-8", "replace")
            if verdict["status"] == "OK" and '"data"' not in head:
                verdict["status"] = "HTTP_ERROR"
                verdict["error"] = "models list shape unexpected"
    except urllib.error.HTTPError as err:
        verdict["status"] = "HTTP_ERROR"
        verdict["error"] = f"HTTP {err.code}"
    except TimeoutError:  # socket.timeout is an alias on 3.10+
        verdict["status"] = "TIMEOUT"
        verdict["error"] = f">{PROBE_TIMEOUT_SEC}s response budget"
    except Exception as err:  # DNS, TLS, reset...
        verdict["status"] = "ERROR"
        verdict["error"] = str(err)[:160]
    total = time.monotonic() - t0
    verdict["total_sec"] = round(total, 3)
    if verdict["status"] == "OK" and total > PROBE_SLOW_SEC:
        verdict["status"] = "SLOW_OK"
    ttl = PROBE_CACHE_SEC if verdict["status"] in ("OK", "SLOW_OK") else 15.0
    _PROBE_CACHE[key] = (now, verdict, ttl)
    return dict(verdict, cached=False)


# ---------------------------------------------------------------------------
# Completion call
# ---------------------------------------------------------------------------


def _parse_sse(text: str) -> str:
    """Join streamed delta/content fragments when the host SSEs despite stream=false."""
    parts: list[str] = []
    for line in text.splitlines():
        if not line.startswith("data:"):
            continue
        payload = line[5:].strip()
        if not payload or payload == "[DONE]":
            continue
        try:
            obj = json.loads(payload)
        except Exception:
            continue
        for ch in obj.get("choices") or []:
            delta = ch.get("delta") or {}
            piece = delta.get("content") or ""
            if piece:
                parts.append(piece)
    return "".join(parts)


def chat_completion(
    ep: Endpoint, system_prompt: str, user_prompt: str, *, timeout_sec: float | None = None
) -> tuple[str | None, str]:
    """Single non-streaming chat call. Returns (text, error); exactly one is None-ish."""
    body = json.dumps(
        {
            "model": ep.model,
            "stream": False,
            "max_tokens": 1400,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        ep.host + "/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {ep.key}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout_sec or CHAT_TIMEOUT_SEC) as resp:
            raw = resp.read(600_000).decode("utf-8", "replace")
    except urllib.error.HTTPError as err:
        return None, f"HTTP {err.code}"
    except TimeoutError:  # socket.timeout is an alias on 3.10+
        return None, "timeout"
    except Exception as err:
        return None, str(err)[:160]

    try:
        obj = json.loads(raw)
        text = ((obj.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
        if not text.strip():
            text = _parse_sse(raw)
    except Exception:
        text = _parse_sse(raw)
    # strip reasoning blocks some hosts leak into content
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    if not text:
        return None, "empty completion"
    return text[:4000], ""


# ---------------------------------------------------------------------------
# Pro prompts (per event kind) — the analysis charter for each summary lane
# ---------------------------------------------------------------------------

_SYSTEM = (
    "You are the lead CI/CD analyst for the NexusTradingForexBot (NSE) repo — a "
    "production PyTorch + MetaTrader 5 XAUUSD scalp engine where wrong merges can "
    "lose real money. You receive a JSON evidence bundle for ONE completed GitHub "
    "Actions run (checks, jobs, failed steps, junit/coverage, PR diff stats, lanes "
    "touched, review state, recent comments). Analyze it like a senior engineer "
    "doing a release-block review. You never speculate beyond the evidence; you "
    "name the exact file/test/check you relied on. You know this repo's failure "
    "taxonomy: dependency-lock drift (uv 0.12.10 regen), ruff-format red blocking "
    "mypy/pytest downstream (root cause is format, not the blocked checks), "
    "core.autocrlf=true CRLF noise, squash-carrier stale bases creating phantom "
    "reds, maintenance-window flakes, known-foreign reds (test_operator_routes "
    "auth-401 x15), force-push-banned policy (DEC-0008), release_auth_gate "
    "(no publish without green main CI on the exact SHA), 1 approving review + "
    "'Validate documentation' context required, and safety invariants (fail-closed "
    "gates, champion model protection, broker-truth reconciliation).\n"
    "Output EXACTLY these sections, one line each, prefixed by the literal label, "
    "markdown-free, <=230 words total:\n"
    "WHY: <root cause of the outcome — for green runs, WHY it passed and what that proves>\n"
    "EVIDENCE: <the 1-3 decisive data points, named>\n"
    "VERDICT: <GOOD-TO-MERGE | MERGE-AFTER-FIX | DO-NOT-MERGE | INVESTIGATE — pick one>\n"
    "RISK: <what is good/bad about this change: scope, safety-boundary touches (hot "
    "path, model gates, execution/risk, auth), missing test coverage, contract or "
    "registry updates the diff should have included>\n"
    "CHECK: <the concrete next actions an agent/human must take IN ORDER, including "
    "exact commands or files when possible>\n"
    "COMMENT: <one ready-to-post review comment for the PR author, <=40 words>\n"
    "CONFIDENCE: <high|medium|low>"
)

PROMPTS: dict[str, str] = {
    "ci-failure": (
        "FINAL CI REVIEW. Judge the whole run: why it failed (or why passing is "
        "credible), whether the failure is real-code, flake, drift, or wiring; "
        "whether green legs prove anything about the touched lanes; the merge "
        "safety of the triggering change; the fix sequence."
    ),
    "release-failure": (
        "FINAL RELEASE REVIEW. The publish rule is absolute: main CI must be "
        "green on the EXACT SHA (release_auth_gate) and a runtime-smoke failure "
        "must stop publication. State which stage broke (auth-gate/validate/"
        "gates/build/signing/publish/verify), why, what it means for the tag "
        "users get, and the recovery order. If green, confirm what the gates "
        "proved and any residual risk of the shipped artifacts."
    ),
    "security": (
        "FINAL SECURITY REVIEW. Classify every finding as actionable vs "
        "known-suppressed/noise; state exploitability in this app's actual "
        "trust boundary (localhost web console, HttpOnly cookie auth, "
        "fail-closed gates); name the first file to fix and the sanitizer "
        "shape that stays linear-time (CodeQL redos lesson from BUG-270)."
    ),
    "pr-analysis": (
        "FINAL PR REVIEW on this new commit set. Is this change a good idea "
        "for THIS repo: does it respect ownership seams, keep money-paths "
        "fail-closed, add real tests (not weakened goldens), update registries "
        "(taskboard/bugs/DEC) when contracts move, avoid CI-wiring or lockfile "
        "side effects? Judge CI legs and review state together into a merge "
        "recommendation the coordinator can act on."
    ),
    "push-summary": (
        "FINAL PUSH REVIEW of commits landed on this branch. Summarize intent, "
        "whether the run validated what changed, cross-lane risk (shared files "
        "with other active agent lanes, swarm_log/taskboard contention), and "
        "what to watch next."
    ),
}


# ---------------------------------------------------------------------------
# Outbound sanitization + context loading
# ---------------------------------------------------------------------------


def _redactor():
    try:
        from nexus_scalp.observability.telegram_transport import redact_secrets

        return redact_secrets
    except Exception:  # offline import failure -> local fallback patterns

        def redact_secrets(text: str) -> str:
            out = re.sub(r"sk-[A-Za-z0-9_\-]{12,}", "[REDACTED_SK]", text)
            out = re.sub(r"\d{8,10}:[A-Za-z0-9_-]{25,}", "[REDACTED_BOT_TOKEN]", out)
            return re.sub(
                r"(?i)(password|passwd|secret|api[_-]?key|token|auth|credential)\s*[=:]\s*\S+",
                r"\1=[REDACTED]",
                out,
            )

    return redact_secrets


def sanitize(text: str, ep: Endpoint | None = None) -> str:
    """Redact secret shapes, then strip literal configured secret values."""
    out = _redactor()(text or "")
    if ep:
        for literal in (
            ep.key,
            os.environ.get("TELEGRAM_BOT_TOKEN", ""),
            os.environ.get("GITHUB_TOKEN", ""),
        ):
            if literal and len(literal) >= 8:
                out = out.replace(literal, "[REDACTED]")
    return out[:MAX_CONTEXT_CHARS]


def load_context(path: str | Path) -> dict[str, Any]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {"raw": data}
    except Exception as err:
        return {"context_load_error": str(err)[:120]}


# ---------------------------------------------------------------------------
# Deterministic fallback (the "find the problem without AI" rules)
# ---------------------------------------------------------------------------

_RULES: list[tuple[str, str, str]] = [
    # (regex over serialized evidence, verdict clause, cheapest first check)
    (
        r"requirements\.lock|Dependency drift|pyproject",
        "dependency lock drift (lock vs pyproject mismatch)",
        "python scripts/ci/check_dependency_drift.py",
    ),
    (
        r"ruff format|RUFF_FORMAT_RC|would be reformatted",
        "format gate red — downstream mypy/pytest checks are BLOCKED, not failed",
        "ruff format --check .",
    ),
    (
        r"eol|CRLF|LF will be replaced",
        "likely CRLF/autocrlf noise (repo is core.autocrlf=true)",
        "git diff --stat after normalizing line endings",
    ),
    (
        r"429|Retry-After|TELEGRAM_RATE_LIMIT",
        "provider/transport rate limit on the notify lane itself",
        "check notifier health_state()",
    ),
    (
        r"Merge conflict|CONFLICT \(",
        "branch is on a stale base vs main (squash-carrier drift)",
        "git merge origin/main on an integration copy",
    ),
    (
        r"CodeQL|redos|ReDoS|http-response-splitting",
        "code-scanning alert class — sanitizer must stay linear-time",
        "re-run CodeQL locally on the touched file",
    ),
    (
        r"401|UNAUTHORIZED|auth",
        "auth bootstrap/cookie regression shape (WEB-AUTH-P0 family)",
        "tests/unit/test_bug267_*",
    ),
    (
        r"test_start_smoke|model\.pt|SAFE_MODE|provision",
        "fresh-install/provisioning gate (model acquisition before start)",
        "nexus start on a clean profile per BUG-298 lanes",
    ),
    (
        r"exitcode: (124|137)|Timeout|SIGTERM",
        "runner timeout / OOM rather than an assertion failure",
        "compare runtime vs job timeout-minutes; check memory of the suite",
    ),
    (
        r"curl|network|Connection reset|getaddrinfo",
        "external network flake (known chronic on this host)",
        "gh run rerun --failed",
    ),
]


def rules_analysis(context: dict[str, Any]) -> str:
    """Deterministic one-paragraph fallback derived from the evidence text."""
    blob = json.dumps(context, default=str)
    hits: list[tuple[str, str]] = []
    for pattern, verdict, check in _RULES:
        if re.search(pattern, blob, flags=re.IGNORECASE):
            hits.append((verdict, check))
    if not hits:
        return ""
    verdict, check = hits[0]
    lines = [
        f"WHY: {verdict}",
        "EVIDENCE: rule pattern matched in the run evidence (no AI available)",
        "VERDICT: INVESTIGATE",
        "CHECK: " + " | ".join(c for _, c in hits[:3]),
        "CONFIDENCE: low (deterministic fallback — AI endpoint unavailable)",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Top-level analysis
# ---------------------------------------------------------------------------


@dataclass
class Analysis:
    kind: str
    text: str
    provenance: str
    model: str = ""
    probe: dict[str, Any] = field(default_factory=dict)
    plaintext_host: bool = False

    def to_result(self, delivered: bool) -> dict[str, Any]:
        return {
            "ok": bool(self.text),
            "kind": self.kind,
            "provenance": self.provenance,
            "model": self.model or None,
            "delivered": delivered,
            "plaintext_host": self.plaintext_host or None,
            "probe": self.probe,
            "chars": len(self.text),
        }


def analyze(kind: str, context: dict[str, Any]) -> Analysis:
    """AI summary with the reachability gate + guaranteed rules fallback.

    Never raises; always returns an Analysis (text may be empty only with
    RULES_EMPTY provenance, which the caller still reports).
    """
    ep = Endpoint.from_env()
    if ep is None:
        return Analysis(
            kind,
            rules_analysis(context),
            PROV_UNCONFIGURED if rules_analysis(context) else PROV_RULES_EMPTY,
            plaintext_host=False,
        )
    base = Analysis(kind, "", "", model=ep.model, plaintext_host=ep.plaintext)
    probe = probe_reachable(ep)
    base.probe = {k: probe.get(k) for k in ("status", "connect_sec", "total_sec", "cached")}
    if probe["status"] not in ("OK", "SLOW_OK"):
        base.text = rules_analysis(context)
        base.provenance = PROV_DOWN if base.text else PROV_RULES_EMPTY
        return base
    user = (
        PROMPTS.get(kind, PROMPTS["ci-failure"])
        + "\n\nJSON EVIDENCE:\n"
        + sanitize(json.dumps(context, default=str, sort_keys=True)[:MAX_CONTEXT_CHARS], ep)
    )
    text, _err = chat_completion(ep, _SYSTEM, user)
    if not text:
        # combo hosts flake intermittently (observed 1-in-3 on the live
        # endpoint: empty bodies, resets, 5xx between success streaks):
        # ONE bounded retry for any transient failure before degrading.
        text, _retry_err = chat_completion(
            ep, _SYSTEM, user, timeout_sec=max(15.0, CHAT_TIMEOUT_SEC * 0.6)
        )
    if not text:
        base.text = rules_analysis(context)
        base.provenance = PROV_CHAT_FAILED if base.text else PROV_RULES_EMPTY
        return base
    base.text = text
    base.provenance = PROV_AI
    return base


# ---------------------------------------------------------------------------
# Telegram emit + artifact write (entry used by scripts/ci/telegram_notify.py)
# ---------------------------------------------------------------------------


def notify_triage(
    kind: str,
    results_dir: str | Path,
    *,
    context_path: str | Path | None = None,
    send_telegram: bool = True,
) -> dict[str, Any]:
    """Analyze a summary event, append ``ai-analysis.md`` to ci-results, and
    (optionally) send a follow-up Telegram block. Exit-0 contract: all errors
    are captured into the returned result."""
    ctx = load_context(context_path) if context_path else {}
    if not ctx or set(ctx) == {"context_load_error"}:
        ctx = _context_from_results(kind, Path(results_dir))
    analysis = analyze(kind, ctx)

    out: dict[str, Any] = {"result": analysis.to_result(False)}
    written = False
    try:
        info = Path(results_dir) / "run-info"
        info.mkdir(parents=True, exist_ok=True)
        payload = {
            "kind": kind,
            "provenance": analysis.provenance,
            "model": analysis.model or None,
            "probe": analysis.probe,
            "text": analysis.text,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        (info / "ai-analysis.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
        )
        written = True
    except Exception as err:
        out["write_error"] = str(err)[:160]
    out["artifact_written"] = written

    if send_telegram and analysis.text:
        try:
            from nexus_scalp.observability.ci_telegram_reporter import CITelegramReporter
            from nexus_scalp.observability.telegram_html import format_ai_triage

            reporter = CITelegramReporter(results_dir)
            html_text = format_ai_triage(
                reporter.context(),
                kind=kind,
                analysis=analysis.text,
                provenance=analysis.provenance,
                model=analysis.model,
                probe=analysis.probe,
            )
            out["result"] = analysis.to_result(True)
            out["telegram"] = reporter._send_text(html_text, event_type="AI_TRIAGE")
        except Exception as err:
            out["telegram"] = {"ok": False, "error": str(err)[:200]}
    return out


def _context_from_results(kind: str, results: Path) -> dict[str, Any]:
    """Build evidence purely from a ci-results/ tree (workflow-side use).

    Log tails are truncated but kept; they pass through sanitize() at the
    analyze() boundary before anything leaves the process.
    """
    ctx: dict[str, Any] = {"kind": kind}
    info = results / "run-info"
    if info.is_dir():
        checks = {}
        for p in sorted(info.glob("*.json")):
            if p.name in ("ai-analysis.json", "secrets-present.json"):
                continue
            try:
                d = json.loads(p.read_text(encoding="utf-8"))
                checks[p.stem] = d.get("status", "unknown")
            except Exception:
                checks[p.stem] = "unreadable"
        ctx["checks"] = checks
    try:
        from nexus_scalp.observability.ci_telegram_reporter import CITelegramReporter

        rep = CITelegramReporter(results)
        stats = rep.junit_stats()
        ctx["junit"] = stats
        ctx["failed_tests"] = rep.failed_test_names(limit=25)
        cov = rep.coverage_percent()
        if cov is not None:
            ctx["coverage_percent"] = round(cov, 1)
    except Exception:
        pass
    for name, rel in (
        ("pytest_tail", "pytest/pytest.txt"),
        ("mypy_tail", "mypy/mypy.txt"),
        ("ruff_tail", "ruff/lint.txt"),
    ):
        p = results / rel
        if p.exists():
            try:
                ctx[name] = p.read_text(encoding="utf-8", errors="replace")[-3000:]
            except Exception:
                pass
    return ctx
