"""CI/CD Telegram reporter — the orchestrator for NSE CI observability.

Consumes the ci-results/ tree produced by the CI pipeline (see
scripts/ci/make_ci_results.py) plus GitHub Actions environment (GITHUB_*),
renders structured Telegram HTML messages, and sends them through the
canonical notifier + document transporter.

Policies (per the enterprise observability spec):

* totals/flags pass through reads of ci-results/run-info/*.json — never
  guessed from the environment
* message splitting: HTML-valid chunks, Telegram size caps respected
* file uploads: only files that exist under ci-results/, redacted before
  send, with informative captions
* failure isolation: any Telegram error is returned as a structured result;
  it NEVER propagates to fail CI
* chat id: TELEGRAM_CHAT_ID (GitHub Actions secret) > NEXUS_TELEGRAM_ADMIN_ID
  > provided default; never hardcoded in the repo
"""

from __future__ import annotations

import json
import logging
import os
import zipfile
from pathlib import Path
from typing import Any

from nexus_scalp.observability.telegram_html import (
    CIContext,
    format_artifact_summary,
    format_release_failure,
    format_release_started,
    format_release_success,
    format_run_cancelled,
    format_run_failure,
    format_run_started,
    format_run_success,
    format_test_summary,
    split_html_message,
)
from nexus_scalp.observability.telegram_notifier import TelegramNotifier
from nexus_scalp.observability.telegram_transport import (
    TelegramDocumentTransporter,
    redact_secrets,
)

logger = logging.getLogger(__name__)

#: Files eligible for upload from ci-results/ (canonical + useful).
_UPLOADABLE = (
    "run-info/summary.md",
    "run-info/manifest.json",
    "run-info/SHA256SUMS.txt",
    "pytest/junit.xml",
    "pytest/coverage.xml",
    "pytest/pytest.txt",
    "ruff/lint.json",
    "ruff/lint.txt",
    "mypy/mypy.txt",
    "format/format.txt",
)

_DIAGNOSTIC_README = """NSE CI diagnostic bundle
========================
Generated by the CI observability pipeline. Contains machine-readable
results for workflow run %(workflow)s #%(run_number)s (commit %(sha)s).

Files:
- summary.json : per-check status + exit codes (run-info/*.json)
- failed-tests.txt : failed test names extracted from junit.xml
- junit.xml : pytest JUnit results
- coverage.xml : Cobertura coverage
- pytest.txt : pytest stdout/stderr log
- artifact-manifest.json : ci-results/run-info/manifest.json
- SHA256SUMS.txt : checksums of all result files
"""


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default) or default


class CITelegramReporter:
    """Report CI/release events to Telegram from a ci-results/ tree."""

    def __init__(
        self,
        results_dir: str | Path,
        *,
        chat_id: str | None = None,
        bot_token: str | None = None,
        server_url: str = "https://github.com",
        repository: str = "",
        max_document_bytes: int = 20 * 1024 * 1024,
    ) -> None:
        self.results_dir = Path(results_dir)

        # Chat id resolution: explicit arg > env > USER_ID (GitHub secret) > admin_id.
        self.chat_id = (
            chat_id
            or _env("TELEGRAM_CHAT_ID")
            or _env("USER_ID")
            or _env("NEXUS_TELEGRAM_ADMIN_ID")
            or ""
        )
        # Bot token: explicit arg > TELEGRAM_BOT_TOKEN (GitHub Actions secret,
        # matches the repo's CI secrets doc) > NEXUS_TELEGRAM_BOT_TOKEN (runtime).
        self.bot_token = bot_token or _env("TELEGRAM_BOT_TOKEN") or _env("NEXUS_TELEGRAM_BOT_TOKEN")
        self.server_url = server_url or _env("GITHUB_SERVER_URL") or "https://github.com"
        self.repository = repository or _env("GITHUB_REPOSITORY")

        self.notifier = TelegramNotifier(
            bot_token=self.bot_token or "",
            admin_id=self.chat_id,
            enabled=bool(self.bot_token and self.chat_id),
        )
        self.transporter = TelegramDocumentTransporter(
            bot_token=self.bot_token or "",
            chat_id=self.chat_id,
            max_document_bytes=max_document_bytes,
        )
        self._env_digest: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Context + reads
    # ------------------------------------------------------------------

    def load_env_digest(self) -> dict[str, Any]:
        for name in ("env-digest.json", "metadata.json"):
            p = self.results_dir / "run-info" / name
            if p.exists():
                try:
                    data = json.loads(p.read_text(encoding="utf-8"))
                    if data:
                        self._env_digest = data
                        break
                except Exception:
                    continue
        return self._env_digest

    def context(self) -> CIContext:
        env = self.load_env_digest() or {}
        sha = env.get("sha") or _env("GITHUB_SHA")
        return CIContext(
            repository=env.get("repository") or self.repository,
            workflow=env.get("workflow") or _env("GITHUB_WORKFLOW"),
            run_id=env.get("run_id") or _env("GITHUB_RUN_ID"),
            run_number=env.get("run_number") or _env("GITHUB_RUN_NUMBER"),
            job=env.get("job") or _env("GITHUB_JOB"),
            attempt=env.get("run_attempt") or _env("GITHUB_RUN_ATTEMPT"),
            branch=env.get("branch") or _env("GITHUB_REF_NAME"),
            sha=sha,
            server_url=self.server_url,
        )

    def check_status(self, name: str) -> str:
        p = self.results_dir / "run-info" / f"{name}.json"
        try:
            return str(json.loads(p.read_text(encoding="utf-8")).get("status", "skipped"))
        except Exception:
            return "skipped"

    def _junit_stats_raw(self) -> dict[str, Any]:
        """Parse junit.xml; handles pytest's <testsuites> wrapper."""
        junit = self.results_dir / "pytest" / "junit.xml"
        stats = {"tests": 0, "failures": 0, "errors": 0, "skipped": 0, "time": 0.0}
        if not junit.exists():
            return stats
        try:
            import xml.etree.ElementTree as ET

            root = ET.parse(junit).getroot()
            nodes = root.findall("testsuite") if root.tag == "testsuites" else [root]
            for node in nodes:
                for attr in ("tests", "failures", "errors", "skipped", "time"):
                    if attr in node.attrib:
                        try:
                            stats[attr] += float(node.attrib[attr])
                        except ValueError:
                            pass
        except Exception:
            pass
        return stats

    def junit_stats(self) -> dict[str, int]:
        s = self._junit_stats_raw()
        return {
            "tests": int(s["tests"]),
            "failures": int(s["failures"]) + int(s["errors"]),
            "skipped": int(s["skipped"]),
            "passed": int(s["tests"]) - int(s["failures"]) - int(s["errors"]) - int(s["skipped"]),
        }

    def coverage_percent(self) -> float | None:
        p = self.results_dir / "pytest" / "coverage.xml"
        if not p.exists():
            return None
        try:
            import xml.etree.ElementTree as ET

            rate = ET.parse(p).getroot().attrib.get("line-rate")
            return float(rate) * 100.0 if rate is not None else None
        except Exception:
            return None

    def failed_test_names(self, limit: int = 20) -> list[str]:
        junit = self.results_dir / "pytest" / "junit.xml"
        names: list[str] = []
        if not junit.exists():
            return names
        try:
            import xml.etree.ElementTree as ET

            root = ET.parse(junit).getroot()
            for case in root.iter("testcase"):
                if case.find("failure") is not None or case.find("error") is not None:
                    names.append(case.attrib.get("name", "?"))
        except Exception:
            pass
        return names[:limit]

    # ------------------------------------------------------------------
    # High-level notifications (each returns a structured result; never raises)
    # ------------------------------------------------------------------

    def notify_run_started(self, *, jobs: str = "") -> dict[str, Any]:
        return self._send_text(
            format_run_started(self.context(), jobs=jobs), event_type="CI_STARTED"
        )

    def notify_run_finished(self, *, os_name: str = "") -> dict[str, Any]:
        """Dispatch SUCCESS/FAILED/CANCELLED based on ci-results statuses."""
        statuses = {
            "ruff_lint": self.check_status("ruff_lint"),
            "ruff_format": self.check_status("ruff_format"),
            "mypy": self.check_status("mypy"),
            "pytest": self.check_status("pytest"),
            "coverage": self.check_status("coverage"),
        }
        failed = [k for k, v in statuses.items() if v in ("failed", "errored")]
        cancelled = any(v == "cancelled" for v in statuses.values())

        ctx = self.context()
        # OS-matrix tagging (tests-os.yml os-finished): which leg finished.
        if os_name:
            ctx = ctx.with_job_suffix(os_name)
        stats = self.junit_stats()
        coverage = self.coverage_percent()
        failures = self.failed_test_names()
        checks = {k.replace("_", " ").title(): v for k, v in statuses.items()}

        if cancelled:
            return self._send_text(format_run_cancelled(ctx), event_type="CI_CANCELLED")
        if failed:
            next_action = f"{len(failures) or 'some'} check(s) failed — see artifact for details"
            msg = format_run_failure(
                ctx,
                tests=stats["tests"] or None,
                passed=stats["passed"],
                failed=stats["failures"],
                skipped=stats["skipped"],
                coverage=coverage,
                checks=checks,
                failures=failures,
                next_action=next_action,
            )
            result = self._send_text(msg, event_type="CI_FAILED")
            self._upload_diagnostics(ctx, reason=f"{len(failures) or '1+'} check(s) failed")
            return result
        msg = format_run_success(
            ctx,
            tests=stats["tests"] or None,
            failed=stats["failures"],
            skipped=stats["skipped"],
            coverage=coverage,
            checks=checks,
        )
        return self._send_text(msg, event_type="CI_SUCCESS")

    def notify_test_summary(self) -> dict[str, Any]:
        stats = self.junit_stats()
        msg = format_test_summary(
            total=stats["tests"],
            passed=stats["passed"],
            failed=stats["failures"],
            skipped=stats["skipped"],
            coverage=self.coverage_percent(),
            failed_names=self.failed_test_names(),
        )
        return self._send_text(msg, event_type="TEST_SUMMARY")

    def notify_release_started(self, *, tag: str = "", phase: str = "") -> dict[str, Any]:
        ctx = self.context()
        if phase:
            ctx.release_version = tag
        return self._send_text(
            format_release_started(ctx, tag=tag, phase=phase), event_type="RELEASE_STARTED"
        )

    def notify_release_success(self, *, tag: str = "") -> dict[str, Any]:
        ctx = self.context()
        ctx.release_version = tag or ctx.release_version
        stats = self.junit_stats()
        msg = format_release_success(
            ctx,
            tag=tag,
            gates=None,
            tests={
                "total": stats["tests"],
                "passed": stats["passed"],
                "failed": stats["failures"],
                "skipped": stats["skipped"],
            },
            coverage=self.coverage_percent(),
            artifacts=self._artifact_names(),
            verification=["SHA256 verified", "Artifact manifest present"],
        )
        return self._send_text(msg, event_type="RELEASE_SUCCESS")

    def notify_release_failure(
        self,
        *,
        tag: str = "",
        failed_phase: str = "",
        failed_job: str = "",
        error_class: str = "",
        error_detail: str = "",
        retry_count: int = 0,
    ) -> dict[str, Any]:
        ctx = self.context()
        ctx.release_version = tag or ctx.release_version
        msg = format_release_failure(
            ctx,
            tag=tag,
            failed_phase=failed_phase,
            failed_job=failed_job,
            retry_count=retry_count,
            error_class=error_class,
            error_detail=error_detail,
            recovery_status="REVIEW_REQUIRED",
            next_action="Inspect the diagnostic files below; fix and re-run the release.",
        )
        result = self._send_text(msg, event_type="RELEASE_FAILED")
        self._upload_diagnostics(ctx, reason="release failure")
        return result

    def notify_artifact_summary(self, *, retention_days: int | None = 30) -> dict[str, Any]:
        msg = format_artifact_summary(
            self.context(),
            artifacts=self._artifact_names(),
            verified=["SHA256SUMS.txt present", "manifest.json present"],
            retention_days=retention_days,
        )
        return self._send_text(msg, event_type="ARTIFACT_SUMMARY")

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _artifact_names(self) -> list[str]:
        out: list[str] = []
        root = self.results_dir
        if root.exists():
            for p in sorted(root.rglob("*")):
                if p.is_file():
                    out.append(p.relative_to(root).as_posix())
        return out[:30]

    def _send_text(self, html_text: str, *, event_type: str) -> dict[str, Any]:
        if not self.notifier.enabled:
            return {
                "ok": False,
                "category": "TELEGRAM_CONFIG_ERROR",
                "safe_message": "not configured",
            }
        redacted = redact_secrets(html_text)
        chunks = split_html_message(redacted)
        sent_ids: list[int] = []
        ok = True
        for chunk in chunks:
            try:
                mid = self.notifier.send(chunk, event_type=event_type, severity="INFO")
                if mid is None:
                    ok = False
                else:
                    sent_ids.append(mid)
            except Exception as err:
                logger.error("[CI_TELEGRAM] event=SEND_FAILED error=%s", err)
                ok = False
        return {
            "ok": ok,
            "chunks": len(chunks),
            "message_ids": sent_ids,
            "category": "DELIVERED" if ok else "SEND_FAILED",
        }

    def _upload_diagnostics(self, ctx: CIContext, *, reason: str) -> dict[str, Any]:
        """Upload the diagnostic bundle + key result files with captions."""
        if not self.transporter.chat_id:
            return {
                "ok": False,
                "category": "TELEGRAM_CONFIG_ERROR",
                "safe_message": "not configured",
            }

        bundle = self._build_diagnostic_bundle()
        results: dict[str, Any] = {}
        caption = (
            f"<b>Diagnostic Artifact</b>\n"
            f"<b>File:</b> {bundle.name}\n"
            f"<b>Job:</b> {esc_ctx(ctx.job)}\n"
            f"<b>Run:</b> #{ctx.run_number or ctx.run_id}\n"
            f"<b>Commit:</b> {esc_ctx(ctx.sha)}\n"
            f"<b>Reason:</b> {esc_ctx(reason)}"
        )
        results["bundle"] = self.transporter.upload(bundle, caption)

        # Also upload up to 3 key files individually (existing only).
        picks = ["pytest/junit.xml", "pytest/coverage.xml", "run-info/summary.md"]
        for rel in picks:
            p = self.results_dir / rel
            if not p.exists():
                continue
            cap = (
                f"<b>Diagnostic Artifact</b>\n"
                f"<b>File:</b> {esc_ctx(rel)}\n"
                f"<b>Run:</b> #{ctx.run_number or ctx.run_id}\n"
                f"<b>Commit:</b> {esc_ctx(ctx.sha)}\n"
                f"<b>Reason:</b> {esc_ctx(reason)}"
            )
            results[rel] = self.transporter.upload(p, cap)
        return results

    def _build_diagnostic_bundle(self, name: str = "nexus-ci-diagnostic.zip") -> Path:
        out = self.results_dir.parent / name
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
            # summary.json: per-check statuses
            summary: dict[str, Any] = {}
            info_dir = self.results_dir / "run-info"
            if info_dir.exists():
                for p in sorted(info_dir.glob("*.json")):
                    try:
                        summary[p.stem] = json.loads(p.read_text(encoding="utf-8"))
                    except Exception:
                        summary[p.stem] = {"status": "unreadable"}
            zf.writestr("summary.json", json.dumps(summary, indent=2, sort_keys=True))

            # failed-tests.txt
            names = self.failed_test_names(limit=200)
            zf.writestr("failed-tests.txt", "\n".join(names) + ("\n" if names else ""))

            # selected result files (redacted in memory)
            for rel in _UPLOADABLE:
                p = self.results_dir / rel
                if p.exists():
                    content = redact_secrets(p.read_text(encoding="utf-8", errors="replace"))
                    zf.writestr(rel.replace("/", "_"), content)
        return out


def esc_ctx(value: Any) -> str:
    """Minimal escape for captions."""
    import html as _html

    return _html.escape(str(value or "n/a"))


__all__ = ["CITelegramReporter", "redact_secrets"]
