"""
Domain Enumerations
===================
Defines immutable, strongly-typed domain constants across execution modes,
trade directions, and broker communication statuses.
"""

from enum import Enum


class ExecutionMode(str, Enum):
    """
    Defines the operational execution state of the engine.

    Invariants:
        - BACKTEST: Historical deterministic engine without external I/O.
        - REPLAY: Replays tick streams deterministically via simulation adapter.
        - PAPER: Live data streams, simulated execution engine.
        - SHADOW: Live data streams, live prediction, no execution (monitoring).
        - LIVE: Live data streams, active capital risk, broker order placement.
    """
    BACKTEST = "BACKTEST"
    REPLAY = "REPLAY"
    PAPER = "PAPER"
    SHADOW = "SHADOW"
    LIVE = "LIVE"


class ActionType(str, Enum):
    """
    Explicit action decisions generated by Signal Policy or neural network inference.
    """
    WAIT = "WAIT"
    NO_TRADE = "NO_TRADE"
    BUY = "BUY"
    SELL = "SELL"
    BUY_MARKET = "BUY_MARKET"
    SELL_MARKET = "SELL_MARKET"
    # [EXPANDED] Added Limit Order actions for Smart Order Routing and Patience strategies
    BUY_LIMIT = "BUY_LIMIT"
    SELL_LIMIT = "SELL_LIMIT"
    BUY_STOP = "BUY_STOP"
    SELL_STOP = "SELL_STOP"
    CLOSE_POSITION = "CLOSE_POSITION"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    MODIFY_SL_TP = "MODIFY_SL_TP"
    CANCEL_ORDER = "CANCEL_ORDER"


class OrderType(str, Enum):
    """
    Standardized order types matching MetaTrader 5 execution mechanisms.
    """
    BUY = "BUY"
    SELL = "SELL"
    BUY_LIMIT = "BUY_LIMIT"
    SELL_LIMIT = "SELL_LIMIT"
    BUY_STOP = "BUY_STOP"
    SELL_STOP = "SELL_STOP"


class OrderStatus(str, Enum):
    """
    Lifecycle status of an order within the internal state tracking machine.
    """
    PENDING = "PENDING"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class SystemHealth(str, Enum):
    """
    Operational health flags for system components.
    """
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    DISCONNECTED = "DISCONNECTED"