"""Critical-System Coverage Matrix — machine-readable + human-readable.

ONE source of truth enumerates every smoke concern from the task brief.
Layers in runner.py consume the machine-readable registry; the narrative
doc below is the operator/agent-facing matrix rendered from the same data.

Verbatim task-brief coverage is reproduced — no concern silently dropped.
Each entry carries: id, layer, description, failure_code, severity.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class CoverageEntry:
    """One auditable smoke concern."""

    id: str  # e.g. BOOTSTRAP-01
    layer: str  # L0 / L1 / L2 / L3 / L4 / lifecycle / dataflow / hotpath / authority / identity / determinism / budget / taxonomy
    category: str  # section in the brief
    description: str
    failure_code: str  # machine-readable code emitted on failure
    severity: str  # CRITICAL | HIGH | MEDIUM | LOW
    critical: bool = True  # if true, its absence must FAIL the gate (no false green)


COVERAGE: tuple[CoverageEntry, ...] = (
    # ── Bootstrap / Startup (L0) ────────────────────────────────────────────
    CoverageEntry(
        "BOOTSTRAP-01",
        "L0",
        "Bootstrap / Startup",
        "environment sanity (Python, platform)",
        "ENVIRONMENT_BLOCKED",
        "CRITICAL",
    ),
    CoverageEntry(
        "BOOTSTRAP-02",
        "L0",
        "Bootstrap / Startup",
        "dependency availability (critical imports)",
        "CODE_DEFECT",
        "CRITICAL",
    ),
    CoverageEntry(
        "BOOTSTRAP-03",
        "L0",
        "Bootstrap / Startup",
        "configuration loading (defaults + YAML)",
        "CONFIG_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "BOOTSTRAP-04",
        "L0",
        "Bootstrap / Startup",
        "configuration authority (masked snapshot)",
        "CONFIG_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "BOOTSTRAP-05",
        "L0",
        "Bootstrap / Startup",
        "migration readiness (status readable, no drift)",
        "DATABASE_SCHEMA_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "BOOTSTRAP-06",
        "L0",
        "Bootstrap / Startup",
        "filesystem / artifact accessibility (required files)",
        "ENVIRONMENT_BLOCKED",
        "CRITICAL",
    ),
    CoverageEntry(
        "BOOTSTRAP-07",
        "L0",
        "Bootstrap / Startup",
        "required directory structure",
        "ENVIRONMENT_BLOCKED",
        "MEDIUM",
    ),
    CoverageEntry(
        "BOOTSTRAP-08",
        "L0",
        "Bootstrap / Startup",
        "supported platform checks (py version, entrypoints compile)",
        "ENVIRONMENT_BLOCKED",
        "MEDIUM",
    ),
    CoverageEntry(
        "BOOTSTRAP-09",
        "L0",
        "Bootstrap / Startup",
        "startup doctor (21 forensics checks materialize)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "BOOTSTRAP-10",
        "L0",
        "Bootstrap / Startup",
        "startup ordering (cheap layers before runtime boot)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "BOOTSTRAP-11",
        "L0",
        "Bootstrap / Startup",
        "duplicate worker prevention (only probed, not forged)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BOOTSTRAP-12",
        "L0",
        "Bootstrap / Startup",
        "stale PID detection (launcher contract surfaces)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BOOTSTRAP-13",
        "L0",
        "Bootstrap / Startup",
        "graceful startup failure (config error does not crash gate)",
        "CONFIG_ERROR",
        "HIGH",
    ),
    # ── Market Data (L1/L2) ───────────────────────────────────────────────
    CoverageEntry(
        "MARKET-01",
        "L1",
        "Market Data",
        "MT5 adapter import surface exists",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "MARKET-02", "L1", "Market Data", "paper adapter available", "CODE_DEFECT", "CRITICAL"
    ),
    CoverageEntry(
        "MARKET-03",
        "L1",
        "Market Data",
        "gateway adapter import surface exists",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "MARKET-04",
        "L1",
        "Market Data",
        "TickData contract (frozen, UTC-aware, spread invariant)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MARKET-05",
        "L1",
        "Market Data",
        "timestamp validity (future-data rejected)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MARKET-06",
        "L1",
        "Market Data",
        "symbol validation (unknown symbol path)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "MARKET-07",
        "L1",
        "Market Data",
        "bid/ask sanity (spread positive)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MARKET-08",
        "L1",
        "Market Data",
        "spread sanity (bounded, not absurd)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "MARKET-09",
        "L1",
        "Market Data",
        "stale tick detection (age guard exists)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "MARKET-10",
        "L1",
        "Market Data",
        "impossible price detection (bounds contract)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "MARKET-11",
        "L1",
        "Market Data",
        "missing-field behavior (validation rejects)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "MARKET-12",
        "L1",
        "Market Data",
        "normalization (bars_normalize path exercised)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "MARKET-13",
        "L1",
        "Market Data",
        "adapter isolation (paper never touches MT5 IPC)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    # ── Feature Pipeline (L1) ─────────────────────────────────────────────
    CoverageEntry(
        "FEATURE-01",
        "L1",
        "Feature Pipeline",
        "50D active contract (scalp_v1=50D)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-02",
        "L1",
        "Feature Pipeline",
        "exact feature ordering (FEATURE_NAMES stable)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-03",
        "L1",
        "Feature Pipeline",
        "feature names (canonical registry)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-04",
        "L1",
        "Feature Pipeline",
        "schema ID (scalp_v3 canonical)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-05",
        "L1",
        "Feature Pipeline",
        "schema hash (235b8fcc... deterministic)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-06",
        "L1",
        "Feature Pipeline",
        "finite values (NaN/Inf rejected)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-07",
        "L1",
        "Feature Pipeline",
        "[-3,+3] bounds (clipped, validated)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-08",
        "L1",
        "Feature Pipeline",
        "NaN/Inf fallback semantics (never silent zero-fill)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-09",
        "L1",
        "Feature Pipeline",
        "deterministic feature generation (same bars -> same vector)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-10",
        "L1",
        "Feature Pipeline",
        "causal guarantees (bars[-55:] vs full-window asymmetry closed; causal MT5 history REPLACE+ALIGN)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-11",
        "L1",
        "Feature Pipeline",
        "70D candidate contract (50+10+10 geometry exact)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-12",
        "L1",
        "Feature Pipeline",
        "news block (10D semantics, neutral available)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-13",
        "L1",
        "Feature Pipeline",
        "liquidity block (10D causal, -opening, bounded)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-14",
        "L1",
        "Feature Pipeline",
        "disabled-feature semantics (neutral vectors explicit)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "FEATURE-15",
        "L1",
        "Feature Pipeline",
        "unavailable-feature blocking (InfeRejectionCode reachable)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "FEATURE-16",
        "L1",
        "Feature Pipeline",
        "dimension mismatch rejection (49D/71D blocked)",
        "FEATURE_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "FEATURE-17",
        "L1",
        "Feature Pipeline",
        "scaler x feature compatibility (scaler dim == feature dim)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    # ── Model (L1) ────────────────────────────────────────────────────────
    CoverageEntry(
        "MODEL-01",
        "L1",
        "Model",
        "artifact discovery (configured path resolvable)",
        "MISSING_ARTIFACT",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-02",
        "L1",
        "Model",
        "manifest integrity (meta.json readable, not truncated)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-03",
        "L1",
        "Model",
        "model load (ScalpNet can be constructed/forwarded)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "MODEL-04",
        "L1",
        "Model",
        "scaler load (mean/std finite, correct dim)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "MODEL-05",
        "L1",
        "Model",
        "feature dimension (checkpoint width == declared width)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "MODEL-06",
        "L1",
        "Model",
        "declared width (meta.num_features honest)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-07",
        "L1",
        "Model",
        "schema compatibility (scalp_v3, hash match)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "MODEL-08",
        "L1",
        "Model",
        "model family (2D/3D parity / TCN contract)",
        "MODEL_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "MODEL-09",
        "L1",
        "Model",
        "output dimension (logits width 3 vs 4 semantic contract)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "MODEL-10",
        "L1",
        "Model",
        "output semantics (masked_softmax contract)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-11",
        "L1",
        "Model",
        "confidence semantics (_directional_confidence contract)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-12",
        "L1",
        "Model",
        "invalid artifact rejection (corrupt/truncated blocked)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
        critical=False,
    ),
    CoverageEntry(
        "MODEL-13",
        "L1",
        "Model",
        "stale champion detection (champion identity surfaced)",
        "MODEL_CONTRACT_ERROR",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "MODEL-14",
        "L1",
        "Model",
        "serving bundle identity (model_id traced end-to-end)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-15",
        "L1",
        "Model",
        "candidate/champion separation (no auto-promotion)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "MODEL-16",
        "L1",
        "Model",
        "rollback compatibility (previous bundle recoverable path)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Signal / Policy (L2) ──────────────────────────────────────────────
    CoverageEntry(
        "POLICY-01",
        "L2",
        "Signal / Policy",
        "model -> policy handoff (probs -> proposal)",
        "CODE_DEFECT",
        "CRITICAL",
    ),
    CoverageEntry(
        "POLICY-02",
        "L2",
        "Signal / Policy",
        "regime classifier (classify_tick reachable, not mocked)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "POLICY-03",
        "L2",
        "Signal / Policy",
        "confidence gate (threshold enforced, low-conf rejected)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "POLICY-04",
        "L2",
        "Signal / Policy",
        "signal validity (proposal action enum valid)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "POLICY-05",
        "L2",
        "Signal / Policy",
        "rule matrix (engine surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "POLICY-06",
        "L2",
        "Signal / Policy",
        "TTL behavior (stale cache not served as fresh)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "POLICY-07",
        "L2",
        "Signal / Policy",
        "contradictory signal handling (opposite signals not double-dispatched)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "POLICY-08",
        "L2",
        "Signal / Policy",
        "NO_TRADE propagation (guardian/risk respect NO_TRADE)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "POLICY-09",
        "L2",
        "Signal / Policy",
        "invalid-state fail-safe (invalid proposal blocked)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "POLICY-10",
        "L2",
        "Signal / Policy",
        "research-only components cannot create order authority (AST scan)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    # ── Risk (L2) ─────────────────────────────────────────────────────────
    CoverageEntry(
        "RISK-01",
        "L2",
        "Risk",
        "position sizing (calculate_dynamic_volume reachable)",
        "CODE_DEFECT",
        "CRITICAL",
    ),
    CoverageEntry(
        "RISK-02",
        "L2",
        "Risk",
        "Kelly calculation (risk math not mocked)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RISK-03",
        "L2",
        "Risk",
        "free-margin clamp (margin guard enforced)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "RISK-04",
        "L2",
        "Risk",
        "tier caps (account-tier caps enforced)",
        "INVARIANT_VIOLATION",
        "MEDIUM",
    ),
    CoverageEntry(
        "RISK-05",
        "L2",
        "Risk",
        "HARD_MAX_LOTS (clamp 10.0, never bypassed)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "RISK-06",
        "L2",
        "Risk",
        "exposure limits (MAX_TOTAL_EXPOSURE gate)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "RISK-07",
        "L2",
        "Risk",
        "invalid proposal rejection (NO_TRADE not sized)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "RISK-08",
        "L2",
        "Risk",
        "kill switch (circuit breaker surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RISK-09",
        "L2",
        "Risk",
        "circuit breaker (SAFE_MODE feeding proven)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "RISK-10",
        "L2",
        "Risk",
        "risk state propagation (risk -> execution contract)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "RISK-11",
        "L2",
        "Risk",
        "broker truth reconciliation (INV-011)",
        "INVARIANT_VIOLATION",
        "MEDIUM",
    ),
    # ── Execution (L2) ────────────────────────────────────────────────────
    CoverageEntry(
        "EXEC-01",
        "L2",
        "Execution",
        "OrderManager authority (single execution seam)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "EXEC-02",
        "L2",
        "Execution",
        "state machine (11 PositionStates reachable)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-03",
        "L2",
        "Execution",
        "60-scenario routing (dispatch path exercised)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-04", "L2", "Execution", "re-quote lock (30s pending lock)", "CODE_DEFECT", "MEDIUM"
    ),
    CoverageEntry(
        "EXEC-05", "L2", "Execution", "ATR drift protection (1.0x clamp)", "CODE_DEFECT", "MEDIUM"
    ),
    CoverageEntry(
        "EXEC-06",
        "L2",
        "Execution",
        "protection ledger (monotonic SL guards)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "EXEC-07",
        "L2",
        "Execution",
        "execution clamps (volume clamped before dispatch)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-08",
        "L2",
        "Execution",
        "duplicate-order prevention (idempotency guard)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-09",
        "L2",
        "Execution",
        "invalid order rejection (NaN/Inf/zero blocked)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-10",
        "L2",
        "Execution",
        "SAFE_MODE transition (breaker -> safe on refusals)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "EXEC-11",
        "L2",
        "Execution",
        "broker adapter boundary (adapter parity: all verbs understood)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "EXEC-12",
        "L2",
        "Execution",
        "simulated vs real execution authority (PAPER never sends live; SHADOW never sends)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    # ── Accounting (L2) ───────────────────────────────────────────────────
    CoverageEntry(
        "ACCT-01",
        "L2",
        "Accounting",
        "trade outcome creation (outcome model reachable)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "ACCT-02",
        "L2",
        "Accounting",
        "account snapshot (audit_account_snapshots table path)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "ACCT-03",
        "L2",
        "Accounting",
        "WAL (journal_mode WAL on disposable DB)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "ACCT-04",
        "L2",
        "Accounting",
        "asynchronous persistence (AuditRepository queue path)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "ACCT-05",
        "L2",
        "Accounting",
        "immutable history (disposable round-trip proves no rewrite)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "ACCT-06",
        "L2",
        "Accounting",
        "recovery after restart (flush semantics verified)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "ACCT-07",
        "L2",
        "Accounting",
        "no hot-path synchronous DB access (INV-001 sampled)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "ACCT-08",
        "L2",
        "Accounting",
        "consistency checks (ledger count honest)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "ACCT-09",
        "L2",
        "Accounting",
        "audit evidence (audit_signals row readable)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    # ── Runtime (L3) ──────────────────────────────────────────────────────
    CoverageEntry(
        "RUNTIME-01",
        "L3",
        "Runtime",
        "LiveEngine startup (REAL construction, all services)",
        "SERVICE_CONSTRUCTION_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "RUNTIME-02",
        "L3",
        "Runtime",
        "tick pipeline (decision cycle end-to-end)",
        "RUNTIME_BOOT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "RUNTIME-03",
        "L3",
        "Runtime",
        "worker lifecycle (construction => shutdown clean)",
        "RUNTIME_BOOT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "RUNTIME-04",
        "L3",
        "Runtime",
        "background worker health (no silent death)",
        "RUNTIME_BOOT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "RUNTIME-05",
        "L3",
        "Runtime",
        "graceful shutdown (all tasks drained, audit flushed)",
        "SHUTDOWN_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "RUNTIME-06",
        "L3",
        "Runtime",
        "restart behavior (second LiveEngine after first shutdown)",
        "SHUTDOWN_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "RUNTIME-07",
        "L3",
        "Runtime",
        "cancellation propagation (async shutdown no-hang)",
        "SHUTDOWN_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "RUNTIME-08",
        "L3",
        "Runtime",
        "exception containment (checker exception never swallowed)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "RUNTIME-09",
        "L3",
        "Runtime",
        "dead-worker detection (shutdown detects leaked tasks)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RUNTIME-10",
        "L3",
        "Runtime",
        "event loop health (async loop still usable after cycle)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "RUNTIME-11",
        "L3",
        "Runtime",
        "no silent worker death (shutdown reports hung tasks)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "RUNTIME-12",
        "L3",
        "Runtime",
        "no zombie processes (process exits)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Governance (L3) ───────────────────────────────────────────────────
    CoverageEntry(
        "GOV-01",
        "L3",
        "Governance",
        "candidate state (registry reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "GOV-02",
        "L3",
        "Governance",
        "champion identity (getter surfaces, not fabricated)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "GOV-03", "L3", "Governance", "challenger identity", "CODE_DEFECT", "MEDIUM", critical=False
    ),
    CoverageEntry(
        "GOV-04",
        "L3",
        "Governance",
        "load gate (10-gate surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "GOV-05",
        "L3",
        "Governance",
        "promotion rules (READY->APPROVED->CHAMPION only)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "GOV-06",
        "L3",
        "Governance",
        "rollback rules (surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "GOV-07",
        "L3",
        "Governance",
        "audit records (evidence tables readable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "GOV-08",
        "L3",
        "Governance",
        "operator gate (LIVE requires explicit confirmation)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "GOV-09",
        "L3",
        "Governance",
        "auto-promotion prohibition (no shadow->champion)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "GOV-10",
        "L3",
        "Governance",
        "shadow zero-order-authority guarantee (L9 seam + AST boundary)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    # ── Research / Replay (L3 subject, gated) ─────────────────────────────
    CoverageEntry(
        "RESEARCH-01",
        "L3",
        "Research / Replay",
        "dataset accessibility (factory import reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-02",
        "L3",
        "Research / Replay",
        "replay startup (StreamingReplayEngine import)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-03",
        "L3",
        "Research / Replay",
        "deterministic replay (replay module reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-04",
        "L3",
        "Research / Replay",
        "live/replay feature parity (parquet builders vs live computation)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-05",
        "L3",
        "Research / Replay",
        "anti-leakage invariants (purge/embargo SSOT, horizon clamp)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "RESEARCH-06",
        "L3",
        "Research / Replay",
        "streaming replay (logical clock producer exists)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-07",
        "L3",
        "Research / Replay",
        "forward test freeze capture (freeze-contract surface)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-08",
        "L3",
        "Research / Replay",
        "OOS gate (OOS floor verification surface)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-09",
        "L3",
        "Research / Replay",
        "friction-aware backtest (fill logic exists)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "RESEARCH-10",
        "L3",
        "Research / Replay",
        "candidate evidence (marketplace/research evidence reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Shadow ────────────────────────────────────────────────────────────
    CoverageEntry(
        "SHADOW-01",
        "L3",
        "Shadow",
        "live data ingestion (shadow70 producer reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "SHADOW-02",
        "L3",
        "Shadow",
        "zero order authority (shadow path never dispatch)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SHADOW-03",
        "L3",
        "Shadow",
        "simulated execution (PAPER math only in shadow)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "SHADOW-04",
        "L3",
        "Shadow",
        "simulated=True (flag honest)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "SHADOW-05",
        "L3",
        "Shadow",
        "no order_send (enforced via tripwire + AST)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SHADOW-06",
        "L3",
        "Shadow",
        "shadow/live isolation (governor boundary)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "SHADOW-07",
        "L3",
        "Shadow",
        "shadow health (monitor import reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "SHADOW-08",
        "L3",
        "Shadow",
        "shadow model compatibility (scaler/compat check reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── News / Liquidity / Experimental ───────────────────────────────────
    CoverageEntry(
        "EXP-01",
        "L1",
        "News / Liquidity / Experimental",
        "explicit enabled/disabled state (flag surfaces)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "EXP-02",
        "L1",
        "News / Liquidity / Experimental",
        "cache semantics (governor cache not stale-served)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "EXP-03",
        "L1",
        "News / Liquidity / Experimental",
        "stale data behavior (stale fails, not silently neutral)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "EXP-04",
        "L1",
        "News / Liquidity / Experimental",
        "neutral-vector rules (neutral is explicit, not invented)",
        "FEATURE_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "EXP-05",
        "L1",
        "News / Liquidity / Experimental",
        "unavailable-feature blocking (InfeRejectionCode guards)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "EXP-06",
        "L1",
        "News / Liquidity / Experimental",
        "research-only isolation (research never holds adapter)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "EXP-07",
        "L1",
        "News / Liquidity / Experimental",
        "experimental failure must not silently corrupt live semantics (fault-isolated)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    # ── Web / Control Center (L3) ─────────────────────────────────────────
    CoverageEntry(
        "WEB-01",
        "L3",
        "Web / Control Center",
        "server startup (create_app reachable & callable)",
        "API_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "WEB-02",
        "L3",
        "Web / Control Center",
        "/health (200 or 503, correct verdict)",
        "API_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "WEB-03",
        "L3",
        "Web / Control Center",
        "readiness (health verdict semantics)",
        "API_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "WEB-04",
        "L3",
        "Web / Control Center",
        "degraded state (DEGRADED not mislabeled READY)",
        "API_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "WEB-05",
        "L3",
        "Web / Control Center",
        "SSE (stream endpoint reachable; 405 without accept)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-06",
        "L3",
        "Web / Control Center",
        "WebSocket (server surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-07",
        "L3",
        "Web / Control Center",
        "critical APIs (/api/status verifies)",
        "API_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "WEB-08",
        "L3",
        "Web / Control Center",
        "debug snapshot (debug/state reachable via wiring check)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-09",
        "L3",
        "Web / Control Center",
        "state visibility (state_version surfaced)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-10",
        "L3",
        "Web / Control Center",
        "runtime mode visibility (mode in status/health)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-11",
        "L3",
        "Web / Control Center",
        "model identity visibility (model id in status)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-12",
        "L3",
        "Web / Control Center",
        "risk/execution state visibility (exposure surface)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "WEB-13",
        "L3",
        "Web / Control Center",
        "API failure handling (404 contract honest)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Observability (L3) ────────────────────────────────────────────────
    CoverageEntry(
        "OBS-01",
        "L3",
        "Observability",
        "structured logging (get_logger reachable)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "OBS-02",
        "L3",
        "Observability",
        "severity levels (log levels well-known)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "OBS-03",
        "L3",
        "Observability",
        "correlation IDs (smoke run_id propagated)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "OBS-04",
        "L3",
        "Observability",
        "redaction (secret never in evidence/blob)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "OBS-05",
        "L3",
        "Observability",
        "startup events (boot leaves evidence)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "OBS-06",
        "L3",
        "Observability",
        "shutdown events (shutdown leaves evidence)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "OBS-07",
        "L3",
        "Observability",
        "smoke correlation ID (report carries run_id)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "OBS-08",
        "L3",
        "Observability",
        "worker lifecycle events (startup/shutdown recorded)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "OBS-09",
        "L3",
        "Observability",
        "failure diagnostics (every failure carries owner/reason/evidence)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "OBS-10",
        "L3",
        "Observability",
        "evidence persistence (--evidence writes JSON artifact)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    # ── Security / Safety (L4) ────────────────────────────────────────────
    CoverageEntry(
        "SEC-01",
        "L4",
        "Security / Safety",
        "secrets not printed (blob redaction verified)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SEC-02",
        "L4",
        "Security / Safety",
        "secrets not persisted into reports",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SEC-03",
        "L4",
        "Security / Safety",
        "LIVE cannot activate implicitly (PAPER default)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SEC-04",
        "L4",
        "Security / Safety",
        "PAPER remains default (mode gate)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "SEC-05",
        "L4",
        "Security / Safety",
        "research code cannot send orders (AST + runtime seam)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SEC-06",
        "L4",
        "Security / Safety",
        "smoke mode cannot hit real broker (paper adapter proof)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "SEC-07",
        "L4",
        "Security / Safety",
        "destructive actions require explicit gates (промоут is operator-gated)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "SEC-08",
        "L4",
        "Security / Safety",
        "test artifacts contain no credentials (clean tmp)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "SEC-09",
        "L4",
        "Security / Safety",
        "unsafe configuration rejected loudly (invalid mode/config)",
        "CONFIG_ERROR",
        "HIGH",
    ),
    # ── Release / Packaging (L3) ──────────────────────────────────────────
    CoverageEntry(
        "REL-01",
        "L3",
        "Release / Packaging",
        "package completeness (release dir readable)",
        "ENVIRONMENT_BLOCKED",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "REL-02",
        "L3",
        "Release / Packaging",
        "manifest validation (versioning block reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "REL-03",
        "L3",
        "Release / Packaging",
        "artifact hashes (checksums surface reachable)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "REL-04",
        "L3",
        "Release / Packaging",
        "SBOM presence (where expected — informational)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "REL-05",
        "L3",
        "Release / Packaging",
        "release metadata (get_version_info reachable)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "REL-06",
        "L3",
        "Release / Packaging",
        "installer verification (where applicable — informational)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "REL-07",
        "L3",
        "Release / Packaging",
        "runtime compatibility (version block coherent)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "REL-08",
        "L3",
        "Release / Packaging",
        "upgrade/rollback sanity (previous bundle path probe)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Temporal / Lifecycle (explicit) ───────────────────────────────────
    CoverageEntry(
        "LIFE-01",
        "lifecycle",
        "Lifecycle",
        "STOPPED -> STARTING (engine constructs)",
        "SERVICE_CONSTRUCTION_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "LIFE-02",
        "lifecycle",
        "Lifecycle",
        "STARTING -> READY (health READY/DEGRADED)",
        "API_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "LIFE-03",
        "lifecycle",
        "Lifecycle",
        "READY -> RUNNING (decision cycle produces result)",
        "RUNTIME_BOOT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "LIFE-04",
        "lifecycle",
        "Lifecycle",
        "RUNNING -> DEGRADED (one degraded signal honest)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "LIFE-05",
        "lifecycle",
        "Lifecycle",
        "DEGRADED -> RECOVERY (shutdown + reconstruct honest)",
        "SHUTDOWN_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "LIFE-06",
        "lifecycle",
        "Lifecycle",
        "RECOVERY -> READY (second engine boots)",
        "SERVICE_CONSTRUCTION_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "LIFE-07",
        "lifecycle",
        "Lifecycle",
        "RUNNING -> SHUTTING_DOWN (clean shutdown)",
        "SHUTDOWN_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "LIFE-08",
        "lifecycle",
        "Lifecycle",
        "SHUTTING_DOWN -> STOPPED (no leaked tasks)",
        "SHUTDOWN_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "LIFE-09",
        "lifecycle",
        "Lifecycle",
        "invalid transition rejected (shutdown-after-shutdown honest)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "LIFE-10",
        "lifecycle",
        "Lifecycle",
        "startup steady state shutdown restart repeated-startup repeated-shutdown stale-PID crash-recovery",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Data-flow (explicit) ──────────────────────────────────────────────
    CoverageEntry(
        "FLOW-01", "dataflow", "Data-flow", "tick_received proven", "CODE_DEFECT", "HIGH"
    ),
    CoverageEntry(
        "FLOW-02", "dataflow", "Data-flow", "feature_snapshot_valid proven", "CODE_DEFECT", "HIGH"
    ),
    CoverageEntry(
        "FLOW-03",
        "dataflow",
        "Data-flow",
        "inference_completed proven (or legitimate UNKNOWN when NO_TRADE)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "FLOW-04", "dataflow", "Data-flow", "policy_evaluated proven", "CODE_DEFECT", "HIGH"
    ),
    CoverageEntry(
        "FLOW-05",
        "dataflow",
        "Data-flow",
        "risk_evaluated proven (or not-applicable when NO_TRADE)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "FLOW-06",
        "dataflow",
        "Data-flow",
        "execution_decision traced (simulated, zero seam)",
        "CODE_DEFECT",
        "HIGH",
    ),
    CoverageEntry(
        "FLOW-07",
        "dataflow",
        "Data-flow",
        "accounting_event proven (disposable flush)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    CoverageEntry(
        "FLOW-08",
        "dataflow",
        "Data-flow",
        "correlation IDs complete the chain (run_id + request_id)",
        "CODE_DEFECT",
        "HIGH",
    ),
    # ── Hot-path discipline (explicit) ────────────────────────────────────
    CoverageEntry(
        "HOT-01",
        "hotpath",
        "Hot-path",
        "no sync DB on tick path (audit queue sampled, INV-001)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "HOT-02",
        "hotpath",
        "Hot-path",
        "no network on tick path (no provider on tick probe)",
        "INVARIANT_VIOLATION",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "HOT-03",
        "hotpath",
        "Hot-path",
        "no training on tick path (AST scan: experience/shadow never hold adapter)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "HOT-04",
        "hotpath",
        "Hot-path",
        "no blocking I/O on tick (decision p95 < budget)",
        "INVARIANT_VIOLATION",
        "MEDIUM",
        critical=False,
    ),
    # ── Order Authority (explicit) ────────────────────────────────────────
    CoverageEntry(
        "AUTH-01",
        "authority",
        "Order Authority",
        "research - no order authority (AST boundary scan)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "AUTH-02",
        "authority",
        "Order Authority",
        "shadow - no order authority (tripwire + AST)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "AUTH-03",
        "authority",
        "Order Authority",
        "counterfactual - no order authority (no replay dispatch)",
        "INVARIANT_VIOLATION",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "AUTH-04",
        "authority",
        "Order Authority",
        "replay - no order authority (streaming_replay seam check)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "AUTH-05",
        "authority",
        "Order Authority",
        "training - no order authority (trainer seam check)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "AUTH-06",
        "authority",
        "Order Authority",
        "only OrderManager dispatches (census proven)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    CoverageEntry(
        "AUTH-07",
        "authority",
        "Order Authority",
        "PAPER verifies simulated execution (dispatched honest)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "AUTH-08",
        "authority",
        "Order Authority",
        "SHADOW verifies zero authority (governed tripwire)",
        "INVARIANT_VIOLATION",
        "HIGH",
    ),
    CoverageEntry(
        "AUTH-09",
        "authority",
        "Order Authority",
        "LIVE never entered automatically (PAPER enforced)",
        "INVARIANT_VIOLATION",
        "CRITICAL",
    ),
    # ── Model Identity E2E (explicit) ─────────────────────────────────────
    CoverageEntry(
        "IDENT-01",
        "identity",
        "Model Identity",
        "artifact -> manifest -> schema -> scaler -> loaded model (bundle honest)",
        "MODEL_CONTRACT_ERROR",
        "CRITICAL",
    ),
    CoverageEntry(
        "IDENT-02",
        "identity",
        "Model Identity",
        "serving identity == reported identity (engine.bundle honest)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "IDENT-03",
        "identity",
        "Model Identity",
        "inference actually serves the reported model (tensor width match)",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "IDENT-04",
        "identity",
        "Model Identity",
        "stale champion/challenger identity detected (registry readable)",
        "MODEL_CONTRACT_ERROR",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "IDENT-05",
        "identity",
        "Model Identity",
        "MODEL_INPUT_DIMENSION_MISMATCH / SCALER_MISMATCH reachable & blocking",
        "MODEL_CONTRACT_ERROR",
        "HIGH",
    ),
    # ── Determinism (explicit) ────────────────────────────────────────────
    CoverageEntry(
        "DETERM-01",
        "determinism",
        "Determinism",
        "same bars -> same 50D (repeat)",
        "FEATURE_CONTRACT_ERROR",
        "HIGH",
    ),
    CoverageEntry(
        "DETERM-02",
        "determinism",
        "Determinism",
        "same vector -> same scaled (repeat)",
        "MODEL_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "DETERM-03",
        "determinism",
        "Determinism",
        "same scaled -> same logits (deterministic net)",
        "MODEL_CONTRACT_ERROR",
        "MEDIUM",
    ),
    CoverageEntry(
        "DETERM-04",
        "determinism",
        "Determinism",
        "synthetic series deterministic (no random)",
        "CODE_DEFECT",
        "MEDIUM",
    ),
    # ── Performance budgets (explicit) ────────────────────────────────────
    CoverageEntry(
        "BUDGET-01",
        "budget",
        "Performance",
        "startup duration within budget",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-02",
        "budget",
        "Performance",
        "readiness duration within budget",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-03",
        "budget",
        "Performance",
        "first successful tick latency within budget",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-04",
        "budget",
        "Performance",
        "end-to-end decision latency within budget (p95 gate)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-05",
        "budget",
        "Performance",
        "shutdown latency within budget",
        "SHUTDOWN_ERROR",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-06",
        "budget",
        "Performance",
        "worker startup latency within budget",
        "RUNTIME_BOOT_ERROR",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-07",
        "budget",
        "Performance",
        "API readiness within budget",
        "API_ERROR",
        "MEDIUM",
        critical=False,
    ),
    CoverageEntry(
        "BUDGET-08",
        "budget",
        "Performance",
        "persistence queue behavior (flush bounded)",
        "CODE_DEFECT",
        "MEDIUM",
        critical=False,
    ),
    # ── Flakiness taxonomy (explicit) ─────────────────────────────────────
    CoverageEntry(
        "TAX-01",
        "taxonomy",
        "Flakiness / Status",
        "PASS/FAIL/DEGRADED/BLOCKED/NOT_APPLICABLE/ENVIRONMENT_FAILURE/UNAVAILABLE taxonomy honored",
        "CODE_DEFECT",
        "HIGH",
    ),
)

# ── Negative / Safety matrix (injected failures) ──────────────────────────
# Each row is a controlled fault the safety tier injects and verifies fail-safe behavior.


@dataclass(frozen=True)
class NegativeCase:
    id: str
    description: str
    expected_code: str  # specific RejectionCode / failure_code or check id
    layer: str  # where the failure must surface


NEGATIVE_CASES: tuple[NegativeCase, ...] = (
    NegativeCase(
        "SAFETY-01",
        "wrong model dimension (MODEL_INPUT_DIMENSION_MISMATCH)",
        "MODEL_INPUT_DIMENSION_MISMATCH",
        "L1/L4 safety",
    ),
    NegativeCase(
        "SAFETY-02", "wrong scaler dimension (SCALER_MISMATCH)", "SCALER_MISMATCH", "L1/L4 safety"
    ),
    NegativeCase(
        "SAFETY-03",
        "wrong schema hash (SCHEMA_HASH_MISMATCH)",
        "SCHEMA_HASH_MISMATCH",
        "L1/L4 safety",
    ),
    NegativeCase(
        "SAFETY-04", "corrupted manifest (meta unreadable)", "MANIFEST_CORRUPT", "L1 safety"
    ),
    NegativeCase(
        "SAFETY-05", "missing artifact (artifact absent)", "MISSING_ARTIFACT", "L4 safety"
    ),
    NegativeCase("SAFETY-06", "invalid feature (NaN)", "NONFINITE_FEATURE", "L1 safety"),
    NegativeCase("SAFETY-07", "invalid feature (Inf)", "NONFINITE_FEATURE", "L1 safety"),
    NegativeCase(
        "SAFETY-08", "out-of-range feature (beyond [-3,3])", "OUT_OF_RANGE_FEATURE", "L1 safety"
    ),
    NegativeCase(
        "SAFETY-09",
        "unavailable liquidity block (LIQUIDITY_UNAVAILABLE)",
        "LIQUIDITY_UNAVAILABLE",
        "L1 safety",
    ),
    NegativeCase(
        "SAFETY-10", "unavailable news block (NEWS_UNAVAILABLE)", "NEWS_UNAVAILABLE", "L1 safety"
    ),
    NegativeCase(
        "SAFETY-11",
        "malformed market data (missing field / bad type)",
        "MALFORMED_TICK",
        "L1 safety",
    ),
    NegativeCase("SAFETY-12", "stale market data (too-old tick)", "STALE_TICK", "L1 safety"),
    NegativeCase(
        "SAFETY-13", "invalid risk proposal (NO_TRADE sized)", "RISK_REJECTION", "L2 safety"
    ),
    NegativeCase(
        "SAFETY-14",
        "excessive exposure (HARD_MAX_LOTS clamp must hold)",
        "HARD_MAX_LOTS_ENFORCED",
        "L2 safety",
    ),
    NegativeCase(
        "SAFETY-15",
        "broker unavailable (adapter reports error truthfully)",
        "ADAPTER_UNAVAILABLE",
        "L3 safety",
    ),
    NegativeCase(
        "SAFETY-16", "database failure (flush failure surfaces)", "DATABASE_FAILURE", "L3 safety"
    ),
    NegativeCase(
        "SAFETY-17",
        "worker exception (engine startup must surface, not swallow)",
        "WORKER_EXCEPTION",
        "L3 safety",
    ),
    NegativeCase(
        "SAFETY-18",
        "invalid runtime configuration (bad config rejected)",
        "CONFIG_ERROR",
        "L0 safety",
    ),
    NegativeCase(
        "SAFETY-19", "LIVE without confirmation (must block)", "LIVE_BLOCKED", "L4/L3 safety"
    ),
    NegativeCase(
        "SAFETY-20",
        "research component attempting execution (boundary violated)",
        "ORDER_AUTHORITY_VIOLATION",
        "authority safety",
    ),
    NegativeCase(
        "SAFETY-21",
        "stale champion identity (reported mismatch surfaces)",
        "STALE_CHAMPION",
        "identity safety",
    ),
)


def coverage_to_dict() -> dict[str, Any]:
    """Machine-readable dump for the result contract's evidence."""
    return {
        "coverage": [
            {
                "id": e.id,
                "layer": e.layer,
                "category": e.category,
                "description": e.description,
                "failure_code": e.failure_code,
                "severity": e.severity,
                "critical": e.critical,
            }
            for e in COVERAGE
        ],
        "negative_cases": [
            {
                "id": n.id,
                "description": n.description,
                "expected_code": n.expected_code,
                "layer": n.layer,
            }
            for n in NEGATIVE_CASES
        ],
    }


def critical_ids() -> set[str]:
    return {e.id for e in COVERAGE if e.critical}


def all_ids() -> set[str]:
    return {e.id for e in COVERAGE}
