#!/usr/bin/env python3
"""Dependency drift check (single source of truth contract).

The dependency architecture is:

    pyproject.toml   -> the ONLY hand-maintained dependency definition
                        (logical ranges + extras)
    requirements.lock -> GENERATED by `uv pip compile pyproject.toml`
                        (uv 0.12+); exact universal resolution with hashes.
                        DO NOT EDIT.
    requirements.txt  -> GENERATED thin compatibility artifact (top-level
                        requirements only, parsed from requirements.lock by
                        this script). DO NOT EDIT.

This script FAILS (exit 1) when either generated artifact is stale relative
to the current pyproject.toml, proving "generated" means generated.

Usage:
    python scripts/ci/check_dependency_drift.py            # check only
    python scripts/ci/check_dependency_drift.py --regen    # regenerate artifacts
                                                           # (requires uv)

Exit codes: 0 = in sync; 1 = drift detected; 2 = tooling error.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = REPO_ROOT / "pyproject.toml"
LOCK = REPO_ROOT / "requirements.lock"
REQS = REPO_ROOT / "requirements.txt"

LOCK_HEADER = (
    "# =============================================================================\n"
    "# GENERATED - DO NOT EDIT\n"
    "# Source: pyproject.toml (single source of truth, ALL extras)\n"
    "# Regenerate: python scripts/ci/check_dependency_drift.py --regen\n"
    "#             (uv pip compile pyproject.toml --all-extras --universal\n"
    "#              --generate-hashes)\n"
    "# Drift is enforced by scripts/ci/check_dependency_drift.py (CI + local).\n"
    "# =============================================================================\n"
    "\n"
)

REQS_HEADER = (
    "# =============================================================================\n"
    "# GENERATED - DO NOT EDIT\n"
    "# Source: pyproject.toml + requirements.lock\n"
    "# Regenerate: python scripts/ci/check_dependency_drift.py --regen\n"
    "# The exact resolution (with hashes) lives in requirements.lock; this file\n"
    "# only carries the top-level pins for tooling that cannot read the lock.\n"
    "# Drift is enforced by scripts/ci/check_dependency_drift.py (CI + local).\n"
    "# =============================================================================\n"
    "\n"
)


def _run_uv_compile() -> str:
    """Fresh `uv pip compile` of pyproject.toml -> lock text.

    --all-extras: the lock must cover the dev/release toolchain too (ruff,
    mypy, pytest, pyinstaller, psycopg), not just the runtime wheel — CI
    installs `.[dev,web]` and the release extra builds the EXE. A lock that
    omits them would not make those environments reproducible.
    """
    r = subprocess.run(
        [
            "uv",
            "pip",
            "compile",
            "pyproject.toml",
            "--all-extras",
            "--universal",
            "--generate-hashes",
            "--no-header",
            "--output-file",
            "-",
        ],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
        timeout=400,
    )
    if r.returncode != 0:
        sys.stderr.write(r.stdout or "")
        sys.stderr.write(r.stderr or "")
        raise SystemExit(2)
    return r.stdout


def _strip_header(text: str) -> str:
    """Drops EVERY leading blank/comment line (ours or uv's autogen header),
    leaving only the requirement body. Comparison and regeneration both use
    this, so header differences can never count as drift."""
    lines = text.splitlines()
    for i, ln in enumerate(lines):
        if ln.strip() and not ln.startswith("#"):
            return "\n".join(lines[i:]) + "\n"
    return ""


def _lock_entries(lock_text: str) -> list[tuple[str, str]]:
    """(name, version) for every pinned requirement in the lock body."""
    entries: list[tuple[str, str]] = []
    for m in re.finditer(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)", lock_text, re.M):
        entries.append((m.group(1).lower().replace("_", "-"), m.group(2)))
    return entries


def _top_level_from_lock(lock_text: str) -> list[str]:
    """Top-level requirement pins: every pinned entry the project itself
    depends on (base deps + extras), derived from uv's `# via
    nexus-scalp-engine (pyproject.toml)` provenance comments.

    Layout note: a requirement starts at column 0; hash/via continuation
    lines are indented. We scan by line state — each column-0 line opens a
    requirement record; indented `# ...` lines carrying the project name
    mark that requirement as top-level. Markers (e.g.
    `; sys_platform == 'win32'`) are preserved verbatim.
    """
    reqs: list[dict[str, object]] = []
    cur: dict[str, object] | None = None
    for ln in lock_text.splitlines():
        if ln and not ln[0].isspace():
            if cur is not None:
                reqs.append(cur)
            cur = {"head": ln, "via": False}
        elif cur is not None and "nexus-scalp-engine" in ln:
            cur["via"] = True  # type: ignore[index]
    if cur is not None:
        reqs.append(cur)

    top: list[str] = []
    for r in reqs:
        if not r["via"]:  # type: ignore[operator]
            continue
        head = str(r["head"])
        m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)\s*;?\s*(.*)", head)
        if not m:
            continue
        marker = m.group(3).rstrip("\\").strip()
        top.append(f"{m.group(1)}=={m.group(2)}" + (f" ; {marker}" if marker else ""))
    return sorted(set(top), key=str.lower)


def _regen(lock_text: str) -> None:
    LOCK.write_text(LOCK_HEADER + _strip_header(lock_text), encoding="utf-8", newline="\n")
    top = _top_level_from_lock(lock_text)
    REQS.write_text(REQS_HEADER + "\n".join(top) + "\n", encoding="utf-8", newline="\n")


def _extract_comments_block(text: str) -> str:
    return "\n".join(ln for ln in text.splitlines() if ln.startswith("#"))


def _commit_hash(name: str) -> bool:
    return False


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="check_dependency_drift")
    ap.add_argument("--regen", action="store_true", help="regenerate lock + requirements")
    args = ap.parse_args(argv)

    try:
        fresh_lock = _run_uv_compile()
    except FileNotFoundError:
        print("uv not found on PATH; cannot verify lock freshness", file=sys.stderr)
        return 2

    if args.regen:
        _regen(fresh_lock)
        print("requirements.lock + requirements.txt regenerated from pyproject.toml")
        return 0

    problems: list[str] = []

    if not LOCK.exists():
        problems.append("requirements.lock missing (the exact resolution is not committed)")
    else:
        committed = LOCK.read_text(encoding="utf-8")
        committed_body = _strip_header(committed)
        fresh_body = fresh_lock
        if committed_body.strip() != fresh_body.strip():
            problems.append(
                "requirements.lock is STALE vs pyproject.toml "
                "(uv pip compile output differs) - run: "
                "python scripts/ci/check_dependency_drift.py --regen"
            )

    if not REQS.exists():
        problems.append("requirements.txt missing (generated artifact absent)")
    else:
        reqs_text = REQS.read_text(encoding="utf-8")
        if "GENERATED - DO NOT EDIT" not in reqs_text:
            problems.append("requirements.txt lacks the GENERATED - DO NOT EDIT header")
        lock_versions: dict[str, set[str]] = {}
        for m in re.finditer(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)", fresh_lock, re.M):
            name = m.group(1).lower().replace("_", "-")
            # Universal lock: one package may appear once per marker arm
            # (e.g. numpy for <3.12 and >=3.12). A thin-artifact pin is
            # consistent when its version is one of the resolution arms.
            lock_versions.setdefault(name, set()).add(m.group(2))
        for raw_line in reqs_text.splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)", line)
            if not m:
                problems.append(f"requirements.txt has a non-pin line: {line!r}")
                continue
            name = m.group(1).lower().replace("_", "-")
            if name not in lock_versions:
                problems.append(
                    f"requirements.txt pin {name}=={m.group(2)} is not in the lock resolution"
                )
            elif m.group(2) not in lock_versions[name]:
                problems.append(
                    f"requirements.txt pin {name}=={m.group(2)} != lock arms "
                    f"{sorted(lock_versions[name])}"
                )

    if problems:
        print("DEPENDENCY DRIFT DETECTED:")
        for p in problems:
            print(f"  - {p}")
        print("Fix: python scripts/ci/check_dependency_drift.py --regen && commit the artifacts")
        return 1
    print(
        "dependency drift check: OK - "
        f"requirements.lock matches pyproject.toml resolution "
        f"({len(_lock_entries(fresh_lock))} pins), requirements.txt consistent with lock"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
