"""Canonical Feature Schema Contract — 70D single source of truth (TASK-03-70D-PARITY).

WHY THIS EXISTS
---------------
The 70D series must guarantee that ONE market snapshot produces ONE canonical
70D vector with identical semantics in dataset, replay, training, inference,
live runtime and the UI. This module is the shared, immutable specification:

    schema_id:          scalp_v3 (70D)
    dimension:          70
    family layout:      indices 0..49  = Base 50D (scalp_v1 contract, protected)
                        indices 50..59 = News 10D (canonical news_context_v1
                                        first-10 selection, order fixed below)
                        indices 60..69 = Liquidity 10D (canonical
                                        liquidity_engine.as_vector() order)

Every subsystem (dataset builder, replay, inference validator, live engine,
manifest) derives its expectations from THIS module. No downstream subsystem
may reorder or reinterpret a dimension.

CONTRACT
--------
1. ``SCHEMA_ID = "scalp_v3"`` — the canonical 70D schema id of this series.
2. ``canonical_feature_names()`` — the exact ordered 70-name tuple (index =
   position). Generated by index, never by dict iteration.
3. ``feature_schema_hash(schema_id)`` — deterministic SHA-256 over the
   canonical registry JSON (index, name, family for every dimension plus
   schema identity). Training and inference compare the SAME canonical
   serialization.
4. ``FAMILY_*`` base offsets make the layout explicit.
5. NEWS 10D selection: the repo's canonical news context is the 12-field
   ``news_context_v1`` vector (model_generation/news_bridge.py). The 70D
   contract keeps fields 0..8 plus news_state/index 10 (documented decision —
   docs/70D_DATA_CONTRACT.md); the remaining 2 (news_state,
   time_since_event_sec) stay in the 12-field context for the 60D path and
   are NOT silently dropped — they are simply outside the 70D news block by
   contract. Hashing covers the selection so any change is detected.
6. No padding, no truncation, no implicit substitution anywhere.

The hash covers index, name and family. Two schemas with the same dimension
but different ordering produce different hashes (schema identity, §5).
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from nexus_scalp.features.scalp_features import FEATURE_NAMES as BASE_50D_NAMES
from nexus_scalp.features.schema import ACTIVE_SCHEMA_ID, FEATURE_SCHEMAS


def base_50d_names() -> tuple[str, ...]:
    """The protected scalp_v1 50-name tuple (indices 0..49)."""
    return tuple(BASE_50D_NAMES)


# ---------------------------------------------------------------------------
# Canonical 70D geometry
# ---------------------------------------------------------------------------

SCHEMA_ID: str = "scalp_v3"
SCHEMA_VERSION: str = "1.0.0"
DIMENSION: int = 70

BASE_START: int = 0
BASE_END: int = 50  # exclusive -> indices 0..49
NEWS_START: int = 50
NEWS_END: int = 60  # exclusive -> indices 50..59
LIQUIDITY_START: int = 60
LIQUIDITY_END: int = 70  # exclusive -> indices 60..69

#: Canonical news 10D block: first 10 fields of news_context_v1, fixed order.
#: MUST match the first 10 entries of NewsContextSchema.fields
#: (model_generation/models.py) at import time (asserted below).
NEWS_10D_NAMES: tuple[str, ...] = (
    "active_high_impact_events",
    "xauusd_relevance",
    "usd_relevance",
    "bullish_pressure",
    "bearish_pressure",
    "conflict_score",
    "novelty",
    "freshness",
    "confidence",
    "news_state",
)

#: Canonical liquidity 10D block: liquidity_engine.LIQUIDITY_FEATURE_NAMES
#: (identical order to LiquidityFeatures.as_vector()).
LIQUIDITY_10D_NAMES: tuple[str, ...] = (
    "bsl_distance_atr",
    "ssl_distance_atr",
    "eqh_strength",
    "eql_strength",
    "htf_liquidity_score",
    "internal_liquidity_distance",
    "external_liquidity_distance",
    "liquidity_confluence",
    "liquidity_sweep_state",
    "post_sweep_displacement",
)

#: Feature families — used for family validation and hash coverage.
FAMILY_BASE: str = "base"
FAMILY_NEWS: str = "news"
FAMILY_LIQUIDITY: str = "liquidity"


def _news_schema_fields() -> tuple[str, ...]:
    """Reads the canonical news field order from the news context schema."""
    from nexus_scalp.model_generation.models import default_news_context_schema

    return tuple(default_news_context_schema().fields)


def canonical_feature_names() -> tuple[str, ...]:
    """The exact ordered 70-name tuple of the scalp_v3 contract.

    Generated by index (base 0..49, news 50..59, liquidity 60..69). Raises
    when the upstream contracts drift (a 51st base name, a news field rename,
    a liquidity rename) so the mismatch is caught at import/test time, never
    silently at inference.
    """
    base = tuple(BASE_50D_NAMES)
    news_canonical = _news_schema_fields()
    liquidity_canonical = (
        "bsl_distance_atr",
        "ssl_distance_atr",
        "eqh_strength",
        "eql_strength",
        "htf_liquidity_score",
        "internal_liquidity_distance",
        "external_liquidity_distance",
        "liquidity_confluence",
        "liquidity_sweep_state",
        "post_sweep_displacement",
    )
    if len(base) != 50:
        raise RuntimeError(f"70D contract: base 50D drifted to {len(base)} names — update BASE_END")
    if len(news_canonical) < 10:
        raise RuntimeError(f"70D contract: news context has only {len(news_canonical)} fields")
    # The 70D NEWS block is fields 0..8 + news_state (index 10) — the model's
    # decision-critical state flag — NOT a blind first-10 slice (TASK-10).
    selected = tuple(news_canonical[i] for i in (0, 1, 2, 3, 4, 5, 6, 7, 8, 10))
    if selected != NEWS_10D_NAMES:
        raise RuntimeError(
            "70D contract: news_context_v1 field order changed — NEWS_10D_NAMES must be updated "
            "to the first 10 canonical fields"
        )
    if tuple(liquidity_canonical) != LIQUIDITY_10D_NAMES:
        raise RuntimeError(
            "70D contract: liquidity feature order changed — LIQUIDITY_10D_NAMES must match "
            "liquidity engine as_vector()"
        )
    return base + NEWS_10D_NAMES + liquidity_canonical


def family_of(index: int) -> str:
    """Feature family of a 0-based index (base/news/liquidity)."""
    if BASE_START <= index < BASE_END:
        return FAMILY_BASE
    if NEWS_START <= index < NEWS_END:
        return FAMILY_NEWS
    if LIQUIDITY_START <= index < LIQUIDITY_END:
        return FAMILY_LIQUIDITY
    raise IndexError(f"index {index} outside 70D contract [0,{DIMENSION})")


def canonical_registry_json(schema_id: str = SCHEMA_ID) -> str:
    """Deterministic canonical serialization of the schema contract.

    JSON array of per-index entries {index, name, family}, plus schema
    identity. Sorted by index. This is the ONLY representation hashed.
    """
    names = canonical_feature_names()
    entries = [{"index": i, "name": names[i], "family": family_of(i)} for i in range(DIMENSION)]
    payload: dict[str, Any] = {
        "schema_id": schema_id,
        "schema_version": SCHEMA_VERSION,
        "dimension": DIMENSION,
        "base": {"start": BASE_START, "end": BASE_END, "count": BASE_END - BASE_START},
        "news": {"start": NEWS_START, "end": NEWS_END, "count": NEWS_END - NEWS_START},
        "liquidity": {
            "start": LIQUIDITY_START,
            "end": LIQUIDITY_END,
            "count": LIQUIDITY_END - LIQUIDITY_START,
        },
        "features": entries,
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)


def feature_schema_hash(schema_id: str = SCHEMA_ID, prefix: int = 16) -> str:
    """Deterministic SHA-256 of the canonical registry JSON (content hash).

    Training, replay, inference and live runtime compare this SAME value.
    ``prefix`` defaults to 16 hex chars, matching the repo's hash convention
    (sha256_json in governance/alignment.py).
    """
    digest = hashlib.sha256(canonical_registry_json(schema_id).encode("utf-8")).hexdigest()
    return digest[:prefix] if prefix else digest


def expected_schema_ids() -> tuple[str, ...]:
    """Registered schema ids that MUST exist for the 70D contract to hold."""
    return (SCHEMA_ID, "scalp_v1", "scalp_v2")


# ---------------------------------------------------------------------------
# Runtime validation
# ---------------------------------------------------------------------------


class SchemaContractError(ValueError):
    """Raised when a feature vector violates the canonical 70D contract."""


def validate_70d_vector(
    vector: list[float] | tuple[float, ...],
    *,
    schema_hash: str | None = None,
    context: str = "",
) -> list[float]:
    """Validates a 70D vector: dimension, names implied, finiteness, bounds.

    Returns the vector as a fresh list. Raises SchemaContractError with an
    explicit reason (never silently repairs).
    """
    vec = list(vector)
    if len(vec) != DIMENSION:
        raise SchemaContractError(
            f"70D contract violation{f' in {context}' if context else ''}: "
            f"expected dimension {DIMENSION}, got {len(vec)}"
        )
    for i, v in enumerate(vec):
        if not _is_finite(v):
            raise SchemaContractError(
                f"70D contract violation{f' in {context}' if context else ''}: "
                f"non-finite value at index {i} (family={family_of(i)})"
            )
        if not (-3.0 <= v <= 3.0):
            raise SchemaContractError(
                f"70D contract violation{f' in {context}' if context else ''}: "
                f"value {v} at index {i} (family={family_of(i)}) out of [-3,+3]"
            )
    if schema_hash is not None and schema_hash != feature_schema_hash():
        raise SchemaContractError(
            f"70D contract violation{f' in {context}' if context else ''}: "
            f"schema hash mismatch expected={feature_schema_hash()} actual={schema_hash}"
        )
    return vec


def _is_finite(v: float) -> bool:
    import math

    return not (math.isnan(float(v)) or math.isinf(float(v)))


def registry_has_canonical_70d() -> bool:
    """True when the schema registry actually contains scalp_v3 == 70D."""
    try:
        schema = FEATURE_SCHEMAS.resolve(SCHEMA_ID)
    except KeyError:
        return False
    return schema.dimension == DIMENSION


def assert_canonical_registry() -> None:
    """Fails loudly if the registry is missing/mismatched vs the 70D contract.

    Called at import of dependent modules and in tests. One canonical
    definition, one registry — any drift is an immediate error (INV-009).
    """
    registered = FEATURE_SCHEMAS.resolve(SCHEMA_ID)
    if registered.dimension != DIMENSION:
        raise RuntimeError(
            f"70D contract: registry scalp_v3 dimension {registered.dimension} != {DIMENSION}. "
            "The canonical schema contract and the schema registry diverged."
        )
    if ACTIVE_SCHEMA_ID != "scalp_v1":
        raise RuntimeError(
            f"70D contract: ACTIVE_SCHEMA_ID is {ACTIVE_SCHEMA_ID}; must remain scalp_v1 "
            "(70D is candidate-only, legacy live contract protected)."
        )


# Import-time guard: the news/liquidity upstream orders are verified against
# the canonical tuples (fail early in tests and in the live entry points).
canonical_feature_names()
