/**
 * i18n messages — scope: pages/Settings
 * OWNER: lane for this scope (see CONTRACT.md) (i18n wave). DATA-ONLY file: no logic, only the type import.
 *
 * Format (enforced by tests/js/frontend_i18n_parity.test.js):
 *   "<key>": { fa: "...", de: "...", es: "...", ar: "..." },
 * - Key namespace: "settings.<area>.<name>" (lowercase, dot-separated).
 * - en is identity: the English source string lives at the call site —
 *   t("dash.x.y", "English source") — do NOT add `en` entries here.
 * - Registered centrally by src/lib/i18nMessages.ts (pre-wired; never edit
 *   that file). Components never import this file; they call t() instead.
 */
import type { FeatureMessages } from "@/lib/i18n";

export const MESSAGES: FeatureMessages = {
  "settings.head.title": { fa: "تنظیمات", de: "Einstellungen", es: "Ajustes", ar: "الإعدادات" },
  "settings.head.crumb": { fa: "کنسول ALT", de: "ALT-Konsole", es: "consola ALT", ar: "وحدة ALT" },
  "settings.head.desc_suffix": { fa: "فقط ترجیحات بصری", de: "nur visuelle Einstellungen", es: "solo preferencias visuales", ar: "تفضيلات بصرية فقط" },
  "settings.note.backend_authority": { fa: "⚠ هیچ‌چیز در این صفحه وضعیت NSE را نمی‌خواند یا تغییر نمی‌دهد. حالت موتور، دروازه‌های ریسک، پوزیشن‌ها و اسنپ‌شات‌ها همچنان تحت اختیار بک‌اند هستند؛ بخش «درباره» فقط اسنپ‌شاتی را که پوسته از قبل دریافت کرده بازتاب می‌دهد.", de: "⚠ Diese Seite liest oder ändert keinen NSE-Zustand. Ausführungsmodus, Risikofreigaben, Positionen und Snapshots bleiben backend-seitig maßgeblich; der Abschnitt Über spiegelt nur den vom Shell bereits abgefragten Snapshot.", es: "⚠ Nada en esta página lee ni cambia el estado de NSE. El modo del motor, los límites de riesgo, las posiciones y las instantáneas siguen siendo responsabilidad del backend; el bloque Acerca solo refleja la instantánea que el shell ya consultó.", ar: "⚠ لا شيء في هذه الصفحة يقرأ أو يغيّر حالة NSE. وضع المحرك وبوابات المخاطر والمراكز واللقطات تبقى تحت سيادة الخادم؛ يعرض قسم «حول» اللقطة التي طلبها الهيكل مسبقًا فقط." },
  "settings.panel.appearance": { fa: "ظاهر", de: "Darstellung", es: "Apariencia", ar: "المظهر" },
  "settings.density.sub": { fa: "مشترک با کلید تراکم در نوار کناری —", de: "Gemeinsam mit dem DICHTE-Schalter der Seitenleiste —", es: "Compartido con el interruptor de DENSIDAD de la barra lateral —", ar: "مشترك مع مفتاح الكثافة في الشريط الجانبي —" },
  "settings.density.badge_dense": { fa: "1 (متراکم)", de: "1 (dicht)", es: "1 (denso)", ar: "1 (كثيف)" },
  "settings.density.badge_comfortable": { fa: "0 (راحت)", de: "0 (komfortabel)", es: "0 (cómodo)", ar: "0 (مريح)" },
  "settings.density.opt_comfortable": { fa: "راحت", de: "Komfortabel", es: "Cómodo", ar: "مريح" },
  "settings.density.opt_dense": { fa: "متراکم", de: "Dicht", es: "Denso", ar: "كثيف" },
  "settings.sidebar.sub": { fa: "همان عملکرد Alt+B و دکمهٔ تغییر نوار کناری —", de: "Dieselbe Aktion wie Alt+B und der Seitenleisten-Schalter —", es: "La misma acción que Alt+B y el botón de la barra lateral —", ar: "نفس إجراء Alt+B وزر تبديل الشريط الجانبي —" },
  "settings.sidebar.badge_collapsed": { fa: "1 (جمع‌شده)", de: "1 (eingeklappt)", es: "1 (contraída)", ar: "1 (مطوي)" },
  "settings.sidebar.badge_expanded": { fa: "0 (باز)", de: "0 (ausgeklappt)", es: "0 (expandida)", ar: "0 (موسّع)" },
  "settings.sidebar.opt_expanded": { fa: "باز", de: "Ausgeklappt", es: "Expandida", ar: "موسّع" },
  "settings.sidebar.opt_collapsed": { fa: "جمع‌شده", de: "Eingeklappt", es: "Contraída", ar: "مطوي" },
  "settings.toast.lab": { fa: "ادغام اعلان‌ها", de: "Toast-Deduplizierung", es: "Deduplicación de avisos", ar: "توحيد الإشعارات" },
  "settings.toast.sub": { fa: "اعلان‌های یکسان در بازهٔ ۴ ثانیه‌ای یک بار ادغام می‌شوند (uiStore toastGuard — هم‌تراز با NX.toast قدیمی). رفتار نمایشی، همیشه فعال، تنظیمی از بک‌اند نیست.", de: "Identische Toasts innerhalb von 4 Sekunden werden einmal zusammengeführt (uiStore toastGuard — Parität mit dem alten NX.toast). Darstellungsverhalten, immer aktiv, keine Backend-Einstellung.", es: "Los avisos idénticos dentro de una ventana de 4 segundos se fusionan una vez (uiStore toastGuard — paridad con el NX.toast antiguo). Comportamiento de visualización, siempre activo, no es un ajuste del backend.", ar: "تُدمج الإشعارات المتطابقة داخل نافذة 4 ثوانٍ مرة واحدة (uiStore toastGuard — مواءمة مع NX.toast القديم). سلوك العرض، مفعّل دائمًا، وليس إعدادًا من الخادم." },
  "settings.toast.badge": { fa: "اطلاعات", de: "INFO", es: "INFO", ar: "معلومات" },
  "settings.lang.sub_a": { fa: "همان سطح با LangRow در نوار کناری؛ ذخیره در", de: "Eine Fläche gemeinsam mit der LangRow der Seitenleiste; gespeichert unter", es: "Una superficie compartida con la LangRow de la barra lateral; se guarda en", ar: "واجهة مشتركة مع LangRow في الشريط الجانبي؛ تُحفظ في" },
  "settings.lang.sub_b": { fa: "(مشترک با داشبورد قدیمی). انتخاب راست‌به‌چپ (فارسی / العربية)", de: "(gemeinsam mit dem alten Dashboard). Die Auswahl von RTL (فارسی / العربية) kippt", es: "(compartida con el panel antiguo). Seleccionar RTL (فارسی / العربية) invierte", ar: "(مشتركة مع اللوحة القديمة). اختيار RTL (فارسی / العربية) يقلب" },
  "settings.lang.sub_c": { fa: "را بلافاصله از طریق store تغییر می‌دهد.", de: "sofort über den Store.", es: "de inmediato mediante el almacén.", ar: "فورًا عبر المخزن." },
  "settings.direction.lab": { fa: "جهت", de: "Richtung", es: "Dirección", ar: "الاتجاه" },
  "settings.direction.note": { fa: "(اعمال‌شده توسط i18nStore، هم‌سان با applyDirection قدیمی)", de: "(angewendet von i18nStore, gespiegelt vom alten applyDirection)", es: "(aplicado por i18nStore, reflejado desde el applyDirection antiguo)", ar: "(يطبقه i18nStore منسوخًا من applyDirection القديم)" },
  "settings.panel.shortcuts": { fa: "میان‌برهای صفحه‌کلید", de: "Tastenkürzel", es: "Atajos de teclado", ar: "اختصارات لوحة المفاتيح" },
  "settings.shortcut.palette.action": { fa: "باز/بستن پالت دستور", de: "Befehlspalette öffnen/schließen", es: "Abrir/cerrar la paleta de comandos", ar: "فتح/إغلاق لوحة الأوامر" },
  "settings.shortcut.palette.note": { fa: "Cmd+K در macOS — متصل به CommandPalette.tsx؛ فرمان‌های پالت فقط ناوبری یا اجرای دوباره پرس‌وجوهای موجود هستند.", de: "Cmd+K unter macOS — gebunden in CommandPalette.tsx; Palette-Befehle navigieren nur oder führen bestehende Abfragen erneut aus.", es: "Cmd+K en macOS — definido en CommandPalette.tsx; los comandos de la paleta solo navegan o repiten consultas existentes.", ar: "Cmd+K على macOS — مرتبط في CommandPalette.tsx؛ أوامر اللوحة تنقّل فقط أو تعيد تشغيل الاستعلامات الموجودة." },
  "settings.shortcut.alt.action": { fa: "پرش به صفحهٔ نوار کناری بر اساس موقعیت", de: "Zur Seitenleisten-Seite nach Position springen", es: "Saltar a la página de la barra lateral por posición", ar: "الانتقال إلى صفحة الشريط الجانبي حسب الموضع" },
  "settings.shortcut.alt.note": { fa: "پویا: یک جایگاه برای هر مورد ناوبری — پس از افزودن /settings به ۱–۸ تبدیل می‌شود. هنگام تایپ غیرفعال است.", de: "Dynamisch: ein Slot pro NAV-Eintrag — wird 1–8, sobald der NAV-Eintrag /settings landet. Beim Tippen deaktiviert.", es: "Dinámico: una ranura por elemento de navegación — pasa a 1–8 cuando entre la entrada /settings. Desactivado al escribir.", ar: "ديناميكي: خانة لكل عنصر تنقل — تصبح 1–8 عند إضافة عنصر /settings. معطّل أثناء الكتابة." },
  "settings.shortcut.sidebar.action": { fa: "جمع/باز کردن نوار کناری", de: "Seitenleiste ein-/ausklappen", es: "Contraer/expandir la barra lateral", ar: "طي/توسيع الشريط الجانبي" },
  "settings.shortcut.sidebar.note": { fa: "همان عملکرد کلید پای نوار کناری و کلید «نوار کناری» در پایین.", de: "Dieselbe Aktion wie der Schalter im Seitenleisten-Fuß und der Umschalter Seitenleiste unten.", es: "La misma acción que el interruptor del pie de la barra lateral y el interruptor Barra lateral de abajo.", ar: "نفس إجراء مفتاح تذييل الشريط الجانبي ومفتاح «الشريط الجانبي» أدناه." },
  "settings.shortcut.refresh.action": { fa: "تازه‌سازی اسنپ‌شات موتور", de: "Engine-Snapshot aktualisieren", es: "Actualizar la instantánea del motor", ar: "تحديث لقطة المحرك" },
  "settings.shortcut.refresh.note": { fa: "R ساده (بدون کلید مکمل)، هنگام تایپ نادیده گرفته می‌شود و فقط پس از بارگذاری نخستین اسنپ‌شات عمل می‌کند.", de: "Plain R (ohne Modifikator), beim Tippen ignoriert und wirkt erst, nachdem ein erster Snapshot geladen wurde.", es: "R simple (sin modificador), se ignora al escribir y solo actúa tras cargar la primera instantánea.", ar: "حرف R فقط (بدون مفتاح إضافي)، يُتجاهل أثناء الكتابة ولا يعمل إلا بعد تحميل أول لقطة." },
  "settings.shortcut.move.action": { fa: "جابه‌جایی/اجرا در پالت", de: "In der Palette bewegen/ausführen", es: "Mover/ejecutar dentro de la paleta", ar: "التنقل/التنفيذ داخل اللوحة" },
  "settings.shortcut.move.note": { fa: "فقط هنگامی که ورودی پالت فعال باشد.", de: "Nur solange die Palette-Eingabe fokussiert ist.", es: "Solo mientras el campo de la paleta tiene el foco.", ar: "فقط أثناء تركيز حقل اللوحة." },
  "settings.shortcut.esc.action": { fa: "بستن پالت/پنجره", de: "Palette/Dialog schließen", es: "Cerrar paleta/diálogo", ar: "إغلاق اللوحة/الحوار" },
  "settings.shortcut.esc.note": { fa: "فقط انصراف — Esc هرگز عملیاتی را تأیید نمی‌کند.", de: "Nur abbrechen — Esc bestätigt nie eine Aktion.", es: "Solo cancelar — Esc nunca confirma una acción.", ar: "إلغاء فقط — لا يؤكد Esc إجراءً أبدًا." },
  "settings.shortcuts.footnote": { fa: "بررسی‌شده با AppShell.tsx (Alt+digit / Alt+B / R) و CommandPalette.tsx (Ctrl/Cmd+K، ↑↓/Enter/Esc) — نه با چیپ نوار کناری که واقعیت را کوتاه‌شده نشان می‌دهد:", de: "Geprüft gegen AppShell.tsx (Alt+Ziffer / Alt+B / R) und CommandPalette.tsx (Ctrl/Cmd+K, ↑↓/Enter/Esc) — nicht gegen den Seitenleisten-Chip, der die Wahrheit verkürzt zu:", es: "Verificado contra AppShell.tsx (Alt+dígito / Alt+B / R) y CommandPalette.tsx (Ctrl/Cmd+K, ↑↓/Enter/Esc) — no contra el chip de la barra lateral, que abrevia la verdad a:", ar: "مُتحقَّق منه مقابل AppShell.tsx (Alt+رقم / Alt+B / R) وCommandPalette.tsx (Ctrl/Cmd+K، ↑↓/Enter/Esc) — وليس مقابل شريحة الشريط الجانبي التي تختصر الحقيقة إلى:" },
  "settings.panel.theme": { fa: "توکن‌های پوسته", de: "Design-Tokens", es: "Tokens de tema", ar: "رموز المظهر" },
  "settings.theme.vars": { fa: "{n} متغیر · :root", de: "{n} Variablen · :root", es: "{n} variables · :root", ar: "{n} متغير · :root" },
  "settings.theme.sub_a": { fa: "نام‌های اعلام‌شده در", de: "Namen wie deklariert in", es: "Nombres declarados en", ar: "الأسماء المُعلَنة في" },
  "settings.theme.sub_b": { fa: "شیوه‌نامه مالک مقادیر است.", de: "das Stylesheet besitzt die Werte.", es: "la hoja de estilos es la dueña de los valores.", ar: "أوراق الأنماط هي مالكة القيم." },
  "settings.theme.sub_c": { fa: "--row-pad، --card-pad، --panel-gap را بازنویسی می‌کند؛ رنگ معنایی می‌ماند (وضعیت بک‌اند)، هرگز انتخاب کاربر نیست.", de: "--row-pad, --card-pad, --panel-gap überschreiben; die Farbe bleibt semantisch (Backend-Zustand), nie benutzergewählt.", es: "anula --row-pad, --card-pad y --panel-gap; el color sigue siendo semántico (estado del backend), nunca lo elige el usuario.", ar: "تتجاوز --row-pad و--card-pad و--panel-gap؛ يبقى اللون دلاليًا (حالة الخادم) وليس اختيار المستخدم." },
  "settings.panel.about": { fa: "درباره", de: "Über", es: "Acerca de", ar: "حول" },
  "settings.about.console_build": { fa: "نسخهٔ کنسول", de: "Konsolen-Build", es: "compilación de la consola", ar: "إصدار الوحدة" },
  "settings.about.state_version": { fa: "اسنپ‌شات · state_version", de: "Snapshot · state_version", es: "instantánea · state_version", ar: "لقطة · state_version" },
  "settings.about.no_snapshot": { fa: "— (هنوز اسنپ‌شاتی نیست)", de: "— (noch kein Snapshot)", es: "— (aún sin instantánea)", ar: "— (لا لقطة بعد)" },
  "settings.about.versioning_block": { fa: "بلوک نسخه‌بندی بک‌اند", de: "Backend-Versionierungsblock", es: "bloque de versionado del backend", ar: "كتلة إصدارات الخادم" },
  "settings.about.no_versioning": { fa: "— (توسط /api/status ارائه نشده)", de: "— (von /api/status nicht bereitgestellt)", es: "— (no lo proporciona /api/status)", ar: "— (لا يوفره /api/status)" },
  "settings.about.feed_label": { fa: "جریان بلادرنگ", de: "Echtzeit-Stream", es: "flujo en tiempo real", ar: "تدفق لحظي" },
  "settings.about.feed_value": { fa: "SSE /api/ticks/stream (state_version از فریم‌های خارج از ترتیب جلوگیری می‌کند)", de: "SSE /api/ticks/stream (state_version schützt vor Frames außerhalb der Reihenfolge)", es: "SSE /api/ticks/stream (state_version protege contra tramas fuera de orden)", ar: "SSE /api/ticks/stream (يحمي state_version الإطارات خارج الترتيب)" },
  "settings.about.readonly": { fa: "آینه فقط‌خواندنی اسنپ‌شاتی که پوسته از قبل دریافت کرده — این صفحه هیچ درخواستی نمی‌فرستد و هیچ پرس‌وجویی را باطل نمی‌کند.", de: "Schreibgeschützter Spiegel des vom Shell bereits abgefragten Snapshots — diese Seite sendet keine Abfragen und invalidiert keine Queries.", es: "Espejo de solo lectura de la instantánea ya consultada por el shell — esta página no emite peticiones ni invalida consultas.", ar: "مرآة للقراءة فقط للقطة التي طلبها الهيكل مسبقًا — هذه الصفحة لا ترسل أي طلبات ولا تُبطل أي استعلام." },
  "settings.panel.local": { fa: "داده‌های محلی", de: "Lokale Daten", es: "Datos locales", ar: "بيانات محلية" },
  "settings.local.stored_lab": { fa: "ترجیحات UI ذخیره‌شده", de: "Gespeicherte UI-Einstellungen", es: "Preferencias de UI guardadas", ar: "تفضيلات الواجهة المحفوظة" },
  "settings.local.sub": { fa: "مقادیر بصری؛ توکن WEB-AUTH در sessionStorage است و خارج از محدوده.", de: "nur visuelle Werte; das WEB-AUTH-Token liegt in sessionStorage und ist nicht betroffen.", es: "solo valores visuales; el token WEB-AUTH está en sessionStorage y queda fuera de alcance.", ar: "قيم بصرية فقط؛ رمز WEB-AUTH في sessionStorage وخارج النطاق." },
  "settings.local.clear_btn": { fa: "پاک‌سازی ترجیحات UI محلی…", de: "Lokale UI-Einstellungen löschen…", es: "Borrar preferencias locales de UI…", ar: "مسح تفضيلات الواجهة المحلية…" },
  "settings.local.cleared": { fa: "✓ {n} کلید localStorage حذف شد. تراکم و نوار کناری در این نشست به پیش‌فرض بازگشتند؛ انتخاب زبان تا بارگذاری مجدد روی صفحه می‌ماند و سپس به تشخیص مرورگر بازمی‌گردد.", de: "✓ {n} localStorage-Schlüssel entfernt. Dichte und Seitenleiste sind für diese Sitzung zurück auf den Standard; die Sprachwahl bleibt bis zum Neuladen sichtbar und fällt danach auf die Browsererkennung zurück.", es: "✓ Se eliminaron {n} claves de localStorage. La densidad y la barra lateral vuelven a los valores predeterminados de esta sesión; la selección de idioma permanece visible hasta recargar y luego vuelve a la detección del navegador.", ar: "✓ تم حذف {n} مفتاح من localStorage. عادت الكثافة والشريط الجانبي إلى الافتراضي في هذه الجلسة؛ يبقى اختيار اللغة ظاهرًا حتى إعادة التحميل ثم يعود إلى كشف المتصفح." },
  "settings.local.cleared_toast": { fa: "ترجیحات UI محلی پاک شد ({n} کلید)", de: "Lokale UI-Einstellungen gelöscht ({n} Schlüssel)", es: "Preferencias locales de UI borradas ({n} claves)", ar: "مُسحت تفضيلات الواجهة المحلية ({n} مفتاح)" },
  "settings.clear.title": { fa: "پاک‌سازی ترجیحات UI محلی", de: "Lokale UI-Einstellungen löschen", es: "Borrar preferencias locales de UI", ar: "مسح تفضيلات الواجهة المحلية" },
  "settings.clear.confirm": { fa: "پاک‌سازی", de: "Einstellungen löschen", es: "Borrar ajustes", ar: "مسح" },
  "settings.clear.note_a": { fa: "فقط این کلیدهای localStorage را در این مرورگر حذف می‌کند: هر", de: "Entfernt NUR diese localStorage-Schlüssel in diesem Browser: jede", es: "Elimina SOLO estas claves de localStorage en este navegador: cada", ar: "يحذف فقط مفاتيح localStorage التالية في هذا المتصفح: كل" },
  "settings.clear.note_b": { fa: "و", de: "Einstellung und", es: "preferencia y", ar: "و" },
  "settings.clear.note_c": { fa: "وضعیت بک‌اند، تنظیمات موتور و توکن نشست احراز هویت دست‌نخورده می‌مانند. این کنسول به کار خود ادامه می‌دهد — فقط ذخیرهٔ مقادیر متوقف می‌شود.", de: "Backend-Zustand, Engine-Einstellungen und das Sitzungs-Auth-Token bleiben unberührt. Die Konsole funktioniert weiter — die Werte werden nur nicht mehr gespeichert.", es: "El estado del backend, la configuración del motor y el token de autenticación de la sesión no se tocan. La consola sigue funcionando; solo dejan de persistirse los valores.", ar: "تبقى حالة الخادم وإعدادات المحرك ورمز مصادقة الجلسة دون تغيير. تواصل الوحدة عملها — تتوقف القيم فقط عن الحفظ." },
  "settings.clear.no_keys": { fa: "هم‌اکنون هیچ کلید nse.altui.* / nexus.ui.lang ذخیره نشده است.", de: "Zurzeit sind keine nse.altui.* / nexus.ui.lang-Schlüssel gespeichert.", es: "Actualmente no hay claves nse.altui.* / nexus.ui.lang guardadas.", ar: "لا توجد حاليًا مفاتيح nse.altui.* / nexus.ui.lang محفوظة." },
};
