"""Update-engine package (extracted from release/updater.py).

Responsibility map:
    constants      status/state vocabulary + detection regexes
    discovery      release discovery, digests, manifests, plan builder
    downloader     resume-safe staged download
    backup_migrate backup/migration/install machinery
    health         post-update health checks
    rollback_state rollback engine + persisted update state/history
    pidfile_lock   single-instance lock, pid liveness, install-mode detection
    safety_guards  LIVE-engine guard + quiesce protocol
    orchestrator   full update flow (check/dry_run/download/verify/install/run/rollback)
"""

from __future__ import annotations

from nexus_scalp.release.update_engine.backup_migrate import (
    ApplicationInstaller,
    BackupEngine,
    BackupPlanner,
    ConfigMigrator,
    DatabaseMigrator,
    MigrationError,
)
from nexus_scalp.release.update_engine.constants import (
    _CHECKSUM_ASSET_RE,
    _MUTATING_STATES,
    _REVOKED_MARKER_RE,
    _SOURCE_ASSET_RE,
    DEFAULT_CHANNEL,
    INSTALL_MODE_DEVELOPER,
    INSTALL_MODE_EXE,
    INSTALL_MODE_INNO,
    INSTALL_MODE_PORTABLE,
    INSTALL_MODE_SOURCE,
    INSTALL_MODE_UNKNOWN,
    STAGE_DOWNLOAD,
    STAGE_INSTALL,
    STAGE_STARTUP,
    STAGE_VERIFY,
    STATE_AVAILABLE,
    STATE_BACKING_UP,
    STATE_CHECKING,
    STATE_COMPLETED,
    STATE_DOWNLOADING,
    STATE_FAILED,
    STATE_FAILED_SAFE,
    STATE_HEALTH_CHECK,
    STATE_IDLE,
    STATE_INSTALLING,
    STATE_MIGRATING,
    STATE_QUIESCING,
    STATE_READY,
    STATE_ROLLBACK_REQUIRED,
    STATE_ROLLED_BACK,
    STATE_ROLLING_BACK,
    STATE_VERIFYING,
    STATE_VERIFYING_INSTALL,
    STATUS_DIRECT_UPDATE_UNSUPPORTED,
    STATUS_GITHUB_UNAVAILABLE,
    STATUS_INCOMPATIBLE,
    STATUS_NETWORK_ERROR,
    STATUS_NETWORK_UNAVAILABLE,
    STATUS_NO_UPDATE,
    STATUS_RELEASE_NOT_FOUND,
    STATUS_SECURITY_BLOCKED,
    STATUS_UNKNOWN,
    STATUS_UNSUPPORTED,
    STATUS_UPDATE_AVAILABLE,
    STATUS_UPDATE_REJECTED,
    SUPPORTED_CHANNELS,
    SUPPORTED_PLATFORM,
)
from nexus_scalp.release.update_engine.discovery import (
    CompatibilityGate,
    DigestResolver,
    GitHubDiscoveryError,
    HashVerifier,
    ManifestVerifier,
    UpdateDiscovery,
    UpdatePlanBuilder,
    _machine_arch,
    compare_versions,
)
from nexus_scalp.release.update_engine.downloader import (
    SafeDownloader,
)
from nexus_scalp.release.update_engine.health import (
    PostUpdateHealth,
)
from nexus_scalp.release.update_engine.orchestrator import (
    UpdateOrchestrator,
    upd_default_user_root,
)
from nexus_scalp.release.update_engine.pidfile_lock import (
    InstallModeDetector,
    SettingsGuard,
    UpdateLock,
    _current_app_root,
    _pid_alive,
)
from nexus_scalp.release.update_engine.rollback_state import (
    ReleaseLocalState,
    RollbackEngine,
    UpdateHistory,
    UpdateState,
)
from nexus_scalp.release.update_engine.safety_guards import (
    EngineGuard,
    QuiesceProtocol,
    UpdateBlockedError,
)

__all__ = [
    "DEFAULT_CHANNEL",
    "INSTALL_MODE_DEVELOPER",
    "INSTALL_MODE_EXE",
    "INSTALL_MODE_INNO",
    "INSTALL_MODE_PORTABLE",
    "INSTALL_MODE_SOURCE",
    "INSTALL_MODE_UNKNOWN",
    "STAGE_DOWNLOAD",
    "STAGE_INSTALL",
    "STAGE_STARTUP",
    "STAGE_VERIFY",
    "STATE_AVAILABLE",
    "STATE_BACKING_UP",
    "STATE_CHECKING",
    "STATE_COMPLETED",
    "STATE_DOWNLOADING",
    "STATE_FAILED",
    "STATE_FAILED_SAFE",
    "STATE_HEALTH_CHECK",
    "STATE_IDLE",
    "STATE_INSTALLING",
    "STATE_MIGRATING",
    "STATE_QUIESCING",
    "STATE_READY",
    "STATE_ROLLBACK_REQUIRED",
    "STATE_ROLLED_BACK",
    "STATE_ROLLING_BACK",
    "STATE_VERIFYING",
    "STATE_VERIFYING_INSTALL",
    "STATUS_DIRECT_UPDATE_UNSUPPORTED",
    "STATUS_GITHUB_UNAVAILABLE",
    "STATUS_INCOMPATIBLE",
    "STATUS_NETWORK_ERROR",
    "STATUS_NETWORK_UNAVAILABLE",
    "STATUS_NO_UPDATE",
    "STATUS_RELEASE_NOT_FOUND",
    "STATUS_SECURITY_BLOCKED",
    "STATUS_UNKNOWN",
    "STATUS_UNSUPPORTED",
    "STATUS_UPDATE_AVAILABLE",
    "STATUS_UPDATE_REJECTED",
    "SUPPORTED_CHANNELS",
    "SUPPORTED_PLATFORM",
    "_CHECKSUM_ASSET_RE",
    "_MUTATING_STATES",
    "_REVOKED_MARKER_RE",
    "_SOURCE_ASSET_RE",
    "ApplicationInstaller",
    "BackupEngine",
    "BackupPlanner",
    "CompatibilityGate",
    "ConfigMigrator",
    "DatabaseMigrator",
    "DigestResolver",
    "EngineGuard",
    "GitHubDiscoveryError",
    "HashVerifier",
    "InstallModeDetector",
    "ManifestVerifier",
    "MigrationError",
    "PostUpdateHealth",
    "QuiesceProtocol",
    "ReleaseLocalState",
    "RollbackEngine",
    "SafeDownloader",
    "SettingsGuard",
    "UpdateBlockedError",
    "UpdateDiscovery",
    "UpdateHistory",
    "UpdateLock",
    "UpdateOrchestrator",
    "UpdatePlanBuilder",
    "UpdateState",
    "_current_app_root",
    "_machine_arch",
    "_pid_alive",
    "compare_versions",
    "upd_default_user_root",
]
