import sqlite3
conn = sqlite3.connect('file:artifacts/audit.db?mode=ro', uri=True)
c = conn.cursor()
print("=== audit_experiences ===")
for r in c.execute("SELECT is_executed, is_closed, COUNT(*) FROM audit_experiences GROUP BY 1,2"): print(r)
print("=== outcomes exit reasons ===")
for r in c.execute("SELECT exit_reason, COUNT(*), ROUND(SUM(realized_r_multiple),2) FROM audit_experience_outcomes GROUP BY 1 ORDER BY 2 DESC LIMIT 12"): print(r)
print("=== outcome lifecycle ===")
for r in c.execute("SELECT COUNT(*), SUM(realized_r_multiple IS NOT NULL AND realized_r_multiple != 0) FROM audit_experience_outcomes"): print(r)
print("=== experience_model_registry ===")
for r in c.execute("SELECT model_id, model_version, lifecycle_status, status FROM experience_model_registry LIMIT 15"): print(r)
print("=== date range ===")
print(c.execute("SELECT MIN(decision_timestamp), MAX(decision_timestamp) FROM audit_experiences").fetchone())
conn.close()
