"""APP-required column contract for the audit baseline skeletons (PERF-DEADLETTER).

WHY THIS EXISTS
===============
Production incident (container v9.0.11, 2026-09-09..10): the startup migration
gate ran BEFORE the engine on a fresh database and
``DatabaseMigrationEngine._create_baseline_tables`` built every manifest table
as an ``id INTEGER PRIMARY KEY`` skeleton. ``AuditRepository``'s bootstrap is
``CREATE TABLE IF NOT EXISTS`` — a no-op on those skeletons — and its
``_add_column_if_missing`` loops only heal EXTRAS, never core columns. Every
producer INSERT then failed with ``table X has no column named Y`` and the
audit worker batch-salvage dead-lettered every row: ~553,000 rows in ~15h
(~10/s), audit.db 1,006 MB.

CONTRACT
========
``APP_REQUIRED_COLUMNS`` maps the audit-domain tables to the columns their
real production INSERT statements use. ``engine._create_baseline_tables``
heals skeletons with it (PRAGMA-gated, additive-only, fail-loud); the
regression test ``tests/unit/test_perf_deadletter_skeleton_repro.py`` pins
both directions:

* skeleton + heal must carry every (table, column) pair listed here, and
* the pairs here must match the columns the app bootstrap/INSERTs use
  (the dead-letter error corpus is the forensic source of truth).

Import-safety: this module must stay importable WITHOUT the app dependency
stack (the migration-safety CI lane installs only structlog) — stdlib only,
no module-level app imports. ``engine.py`` imports it lazily inside the
baseline builder for the same reason.

The DDL strings below are deliberately the MINIMAL ADDITIVE form: a bare
``TEXT``/``REAL``/``INTEGER`` type with a DEFAULT where the producer relies
on one. ``NOT NULL`` is intentionally dropped when healing a skeleton
(``ALTER TABLE ADD COLUMN`` cannot add NOT NULL without a default and legacy
skeleton rows may exist); the authoritative NOT NULL contract stays in the
application DDL (``AuditRepository._create_sqlite_tables``).
"""

from __future__ import annotations

#: table -> tuple of (column, DDL-after-name) entries.
#: Additive-only, idempotent; applied with a PRAGMA table_info pre-check.
APP_REQUIRED_COLUMNS: dict[str, tuple[tuple[str, str], ...]] = {
    "audit_signals": (
        ("request_id", "TEXT"),
        ("symbol", "TEXT"),
        ("action", "TEXT"),
        ("confidence", "REAL"),
        ("proposed_entry", "REAL"),
        ("stop_loss", "REAL"),
        ("take_profit", "REAL"),
        ("regime", "TEXT"),
        ("generated_at", "TEXT"),
        ("payload", "TEXT"),
        ("execution_mode", "TEXT"),
        ("reason_code", "TEXT"),
        ("decision_stage", "TEXT"),
        ("blocked_by", "TEXT"),
        ("htf_score", "REAL"),
        ("smc_score", "REAL"),
        ("confidence_before_filters", "REAL"),
        ("confidence_after_filters", "REAL"),
        ("preferred_direction", "TEXT"),
        ("raw_prob_buy", "REAL"),
        ("raw_prob_sell", "REAL"),
        ("raw_prob_no_trade", "REAL"),
        ("raw_prob_wait", "REAL"),
        ("confidence_source", "TEXT"),
        ("spread_usd", "REAL"),
        ("signal_dedup_key", "TEXT"),
        ("account_source", "TEXT DEFAULT ''"),
    ),
    "audit_guard_telemetry": (
        ("window_start", "TEXT"),
        ("symbol", "TEXT"),
        ("reason_code", "TEXT"),
        ("count", "INTEGER DEFAULT 0"),
    ),
    "audit_orders": (
        ("ticket", "INTEGER"),
        ("order_id", "TEXT"),
        ("symbol", "TEXT"),
        ("action", "TEXT"),
        ("price", "REAL"),
        ("stop_loss", "REAL"),
        ("take_profit", "REAL"),
        ("volume", "REAL"),
        ("reason", "TEXT"),
        ("latency", "REAL"),
        ("execution_mode", "TEXT"),
        ("execution_id", "TEXT"),
        ("timestamp", "TEXT"),
    ),
    "audit_executions": (
        ("order_id", "TEXT"),
        ("symbol", "TEXT"),
        ("order_type", "TEXT"),
        ("volume", "REAL"),
        ("price", "REAL"),
        ("status", "TEXT"),
        ("executed_at", "TEXT"),
        ("payload", "TEXT"),
    ),
    "audit_account_snapshots": (
        ("timestamp", "TEXT"),
        ("balance", "REAL"),
        ("equity", "REAL"),
        ("margin_free", "REAL"),
        ("peak_equity", "REAL"),
        ("account_source", "TEXT DEFAULT ''"),
    ),
    "audit_experiences": (
        ("experience_id", "TEXT"),
        ("request_id", "TEXT"),
        ("execution_id", "TEXT DEFAULT ''"),
        ("decision_id", "TEXT DEFAULT ''"),
        ("idempotency_key", "TEXT"),
        ("correction_of", "TEXT DEFAULT ''"),
        ("record_version", "INTEGER DEFAULT 2"),
        ("symbol", "TEXT"),
        ("timeframe", "TEXT"),
        ("strategy_id", "TEXT"),
        ("strategy_version", "TEXT DEFAULT '1.0.0'"),
        ("decision_timestamp", "TEXT"),
        ("action", "TEXT"),
        ("entry_reason", "TEXT"),
        ("model_probability", "REAL DEFAULT 0.0"),
        ("signal_confidence", "REAL DEFAULT 0.0"),
        ("proposed_entry", "REAL"),
        ("stop_loss", "REAL"),
        ("take_profit", "REAL"),
        ("risk_reward_ratio", "REAL DEFAULT 1.0"),
        ("min_rr_policy", "REAL DEFAULT 0.0"),
        ("feature_schema_id", "TEXT DEFAULT 'scalp_v1'"),
        ("feature_dimension", "INTEGER DEFAULT 50"),
        ("feature_hash", "TEXT DEFAULT ''"),
        ("model_id", "TEXT DEFAULT ''"),
        ("model_version", "TEXT DEFAULT ''"),
        ("config_version", "TEXT DEFAULT ''"),
        ("payload", "TEXT"),
    ),
    "audit_experience_outcomes": (
        ("idempotency_key", "TEXT"),
        ("execution_id", "TEXT DEFAULT ''"),
        ("outcome_timestamp", "TEXT"),
        ("is_executed", "INTEGER DEFAULT 0"),
        ("is_closed", "INTEGER DEFAULT 0"),
        ("exit_reason", "TEXT DEFAULT ''"),
        ("realized_pnl_usd", "REAL DEFAULT 0.0"),
        ("realized_r_multiple", "REAL DEFAULT 0.0"),
        ("approved_volume", "REAL DEFAULT 0.0"),
        ("mae_points", "REAL DEFAULT 0.0"),
        ("mfe_points", "REAL DEFAULT 0.0"),
        ("mae_usd", "REAL DEFAULT 0.0"),
        ("mfe_usd", "REAL DEFAULT 0.0"),
        ("mae_r", "REAL DEFAULT 0.0"),
        ("mfe_r", "REAL DEFAULT 0.0"),
        ("holding_duration_seconds", "REAL DEFAULT 0.0"),
        ("slippage_points", "REAL DEFAULT 0.0"),
        ("execution_latency_ms", "REAL DEFAULT 0.0"),
        ("strategy_quality", "REAL DEFAULT 0.0"),
        ("entry_quality", "REAL DEFAULT 0.0"),
        ("execution_quality", "REAL DEFAULT 0.0"),
        ("management_quality", "REAL DEFAULT 0.0"),
        ("exit_quality", "REAL DEFAULT 0.0"),
        ("behavioral_flags", "TEXT DEFAULT ''"),
        ("payload", "TEXT"),
    ),
    "audit_experience_corrections": (
        ("correction_id", "TEXT"),
        ("idempotency_key", "TEXT"),
        ("corrected_at", "TEXT"),
        ("reason", "TEXT"),
        ("field_name", "TEXT"),
        ("old_value", "TEXT DEFAULT ''"),
        ("new_value", "TEXT DEFAULT ''"),
    ),
    "strategy_intelligence_registry": (
        ("strategy_id", "TEXT"),
        ("lifecycle_state", "TEXT"),
        ("sample_count", "INTEGER DEFAULT 0"),
        ("win_rate", "REAL DEFAULT 0.0"),
        ("expectancy_r", "REAL DEFAULT 0.0"),
        ("recent_expectancy_r", "REAL DEFAULT 0.0"),
        ("normalized_drawdown_r", "REAL DEFAULT 0.0"),
        ("profit_factor", "REAL DEFAULT 0.0"),
        ("confidence_score", "REAL DEFAULT 0.0"),
        ("evidence_quality", "REAL DEFAULT 0.0"),
        ("replay_validated", "INTEGER DEFAULT 0"),
        ("probation_samples", "INTEGER DEFAULT 0"),
        ("score_payload", "TEXT DEFAULT '{}'"),
        ("updated_at", "TEXT"),
    ),
    "experience_model_registry": (
        ("model_id", "TEXT"),
        ("model_version", "TEXT"),
        ("model_role", "TEXT DEFAULT 'PRIMARY_SCALP'"),
        ("artifact_path", "TEXT DEFAULT ''"),
        ("artifact_fingerprint", "TEXT DEFAULT ''"),
        ("feature_schema_id", "TEXT DEFAULT 'scalp_v1'"),
        ("feature_dimension", "INTEGER DEFAULT 50"),
        ("config_version", "TEXT DEFAULT ''"),
        ("build_identity", "TEXT DEFAULT ''"),
        ("was_replacement", "INTEGER DEFAULT 0"),
        ("registered_at", "TEXT"),
    ),
    # NOTE: UNIQUE(model_id, model_version, artifact_fingerprint) is a table
    # CONSTRAINT in the app DDL, not a column — healing a skeleton with plain
    # columns is compatible (the app bootstrap still owns constraint-level
    # truth via its CREATE TABLE / upsert semantics).
    "position_lifecycle_events": (
        ("event_key", "TEXT"),
        ("ticket", "TEXT"),
        ("trade_id", "TEXT DEFAULT ''"),
        ("experience_id", "TEXT DEFAULT ''"),
        ("symbol", "TEXT"),
        ("timeframe", "TEXT"),
        ("event_type", "TEXT"),
        ("sequence", "INTEGER DEFAULT 0"),
        ("event_timestamp", "TEXT"),
        ("market_context", "TEXT"),
        ("position_snapshot", "TEXT"),
        ("payload", "TEXT"),
    ),
    "trade_autopsies": (
        ("ticket", "INTEGER"),
        ("trade_id", "TEXT DEFAULT ''"),
        ("experience_id", "TEXT DEFAULT ''"),
        ("strategy_id", "TEXT DEFAULT ''"),
        ("strategy_version", "TEXT DEFAULT '1.0.0'"),
        ("symbol", "TEXT"),
        ("timeframe", "TEXT DEFAULT 'M1'"),
        ("entry_price", "REAL DEFAULT 0.0"),
        ("exit_price", "REAL DEFAULT 0.0"),
        ("volume", "REAL DEFAULT 0.0"),
        ("direction", "TEXT DEFAULT ''"),
        ("entry_reason", "TEXT DEFAULT ''"),
        ("realized_pnl_usd", "REAL DEFAULT 0.0"),
        ("realized_r", "REAL DEFAULT 0.0"),
        ("mfe_r", "REAL DEFAULT 0.0"),
        ("mae_r", "REAL DEFAULT 0.0"),
        ("giveback_pct", "REAL DEFAULT 0.0"),
        ("holding_duration_sec", "REAL DEFAULT 0.0"),
        ("exit_mechanism", "TEXT DEFAULT ''"),
        ("strategy_quality", "REAL DEFAULT 0.0"),
        ("entry_quality", "REAL DEFAULT 0.0"),
        ("management_quality", "REAL DEFAULT 0.0"),
        ("exit_quality", "REAL DEFAULT 0.0"),
        ("execution_quality", "REAL DEFAULT 0.0"),
        ("quality_verdict", "TEXT DEFAULT ''"),
        ("behavioral_flags", "TEXT DEFAULT ''"),
        ("narrative", "TEXT DEFAULT ''"),
        ("autopsied_at", "TEXT"),
        ("payload", "TEXT"),
    ),
    "behavior_detections": (
        ("behavior_key", "TEXT"),
        ("behavior_id", "TEXT"),
        ("ticket", "TEXT"),
        ("experience_id", "TEXT DEFAULT ''"),
        ("ticket_ctx", "TEXT DEFAULT ''"),
        ("pattern", "TEXT"),
        ("severity", "TEXT DEFAULT 'INFO'"),
        ("confidence", "REAL DEFAULT 0.0"),
        ("evidence", "TEXT DEFAULT '{}'"),
        ("detected_at", "TEXT"),
        ("autocorrected", "INTEGER DEFAULT 0"),
    ),
    "behavior_analysis": (
        ("analysis_key", "TEXT"),
        ("ticket", "TEXT"),
        ("symbol", "TEXT"),
        ("strategy_id", "TEXT"),
        ("behavior_version", "TEXT"),
        ("anomaly_version", "TEXT"),
        ("analyzed_at", "TEXT"),
        ("evidence_coverage", "REAL DEFAULT 0.0"),
        ("complete_context", "INTEGER DEFAULT 0"),
        ("partial_context", "INTEGER DEFAULT 0"),
        ("flags", "TEXT DEFAULT '[]'"),
        ("anomalies", "TEXT DEFAULT '[]'"),
    ),
    "anomaly_events": (
        ("anomaly_id", "TEXT"),
        ("ticket", "TEXT DEFAULT ''"),
        ("anomaly_type", "TEXT"),
        ("category", "TEXT DEFAULT 'DATA'"),
        ("severity", "TEXT DEFAULT 'LOW'"),
        ("confidence", "REAL DEFAULT 0.0"),
        ("evidence", "TEXT DEFAULT '{}'"),
        ("detected_at", "TEXT"),
        ("algorithm_version", "TEXT"),
    ),
    "strategy_evolution_candidates": (
        ("candidate_id", "TEXT"),
        ("source_strategy_id", "TEXT"),
        ("symbol", "TEXT"),
        ("timeframe", "TEXT DEFAULT ''"),
        ("hypothesis", "TEXT"),
        ("parameter_delta", "TEXT DEFAULT '{}'"),
        ("pattern_evidence", "TEXT DEFAULT '{}'"),
        ("status", "TEXT"),
        ("backtest_expectancy_r", "REAL DEFAULT 0.0"),
        ("backtest_sample_count", "INTEGER DEFAULT 0"),
        ("validated_at", "TEXT DEFAULT ''"),
        ("discovered_at", "TEXT"),
        ("payload", "TEXT"),
    ),
    "intelligence_worker_state": (
        ("scope", "TEXT"),
        ("last_checkpoint", "TEXT DEFAULT ''"),
        ("last_cycle_at", "TEXT DEFAULT ''"),
        ("last_error", "TEXT DEFAULT ''"),
        ("cycle_count", "INTEGER DEFAULT 0"),
    ),
    "factory_generations": (
        ("generation_id", "TEXT"),
        ("number", "INTEGER DEFAULT 0"),
        ("mode", "TEXT DEFAULT 'MANUAL'"),
        ("parent_generation", "TEXT DEFAULT ''"),
        ("population_target", "INTEGER DEFAULT 0"),
        ("created_at", "TEXT"),
        ("completed_at", "TEXT"),
        ("status", "TEXT DEFAULT 'PENDING'"),
        ("config", "TEXT DEFAULT '{}'"),
    ),
    "factory_candidates": (
        ("candidate_id", "TEXT"),
        ("definition_hash", "TEXT"),
        ("generation_id", "TEXT"),
        ("source", "TEXT DEFAULT 'TEMPLATE'"),
        ("operator", "TEXT DEFAULT 'NONE'"),
        ("parent_ids", "TEXT DEFAULT '[]'"),
        ("family", "TEXT DEFAULT 'HYBRID'"),
        ("population_index", "INTEGER DEFAULT 0"),
        ("dsl", "TEXT DEFAULT '{}'"),
        ("structural", "TEXT DEFAULT '{}'"),
        ("lifecycle", "TEXT DEFAULT 'GENERATED'"),
        ("failure_reasons", "TEXT DEFAULT '[]'"),
        ("llm_response_id", "TEXT DEFAULT ''"),
        ("created_at", "TEXT"),
    ),
    "factory_failures": (
        ("failure_id", "TEXT"),
        ("candidate_id", "TEXT"),
        ("strategy_id", "TEXT DEFAULT ''"),
        ("generation_id", "TEXT DEFAULT ''"),
        ("stage", "TEXT DEFAULT 'DSL_VALIDATION'"),
        ("reason", "TEXT DEFAULT ''"),
        ("detail", "TEXT DEFAULT '{}'"),
        ("created_at", "TEXT"),
    ),
    "factory_events": (
        ("event_id", "TEXT"),
        ("generation_id", "TEXT DEFAULT ''"),
        ("candidate_id", "TEXT DEFAULT ''"),
        ("event_type", "TEXT"),
        ("message", "TEXT DEFAULT ''"),
        ("payload", "TEXT DEFAULT '{}'"),
        ("created_at", "TEXT"),
    ),
    "factory_runs": (
        ("run_id", "TEXT"),
        ("generation_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("experiment_kind", "TEXT DEFAULT ''"),
        ("executed_at", "TEXT"),
        ("config", "TEXT DEFAULT '{}'"),
        ("result_summary", "TEXT DEFAULT '{}'"),
    ),
    "factory_provider_usage": (
        ("usage_id", "TEXT"),
        ("generation_id", "TEXT DEFAULT ''"),
        ("requests", "INTEGER DEFAULT 0"),
        ("failures", "INTEGER DEFAULT 0"),
        ("prompt_tokens", "INTEGER DEFAULT 0"),
        ("completion_tokens", "INTEGER DEFAULT 0"),
        ("total_tokens", "INTEGER DEFAULT 0"),
        ("estimated_cost_usd", "REAL DEFAULT 0.0"),
        ("last_latency_ms", "REAL DEFAULT 0.0"),
        ("last_error", "TEXT DEFAULT ''"),
        ("created_at", "TEXT"),
    ),
    "factory_loop_state": (
        ("scope", "TEXT"),
        ("state", "TEXT DEFAULT ''"),
        ("generation_id", "TEXT DEFAULT ''"),
        ("checkpoint", "TEXT DEFAULT ''"),
        ("updated_at", "TEXT DEFAULT ''"),
        ("last_error", "TEXT DEFAULT ''"),
    ),
    "strategy_registry": (
        ("strategy_id", "TEXT"),
        ("strategy_version", "TEXT"),
        ("feature_schema_id", "TEXT DEFAULT 'scalp_v1'"),
        ("feature_dimension", "INTEGER DEFAULT 50"),
        ("discovery_source", "TEXT DEFAULT ''"),
        ("discovery_window", "TEXT DEFAULT ''"),
        ("context_definition", "TEXT DEFAULT '{}'"),
        ("parent_strategy_ids", "TEXT DEFAULT '[]'"),
        ("lifecycle", "TEXT"),
        ("backtest", "TEXT DEFAULT '{}'"),
        ("walkforward", "TEXT DEFAULT '{}'"),
        ("oos", "TEXT DEFAULT '{}'"),
        ("robustness", "TEXT DEFAULT '{}'"),
        ("score", "TEXT DEFAULT '{}'"),
        ("confidence", "REAL DEFAULT 0.0"),
        ("sample_count", "INTEGER DEFAULT 0"),
        ("validation_lineage", "TEXT DEFAULT '[]'"),
        ("retirement_reason", "TEXT DEFAULT ''"),
        ("created_at", "TEXT"),
        ("updated_at", "TEXT"),
    ),
    "research_runs": (
        ("run_id", "TEXT"),
        ("dataset_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("strategy_version", "TEXT"),
        ("executed_at", "TEXT"),
        ("config", "TEXT DEFAULT '{}'"),
        ("build_identity", "TEXT DEFAULT ''"),
        ("result_summary", "TEXT DEFAULT '{}'"),
        ("status", "TEXT"),
        ("run_outcome", "TEXT"),
        ("snapshot_id", "TEXT"),
        ("gates", "TEXT"),
        ("completed_at", "TEXT"),
    ),
    "research_worker_state": (
        ("scope", "TEXT"),
        ("last_checkpoint", "TEXT DEFAULT ''"),
        ("last_cycle_at", "TEXT DEFAULT ''"),
        ("last_error", "TEXT DEFAULT ''"),
        ("cycle_count", "INTEGER DEFAULT 0"),
    ),
    "research_gates": (
        ("gate_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("research_run_id", "TEXT"),
        ("gate_type", "TEXT"),
        ("status", "TEXT DEFAULT 'PENDING'"),
        ("started_at", "TEXT DEFAULT ''"),
        ("completed_at", "TEXT DEFAULT ''"),
        ("duration_ms", "REAL DEFAULT 0.0"),
        ("configuration_version", "TEXT DEFAULT ''"),
        ("dataset_version", "TEXT DEFAULT ''"),
        ("engine_version", "TEXT DEFAULT ''"),
        ("result", "TEXT DEFAULT '{}'"),
        ("failure_reason", "TEXT DEFAULT ''"),
        ("failure_class", "TEXT DEFAULT 'UNKNOWN'"),
        ("evidence_id", "TEXT DEFAULT ''"),
        ("retryable", "INTEGER DEFAULT 0"),
        ("order_index", "INTEGER DEFAULT 0"),
    ),
    "research_events": (
        ("event_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("research_run_id", "TEXT"),
        ("gate_id", "TEXT DEFAULT ''"),
        ("event_type", "TEXT"),
        ("message", "TEXT DEFAULT ''"),
        ("payload", "TEXT DEFAULT '{}'"),
        ("occurred_at", "TEXT"),
    ),
    "research_evidence": (
        ("evidence_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("research_run_id", "TEXT"),
        ("gate_id", "TEXT DEFAULT ''"),
        ("kind", "TEXT DEFAULT ''"),
        ("content", "TEXT DEFAULT ''"),
        ("content_hash", "TEXT DEFAULT ''"),
        ("dataset_version", "TEXT DEFAULT ''"),
        ("engine_version", "TEXT DEFAULT ''"),
        ("created_at", "TEXT DEFAULT ''"),
    ),
    "research_run_snapshots": (
        ("research_run_id", "TEXT"),
        ("strategy_id", "TEXT"),
        ("strategy_version", "TEXT DEFAULT ''"),
        ("strategy_definition_hash", "TEXT DEFAULT ''"),
        ("strategy_configuration", "TEXT DEFAULT '{}'"),
        ("dataset_version", "TEXT DEFAULT ''"),
        ("dataset_hash", "TEXT DEFAULT ''"),
        ("feature_schema_version", "TEXT DEFAULT ''"),
        ("feature_schema_id", "TEXT"),
        ("feature_dimension", "INTEGER"),
        ("model_version", "TEXT DEFAULT ''"),
        ("model_hash", "TEXT DEFAULT ''"),
        ("model_id", "TEXT"),
        ("git_commit", "TEXT"),
        ("rule_matrix_version", "TEXT DEFAULT ''"),
        ("runtime_configuration_version", "TEXT DEFAULT ''"),
        ("backtest_engine_version", "TEXT DEFAULT ''"),
        ("validation_engine_version", "TEXT DEFAULT ''"),
        ("random_seed", "INTEGER DEFAULT 0"),
        ("research_prompt_version", "TEXT DEFAULT ''"),
        ("engine_version", "TEXT DEFAULT ''"),
        ("configuration_hash", "TEXT DEFAULT ''"),
        ("research_hash", "TEXT DEFAULT ''"),
        ("captured_at", "TEXT"),
    ),
    "research_worker_heartbeat": (
        ("scope", "TEXT"),
        ("last_beat_at", "TEXT DEFAULT ''"),
        ("cycle_count", "INTEGER DEFAULT 0"),
        ("last_cycle_start", "TEXT DEFAULT ''"),
        ("last_cycle_completion", "TEXT DEFAULT ''"),
        ("last_cycle_duration_ms", "REAL DEFAULT 0.0"),
        ("last_action", "TEXT DEFAULT ''"),
        ("current_job", "TEXT DEFAULT ''"),
        ("current_strategy", "TEXT DEFAULT ''"),
        ("current_gate", "TEXT DEFAULT ''"),
        ("queued_jobs", "INTEGER DEFAULT 0"),
        ("failed_jobs", "INTEGER DEFAULT 0"),
        ("last_error", "TEXT DEFAULT ''"),
        ("status", "TEXT DEFAULT ''"),
    ),
    "runtime_risk_state": (
        ("version", "INTEGER DEFAULT 1"),
        ("state", "TEXT"),
        ("reason", "TEXT DEFAULT ''"),
        ("source", "TEXT DEFAULT ''"),
        ("triggered_at", "TEXT DEFAULT ''"),
        ("balance", "REAL DEFAULT 0.0"),
        ("equity", "REAL DEFAULT 0.0"),
        ("peak_equity", "REAL DEFAULT 0.0"),
        ("release_required", "INTEGER DEFAULT 1"),
        ("released_at", "TEXT"),
        ("release_actor", "TEXT"),
        ("consecutive_losses", "INTEGER DEFAULT 0"),
    ),
    "audit_ledger": (
        ("ticket", "INTEGER"),
        ("symbol", "TEXT"),
        ("direction", "TEXT"),
        ("volume", "REAL"),
        ("entry_price", "REAL"),
        ("exit_price", "REAL"),
        ("status", "TEXT"),
        ("pnl", "REAL DEFAULT 0.0"),
        ("commission", "REAL DEFAULT 0.0"),
        ("swap", "REAL DEFAULT 0.0"),
        ("duration_sec", "REAL DEFAULT 0.0"),
        ("timestamp", "TEXT"),
        ("mae", "REAL DEFAULT 0.0"),
        ("mfe", "REAL DEFAULT 0.0"),
        ("initial_sl_price", "REAL DEFAULT 0.0"),
        ("final_sl_price", "REAL DEFAULT 0.0"),
        ("is_risk_free_hit", "INTEGER DEFAULT 0"),
        ("exit_mechanism", "TEXT DEFAULT ''"),
        ("order_id", "TEXT DEFAULT ''"),
        ("open_time", "TEXT DEFAULT ''"),
        ("close_time", "TEXT DEFAULT ''"),
        ("duration_seconds", "REAL DEFAULT 0.0"),
        ("open_price", "REAL DEFAULT 0.0"),
        ("close_price", "REAL DEFAULT 0.0"),
        ("gross_pnl_usd", "REAL DEFAULT 0.0"),
        ("net_pnl_usd", "REAL DEFAULT 0.0"),
        ("entry_reason", "TEXT DEFAULT ''"),
        ("ai_confidence_at_open", "REAL DEFAULT 0.0"),
        ("market_regime_at_open", "TEXT DEFAULT ''"),
        ("was_sl_modified", "INTEGER DEFAULT 0"),
        ("MAE_usd", "REAL DEFAULT 0.0"),
        ("MFE_usd", "REAL DEFAULT 0.0"),
        ("account_balance_after", "REAL DEFAULT 0.0"),
        ("account_equity_after", "REAL DEFAULT 0.0"),
        ("drawdown_percent_after", "REAL DEFAULT 0.0"),
        ("entry_setup_snapshot", "TEXT DEFAULT '{}'"),
        ("exit_reason_source", "TEXT DEFAULT ''"),
        ("exit_evidence", "TEXT DEFAULT ''"),
        ("exit_reason_confidence", "REAL DEFAULT 0.0"),
        ("reversal_events_json", "TEXT DEFAULT '[]'"),
        # NOTE: audit_ledger.account_source is deliberately NOT healed here —
        # the schema manifest declares audit_ledger's columns, and drift
        # verification classifies any extra column as drift (UNKNOWN). The
        # app bootstrap adds account_source via _add_column_if_missing at
        # engine construction (BUG-226), before any ledger INSERT.
    ),
    "trading_rules_config": (
        ("rule_name", "TEXT"),
        ("is_enabled", "INTEGER DEFAULT 0"),
        ("category", "TEXT"),
        ("parameters", "TEXT"),
    ),
}

__all__ = ["APP_REQUIRED_COLUMNS"]
