"""
Route-parity gate for the NSE Alternative UI (frontend/) — offline, source-level.

Every endpoint the alt console actually requests must exist as a real route on the
FastAPI backend (src/nexus_scalp/web/). Nothing boots, nothing is fetched: both
sides are read from source with AST/regex, so this runs in CI with no engine, no
MT5 and no network.

Why source-level instead of hitting a live server: the live contract is already
covered by tests/unit/test_alt_ui_runtime_contract.py (opt-in, ALT_UI_LIVE_BACKEND).
This file closes the *static* gap — a frontend call that would 404 forever, and a
backend surface the console silently never reaches (reported, not red).

Robustness (parallel orchestrator edits src/nexus_scalp/web while this runs):
each backend file is parsed inside try/except. A file that fails to parse falls
back to the cached last-good route table in tests/js/coverage_ledger.json and is
disclosed via ledger['parse_failures'] — the suite degrades to "stale but
visible", never to a crash and never to a silent pass.

The ledger is a generated artifact (it matches .gitignore's coverage*.json), so a
session autouse fixture regenerates it when it is absent — CI on a fresh checkout
gets a deterministic, self-consistent copy instead of skipping the gate. The hard
parity gate never depends on a hand-written expectation: it compares live scan vs
ledger content, both generated by the same code path.

Ledger gaps are explicit:
  * missing_routes / missing_fields  -> would be real offenders (kept in the
    ledger AND asserted empty by test_route_parity);
  * not_consumed                     -> backend API routes the console does not
    use yet (visibility only, never fails);
  * unverified_fields                -> consumed snapshot fields this scanner
    cannot prove from source; each is an xfail entry in
    test_alt_ui_snapshot_field_coverage.py.

Regenerate after intentionally changing either side:
  python -c "import tests.unit.test_alt_ui_route_parity as m; m.write_ledger()"
"""

from __future__ import annotations

import ast
import json
import os
import re
import sys
import warnings
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
WEB_DIR = os.path.join(REPO_ROOT, "src", "nexus_scalp", "web")
FRONTEND_SRC = os.path.join(REPO_ROOT, "frontend", "src")
LEDGER_PATH = os.path.join(REPO_ROOT, "tests", "js", "coverage_ledger.json")

_METHODS = ("get", "post", "put", "delete", "patch", "head", "options")

# Transports exported by frontend/src/api/client.ts. ``send`` is the mutation
# helper; getV1/getLegacy are reads. A bare fetch() outside client.ts is a
# supply-chain smell, covered by the XSS/transport lanes, not here.
_FRONTEND_TRANSPORT = re.compile(
    r"(?P<fn>getV1|getLegacy|(?<![.\w])send)\s*(?:<[^()]*>)?\s*\(\s*[`\"'](?P<path>/api[^`\"']*)"
)
# Any /api literal in a module that opens an EventSource/WebSocket is a request
# that module actually makes (comment stripping ran first, so prose can't lie).
_FRONTEND_SSE = re.compile(r"[`\"'](?P<path>/api[^`\"'?]*)")
_SSE_CONSUMER = re.compile(r"new\s+(?:EventSource|WebSocket)")


def _read(path: str) -> str:
    with open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read()


def _strip_ts_comments(src: str) -> str:
    """Drop JSDoc/line comments so a documented-but-unwired endpoint cannot pass."""
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    src = re.sub(r"(?m)^\s*//.*$", " ", src)
    return src


def _normalize(path: str) -> str:
    """Trim template suffix / query string from a frontend path literal."""
    path = re.split(r"\$\{|\?|#", path, maxsplit=1)[0]
    path = path.rstrip("/")
    return path or "/"


def _static_asset(path: str) -> bool:
    return path.endswith((".js", ".css", ".html", ".svg", ".png", ".ico", ".woff", ".woff2"))


def _segment_matches(concrete: str, template: str) -> bool:
    """Exact match, with ``{param}`` path segments (and ``{param:path}``) wildcarded."""
    if concrete == template:
        return True
    a, b = concrete.strip("/").split("/"), template.strip("/").split("/")
    if len(a) != len(b):
        return False
    for x, y in zip(a, b, strict=True):
        if y.startswith("{") and y.endswith("}"):
            continue
        if x != y:
            return False
    return True


def _router_prefixes(tree: ast.Module) -> dict[str, str]:
    """Map ``name = APIRouter(prefix=...)`` bindings to their prefix."""
    out: dict[str, str] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        value = node.value
        if not isinstance(value, ast.Call):
            continue
        func = value.func
        name = getattr(func, "id", None) or getattr(func, "attr", None)
        if name != "APIRouter":
            continue
        prefix = ""
        for kw in value.keywords:
            if kw.arg == "prefix" and isinstance(kw.value, ast.Constant):
                raw_prefix = kw.value.value
                if isinstance(raw_prefix, str):
                    prefix = raw_prefix
        for target in node.targets:
            if isinstance(target, ast.Name):
                out[target.id] = prefix
    return out


def scan_backend_files(
    paths: list[str],
) -> tuple[set[tuple[str, str]], dict[str, list[str]], list[str]]:
    """AST-scan backend route files.

    Returns (routes as {(method, path)}, routes_by_file, parse_failures).
    A file that cannot be parsed (mid-edit by a parallel agent) is reported in
    parse_failures instead of raising.
    """
    routes: set[tuple[str, str]] = set()
    by_file: dict[str, list[str]] = {}
    failures: list[str] = []
    for path in sorted(paths):
        rel = os.path.relpath(path, REPO_ROOT).replace("\\", "/")
        try:
            tree = ast.parse(_read(path))
        except Exception as exc:  # mid-edit by a parallel orchestrator
            failures.append(f"{rel}: {type(exc).__name__}: {exc}")
            continue
        found: set[tuple[str, str]] = set()
        try:
            prefixes = _router_prefixes(tree)
            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                for dec in node.decorator_list:
                    if not (isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute)):
                        continue
                    method = dec.func.attr
                    receiver = dec.func.value
                    recv_name = getattr(receiver, "id", None) or getattr(receiver, "attr", "")
                    is_app = recv_name == "app"
                    if method not in _METHODS and not (
                        is_app and method in {"websocket", "api_route"}
                    ):
                        continue
                    if not dec.args or not isinstance(dec.args[0], ast.Constant):
                        continue
                    raw = dec.args[0].value
                    if not isinstance(raw, str) or not raw.startswith("/"):
                        continue
                    full = raw if is_app else prefixes.get(recv_name, "") + raw
                    found.add((method, full))
        except Exception as exc:  # a half-parsed file must never poison the table
            failures.append(f"{rel}: scan error {type(exc).__name__}: {exc}")
        routes |= found
        by_file[rel] = sorted(f"{m.upper()} {p}" for m, p in found)
    return routes, by_file, failures


def backend_route_files(web_dir: str = WEB_DIR) -> list[str]:
    return [str(p) for p in Path(web_dir).rglob("*.py") if "__pycache__" not in str(p)]


def scan_backend_routes(
    web_dir: str = WEB_DIR,
) -> tuple[set[tuple[str, str]], list[str], dict[str, list[str]]]:
    """Real backend route table, with cached-last-good merge for unparseable files."""
    paths = backend_route_files(web_dir)
    routes, by_file, failures = scan_backend_files(paths)
    if failures:
        cached = load_ledger().get("last_good_routes") or {}
        for entry in failures[:]:
            rel = entry.split(":", 1)[0]
            for item in cached.get(rel, []):
                method, _, path = item.partition(" ")
                routes.add((method.lower(), path))
            if rel not in cached:
                failures.append(f"{rel}: NO cached last-good routes — fallback impossible")
    return routes, failures, by_file


def scan_frontend_calls(frontend_src: str = FRONTEND_SRC) -> set[tuple[str, str]]:
    """{(method, path)} the console requests: src/api/*.ts transports + SSE url."""
    calls: set[tuple[str, str]] = set()
    api_dir = Path(frontend_src) / "api"
    if not api_dir.is_dir():
        raise AssertionError(f"frontend api layer missing: {api_dir}")
    for path in sorted(api_dir.glob("*.ts")):
        src = _strip_ts_comments(_read(str(path)))
        for match in _FRONTEND_TRANSPORT.finditer(src):
            method = "post" if match.group("fn") == "send" else "get"
            calls.add((method, _normalize(match.group("path"))))
    ws_dir = Path(frontend_src) / "websocket"
    for path in sorted(ws_dir.glob("*.ts")) if ws_dir.is_dir() else []:
        src = _strip_ts_comments(_read(str(path)))
        if not _SSE_CONSUMER.search(src):
            continue
        for match in _FRONTEND_SSE.finditer(src):
            calls.add(("get", _normalize(match.group("path"))))
    return calls


def find_missing_routes(calls: set[tuple[str, str]], routes: set[tuple[str, str]]) -> list[str]:
    missing = []
    for method, path in sorted(calls):
        hit = any(
            (m == method and _segment_matches(path, route_path))
            or (m == "api_route" and _segment_matches(path, route_path))
            for m, route_path in routes
        )
        if not hit:
            missing.append(f"{method.upper()} {path}")
    return missing


def find_not_consumed(calls: set[tuple[str, str]], routes: set[tuple[str, str]]) -> list[str]:
    """Backend API/WS surface the alt console does not call (visibility only)."""
    consumed = {path for _m, path in calls}
    out: set[str] = set()
    for _method, path in routes:
        if _static_asset(path):
            continue
        if not path.startswith("/api") and path not in ("/ws", "/web"):
            continue
        if any(_segment_matches(concrete, path) for concrete in consumed):
            continue
        out.add(path)
    return sorted(out)


def load_ledger(path: str = LEDGER_PATH) -> dict[str, Any]:
    if not os.path.exists(path):
        return {}
    try:
        return json.loads(_read(path))
    except Exception as exc:
        raise AssertionError(f"{path} is not valid JSON ({exc})") from exc


def compute_route_side_ledger() -> dict[str, Any]:
    """Fresh route-parity view of the world (used by the assertions + writer)."""
    routes, failures, by_file = scan_backend_routes()
    calls = scan_frontend_calls()
    return {
        "routes": routes,
        "routes_by_file": by_file,
        "parse_failures": failures,
        "calls": calls,
        "missing_routes": find_missing_routes(calls, routes),
        "not_consumed": find_not_consumed(calls, routes),
        "backend_route_count": len(routes),
    }


def write_ledger(path: str = LEDGER_PATH) -> dict[str, Any]:
    """Regenerate the route-parity half of tests/js/coverage_ledger.json.

    Explicit maintenance entry point only — never called during collection or by
    an assertion, so CI cannot quietly rewrite its own expectations.
    """
    view = compute_route_side_ledger()
    ledger = load_ledger(path)
    ledger["generated_by"] = "alt-ui route-parity audit"
    ledger["missing_routes"] = view["missing_routes"]
    ledger["not_consumed"] = view["not_consumed"]
    ledger["last_good_routes"] = view["routes_by_file"]
    # degradation is disclosed, and the last-good cache above stays valid for it
    ledger["parse_failures"] = view["parse_failures"]
    summary = dict(ledger.get("summary") or {})
    summary.update(
        {
            "backend_routes": view["backend_route_count"],
            "frontend_calls": len(view["calls"]),
            "not_consumed_count": len(view["not_consumed"]),
        }
    )
    ledger["summary"] = summary
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(ledger, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return ledger


@pytest.fixture(scope="session", autouse=True)
def _ensure_ledger_exists() -> None:
    """Regenerate a missing ledger so a fresh checkout still runs the gates.

    Both writers run (each owns its half of the file). This is the only place the
    writers are invoked automatically, and it triggers solely when the generated
    artifact is absent — an existing ledger is never rewritten by a test run.
    """
    if os.path.exists(LEDGER_PATH):
        return
    write_ledger()
    from tests.unit import test_alt_ui_snapshot_field_coverage as field_module

    field_module.write_field_ledger()


class TestBackendRouteTable:
    """The scanner itself must not be blind (guards every assertion below)."""

    def test_scanner_sees_the_documented_route_surface(self) -> None:
        routes, failures, by_file = scan_backend_routes()
        assert by_file, "backend scan produced no files"
        assert len(routes) > 250, f"route table implausibly small: {len(routes)}"
        required = (
            ("get", "/api/status"),
            ("get", "/api/ticks/stream"),
            ("post", "/api/engine/toggle"),
            ("get", "/api/v1/positions"),
            ("get", "/api/v1/risk/status"),
            ("get", "/api/models/shadow70/summary"),
            ("get", "/api/intelligence/summary"),
            ("get", "/api/news/state"),
            ("get", "/api/debug/state"),
            ("get", "/api/account/trades"),
            ("get", "/api/replay/state"),
            ("get", "/api/operator/summary"),
        )
        for want in required:
            assert want in routes, f"route scanner lost {want[0].upper()} {want[1]}"
        assert not [f for f in failures if "NO cached last-good" in f], (
            f"unparseable backend file with no fallback: {failures}"
        )

    def test_frontend_scan_is_not_empty(self) -> None:
        calls = scan_frontend_calls()
        assert len(calls) >= 20, f"frontend scan implausibly small: {sorted(calls)}"
        assert ("get", "/api/status") in calls
        assert ("get", "/api/ticks/stream") in calls, "SSE url must be part of parity surface"
        assert ("post", "/api/positions/close") in calls, "mutations must be method-checked"


class TestRouteParity:
    """THE gate: every frontend-consumed path+method resolves to a backend route."""

    def test_route_parity(self) -> None:
        view = compute_route_side_ledger()
        offenders = view["missing_routes"]
        ledger_missing = list(load_ledger().get("missing_routes") or [])
        assert sorted(offenders) == sorted(ledger_missing), (
            "tests/js/coverage_ledger.json missing_routes is stale: "
            f"live={offenders} ledger={ledger_missing} — run: "
            'python -c "import tests.unit.test_alt_ui_route_parity as m; m.write_ledger()"'
        )
        assert not offenders, f"frontend calls a route the backend does not serve: {offenders}"

    def test_ledger_parse_failures_stay_visible(self) -> None:
        """Degradation must be disclosed, never silent — and never a false red.

        No live parse failure (normal CI): the ledger must not carry ghost
        failures and must hold the last-good route cache for the next event.
        Live parse failure (a parallel agent's mid-edit): every failing file must
        have a cached fallback, and the parity result stays trustworthy.
        """
        view = compute_route_side_ledger()
        live = view["parse_failures"]
        ledger = load_ledger()
        cached = ledger.get("last_good_routes") or {}
        if live:
            warnings.warn(
                "route-parity degraded to cached-last-good for: "
                + ", ".join(sorted(e.split(":", 1)[0] for e in live)),
                RuntimeWarning,
                stacklevel=2,
            )
            for entry in live:
                rel = entry.split(":", 1)[0]
                assert "NO cached last-good" not in entry, (
                    f"{rel} is unparseable AND uncached — parity ran blind: {entry}"
                )
                assert rel in cached, f"{rel} unparseable and uncached — not trustworthy"
        else:
            ghost = [f for f in list(ledger.get("parse_failures") or []) if f not in live]
            assert ghost == [], (
                "ledger records parse_failures the live scan no longer sees — regenerate: "
                'python -c "import tests.unit.test_alt_ui_route_parity as m; m.write_ledger()"'
            )
        assert cached, "ledger must carry last_good_routes for the mid-edit fallback"

    def test_sse_is_the_realtime_surface_not_websocket(self) -> None:
        """The alt console must consume SSE (/api/ticks/stream); /ws is served but
        cannot upgrade in production (uvicorn ws='none'), so it stays in not_consumed.
        """
        calls = scan_frontend_calls()
        paths = {path for _m, path in calls}
        assert "/api/ticks/stream" in paths
        assert not any(path.startswith(("/ws", "/web")) for path in paths), (
            "frontend opened a WebSocket endpoint that production cannot upgrade"
        )
        not_consumed = find_not_consumed(calls, scan_backend_routes()[0])
        assert "/ws" in not_consumed, "/ws must stay disclosed as unconsumed"


@pytest.mark.skipif(
    "--slow" not in sys.argv and os.environ.get("NSE_LEDGER_AUDIT") != "1",
    reason="300-entry visibility ledger walk; run with NSE_LEDGER_AUDIT=1",
)
class TestLedgerHygiene:
    """not_consumed is advisory; keep it honest but do not spend CI time on it."""

    def test_not_consumed_entries_are_real_routes(self) -> None:
        routes, _failures, _by_file = scan_backend_routes()
        declared = set(load_ledger().get("not_consumed") or [])
        for path in declared:
            assert any(rp == path for _m, rp in routes), f"ledger lists non-route {path}"


class TestScannerTolerance:
    """The try/except fallback is exercised, not just claimed."""

    def test_broken_backend_file_does_not_crash_the_scan(self, tmp_path: Path) -> None:
        web = tmp_path / "web"
        (web / "api_v1").mkdir(parents=True)
        (web / "good.py").write_text(
            'from fastapi import APIRouter\nrouter = APIRouter(prefix="/api/v1/x")\n'
            '@router.get("/ping")\ndef ping():\n    return {}\n',
            encoding="utf-8",
        )
        (web / "mid_edit.py").write_text("@app.get('/api/broken'\ndef (:\n", encoding="utf-8")
        routes, by_file, failures = scan_backend_files(
            [str(web / "good.py"), str(web / "mid_edit.py")]
        )
        assert ("get", "/api/v1/x/ping") in routes, (
            "a foreign syntax error must not lose valid files"
        )
        assert len(failures) == 1 and "mid_edit.py" in failures[0]
        assert not any("mid_edit" in k for k in by_file), (
            "failed file must not publish a route list"
        )


class TestGateCanFail:
    """A gate that cannot go red is not a gate: feed it synthetic offenders."""

    def test_phantom_frontend_call_is_detected(self) -> None:
        routes = {("get", "/api/v1/real"), ("post", "/api/engine/toggle")}
        offenders = find_missing_routes(
            {("get", "/api/v1/real"), ("get", "/api/v1/ghost"), ("get", "/api/engine/toggle")},
            routes,
        )
        assert "GET /api/v1/ghost" in offenders, "unknown path must be reported"
        assert "GET /api/engine/toggle" in offenders, "method mismatch must be reported"
        assert find_missing_routes({("post", "/api/engine/toggle")}, routes) == [], (
            "valid call must pass"
        )

    def test_template_segments_are_matched(self) -> None:
        routes = {("get", "/api/intelligence/autopsies/{ticket}")}
        assert find_missing_routes({("get", "/api/intelligence/autopsies/12345")}, routes) == []

    def test_comment_only_endpoint_is_not_counted_as_consumed(self) -> None:
        """A documented-but-unwired path must not make parity pass."""
        src = (
            "/** GET /api/never/wired — documented only */\n"
            'export const x = () => getLegacy<Foo>("/api/actually/called");\n'
        )
        stripped = _strip_ts_comments(src)
        assert _FRONTEND_TRANSPORT.search(stripped) is not None
        assert "/api/never/wired" not in stripped
