"""Operator routes tests (CHG-0043, TASK-CONTROL-CENTER).

Covers the /api/operator/* read-only surface end-to-end via TestClient
against the REAL create_app (engine_ref=None) and the real audit DB path
resolution, plus adversarial cases: missing decision, malformed filters,
additive-only route parity, read-only enforcement, and error-envelope
stability.

Run: .venv/Scripts/python -m pytest tests/unit/test_operator_routes.py -q
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from nexus_scalp.web.server import create_app

REPO_ROOT = Path(__file__).resolve().parents[2]

BASELINE_OPENAPI_PATHS = 252  # route-parity floor captured 2026-09-02 pre-wiring

#: The six CHG-0043 operator routes (additive-only contract, A-6).
CHG_0043_OPERATOR_PATHS = (
    "/api/operator/summary",
    "/api/operator/decisions",
    "/api/operator/decisions/{decision_id}",
    "/api/operator/funnel",
    "/api/operator/no-trade",
    "/api/operator/orders",
)

#: A-6 determinism (2026-09-12): pinned WEB-AUTH token + tmp-backed audit
#: ledger. On main these tests were machine-state dependent in TWO ways:
#: 1) WEB-AUTH-P0 middleware (audit B1) resolves the token from
#:    NSE_WEB_AUTH_TOKEN env, else the DPAPI SecureSecretStore
#:    (%LOCALAPPDATA%\NexusScalpEngine\secrets.enc — a token previously
#:    generated by the real engine lives there), else generates+persists a
#:    new one. With no env var, every probe here 401'd (15 reds) — while on
#:    a machine exporting NSE_WEB_AUTH_DISABLE=1 the middleware is skipped
#:    and the SAME probes pass. Same commit, different verdicts.
#: 2) ``_audit_db_path`` -> ``default_sqlite_path("audit")`` is CWD-anchored
#:    (BUG-149 source-run semantics), so the operator surface reads the
#:    REAL ``<cwd>/artifacts/audit.db`` when one exists (primary worktree:
#:    production ledger, content varies run to run) and nothing exists in a
#:    fresh checkout/worktree (LEDGER_UNAVAILABLE → every behavior test
#:    red). Neither env nor checkout state may decide these outcomes.
FAKE_WEB_AUTH_TOKEN = "a6-determinism-fake-token"


@pytest.fixture(scope="module", autouse=True)
def _deterministic_operator_env(tmp_path_factory: pytest.TempPathFactory):
    """Pin auth env + a seeded, tmp-backed audit ledger for the whole module.

    Test-local only (monkeypatch semantics; production code untouched):
    * NSE_WEB_AUTH_TOKEN := deterministic fake token (env-wins guarantee in
      auth._resolve_token means the DPAPI store is NEVER consulted or
      written), NSE_WEB_AUTH_DISABLE := removed (an ambient opt-out must not
      silently skip the middleware and fake-green these probes).
    * ``operator_routes._audit_db_path`` redirected to a tmp SQLite ledger
      with known audit_signals/audit_orders rows, so route behavior is
      reproducible independent of CWD, checkout, or the production DB. The
      read-only-URI security assertion still runs against this DB via the
      REAL ``_connect_ro`` code path.
    """
    from nexus_scalp.web import operator_routes

    mp = pytest.MonkeyPatch()
    mp.delenv("NSE_WEB_AUTH_DISABLE", raising=False)
    mp.setenv("NSE_WEB_AUTH_TOKEN", FAKE_WEB_AUTH_TOKEN)

    db = tmp_path_factory.mktemp("operator_ledger") / "audit.db"
    con = sqlite3.connect(db)
    con.executescript(
        """
        CREATE TABLE audit_signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            request_id TEXT NOT NULL,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            confidence REAL NOT NULL,
            proposed_entry REAL NOT NULL,
            stop_loss REAL NOT NULL,
            take_profit REAL NOT NULL,
            regime TEXT NOT NULL,
            generated_at TEXT NOT NULL,
            payload TEXT NOT NULL,
            execution_mode TEXT,
            reason_code TEXT,
            decision_stage TEXT,
            blocked_by TEXT,
            htf_score REAL,
            smc_score REAL,
            confidence_before_filters REAL,
            confidence_after_filters REAL,
            preferred_direction TEXT,
            raw_prob_buy REAL,
            raw_prob_sell REAL,
            raw_prob_no_trade REAL,
            raw_prob_wait REAL,
            confidence_source TEXT,
            spread_usd REAL
        );
        CREATE TABLE audit_orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ticket INTEGER,
            order_id TEXT NOT NULL,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            price REAL NOT NULL,
            stop_loss REAL,
            take_profit REAL,
            volume REAL NOT NULL,
            reason TEXT,
            latency REAL,
            execution_mode TEXT,
            execution_id TEXT,
            timestamp TEXT NOT NULL
        );
        """
    )
    recent = "datetime('now')"  # space-form = SQLite canonical, comparable
    #   to the routes' datetime('now', '-N hours') filters
    old = "'2020-01-01 00:00:00'"
    for gen in (recent, recent, recent, old, old, old):
        con.execute(
            "INSERT INTO audit_signals (request_id, symbol, action, confidence, "
            "proposed_entry, stop_loss, take_profit, regime, generated_at, payload, "
            "execution_mode, reason_code, decision_stage, blocked_by) "
            "VALUES ('a6-req', 'XAUUSD', 'NO_TRADE', 0.9, 3300.0, 3267.0, 3333.0, "
            "'RANGING_MEAN_REVERSION', " + gen + ", "
            '\'{"ai_no_trade_probability": 0.9, "model_action": "NO_TRADE"}\', '
            "'PAPER', 'SPREAD_GATE', 'TERMINAL', 'SPREAD_GATE')"
        )
    con.execute(
        "INSERT INTO audit_signals (request_id, symbol, action, confidence, "
        "proposed_entry, stop_loss, take_profit, regime, generated_at, payload, "
        "execution_mode, reason_code, decision_stage, blocked_by) VALUES "
        "('a6-buy', 'XAUUSD', 'BUY', 0.8, 3300.0, 3290.0, 3320.0, 'TRENDING_UP', "
        'datetime(\'now\'), \'{"ai_buy_probability": 0.8, "model_action": "BUY"}\', '
        "'PAPER', NULL, 'DISPATCHED', NULL)"
    )
    for latency in (10.0, 20.0, 30.0):
        con.execute(
            "INSERT INTO audit_orders (ticket, order_id, symbol, action, price, "
            "stop_loss, take_profit, volume, reason, latency, execution_mode, "
            "execution_id, timestamp) VALUES "
            f"(4400, 'a6-buy', 'XAUUSD', 'BUY', 3300.0, 3290.0, 3320.0, 0.01, "
            f"'TEST', {latency}, 'PAPER', 'exec-a6', '2026-09-12 00:00:00')"
        )
    con.commit()
    con.close()
    mp.setattr(operator_routes, "_audit_db_path", lambda: str(db))
    yield
    mp.undo()


@pytest.fixture(scope="module")
def client(_deterministic_operator_env: None) -> TestClient:
    """Authenticated TestClient: operator surface with an explicit credential.

    WEB-AUTH-P0 enforces Bearer/X-NSE-Token/?token= on every /api path
    (fail-closed); these probes carry the pinned fixture token exactly like
    an authenticated operator would. The 401 contract itself stays tested —
    tests/unit/test_web_auth.py asserts refusal WITHOUT a token. The
    explicit dependency guarantees the env pin is active BEFORE create_app
    resolves the middleware token.
    """
    app = create_app(engine_ref=None)
    c = TestClient(app)
    c.headers.update({"Authorization": f"Bearer {FAKE_WEB_AUTH_TOKEN}"})
    return c


# ---------------------------------------------------------------------------
# Route parity: the operator surface is additive-only
# ---------------------------------------------------------------------------


class TestAdditiveOnly:
    def test_openapi_grows_by_exactly_six(self, client: TestClient) -> None:
        paths = client.app.openapi()["paths"]
        operator = [p for p in paths if p.startswith("/api/operator")]
        assert len(paths) >= BASELINE_OPENAPI_PATHS
        # A-6 (determinism, 2026-09-12): this ==6 pin went stale silently.
        # 56fce1e8 (2026-09-08, calibration evidence monitor) legitimately
        # added /api/operator/calibration, so the exact count depends on the
        # checkout's age, not on machine state. The contract this test names
        # is ADDITIVE-ONLY: the six CHG-0043 paths must all be present
        # (pinned exactly below and in test_operator_paths_discovered) and
        # later additions are allowed by design — never deletions/renames.
        # Red-before note: this failed identically on EVERY environment
        # scenario probed (it is drift, not env sensitivity); fixed by
        # encoding the invariant the title already claims.
        assert set(CHG_0043_OPERATOR_PATHS) <= set(operator), (
            f"operator surface lost routes: {sorted(set(CHG_0043_OPERATOR_PATHS) - set(operator))}"
        )
        assert len(operator) >= 6, operator

    def test_operator_paths_discovered(self, client: TestClient) -> None:
        paths = client.app.openapi()["paths"]
        for p in (
            "/api/operator/summary",
            "/api/operator/decisions",
            "/api/operator/decisions/{decision_id}",
            "/api/operator/funnel",
            "/api/operator/no-trade",
            "/api/operator/orders",
        ):
            assert p in paths, p

    def test_all_operator_routes_are_get(self, client: TestClient) -> None:
        paths = client.app.openapi()["paths"]
        for p, methods in paths.items():
            if p.startswith("/api/operator"):
                assert set(methods) <= {"get"}, (p, set(methods))


# ---------------------------------------------------------------------------
# Read-only enforcement: the surface cannot mutate the audit trail
# ---------------------------------------------------------------------------


class TestReadOnly:
    def test_connect_ro_cannot_write(self) -> None:
        from nexus_scalp.web.operator_routes import _connect_ro

        con = _connect_ro()
        assert con is not None, "authoritative audit DB must exist in repo"
        try:
            with pytest.raises(sqlite3.OperationalError):
                con.execute("CREATE TABLE cc_mutation_probe (x INTEGER)")
        finally:
            con.close()

    def test_post_to_operator_route_is_405(self, client: TestClient) -> None:
        r = client.post("/api/operator/summary")
        assert r.status_code == 405


# ---------------------------------------------------------------------------
# Endpoint behavior
# ---------------------------------------------------------------------------


class TestSummary:
    def test_summary_shape(self, client: TestClient) -> None:
        r = client.get("/api/operator/summary")
        assert r.status_code == 200
        body = r.json()
        assert body["available"] is True
        assert "runtime" in body and "ledger" in body and "warnings" in body
        rt = body["runtime"]
        for key in ("engine_running", "execution_mode", "runtime_mode", "state_version"):
            assert key in rt, key

    def test_summary_ledger_stats_are_bounded(self, client: TestClient) -> None:
        body = client.get("/api/operator/summary").json()
        ledger = body["ledger"]
        if ledger.get("available"):
            assert ledger["scanned_rows"] <= ledger["window"]
            assert isinstance(ledger.get("actions"), dict)


class TestDecisions:
    def test_history_limit_clamped(self, client: TestClient) -> None:
        r = client.get("/api/operator/decisions?limit=99999")
        assert r.status_code == 200
        assert r.json()["count"] <= 500

    def test_action_filter(self, client: TestClient) -> None:
        r = client.get("/api/operator/decisions?action=NO_TRADE&limit=20")
        assert r.status_code == 200
        rows = r.json()["rows"]
        assert all(row["action"] == "NO_TRADE" for row in rows)

    def test_rows_carry_payload_ok_flag(self, client: TestClient) -> None:
        rows = client.get("/api/operator/decisions?limit=10").json()["rows"]
        assert rows, "ledger fixture expected to be non-empty in repo"
        for row in rows:
            assert isinstance(row["payload_ok"], bool)
            assert "probabilities" in row

    def test_missing_decision_returns_stable_envelope(self, client: TestClient) -> None:
        r = client.get("/api/operator/decisions/999999999")
        assert r.status_code == 200
        body = r.json()
        assert body["available"] is False
        assert body["error"]["code"] == "NOT_FOUND"
        assert "request_id" in body["error"]

    def test_detail_includes_correlation_metadata(self, client: TestClient) -> None:
        rows = client.get("/api/operator/decisions?limit=1").json()["rows"]
        assert rows
        detail = client.get(f"/api/operator/decisions/{rows[0]['id']}").json()
        assert detail["available"] is True
        d = detail["decision"]
        assert "order_correlation" in d
        assert "orders" in d
        assert "columns_not_recorded" in d


class TestFunnelAndNoTrade:
    def test_funnel_totals_reconcile(self, client: TestClient) -> None:
        body = client.get("/api/operator/funnel").json()
        assert body["available"] is True
        assert body["total"] == sum(s["count"] for s in body["stages"])
        assert body["total"] == sum(g["count"] for g in body["gates"])
        assert "TERMINAL" in body["note"]

    def test_no_trade_distribution_sums_to_total(self, client: TestClient) -> None:
        body = client.get("/api/operator/no-trade").json()
        assert body["available"] is True
        assert body["total"] == sum(g["count"] for g in body["gates"])
        assert body["total"] == sum(x["count"] for x in body["reasons"])
        assert isinstance(body["model_direction_unresolved"], int)
        assert body["model_direction_unresolved"] <= body["total"]

    def test_no_trade_hours_filter_bounds_results(self, client: TestClient) -> None:
        full = client.get("/api/operator/no-trade").json()["total"]
        one = client.get("/api/operator/no-trade?hours=1").json()["total"]
        assert one <= full


class TestOrders:
    def test_orders_latency_stats_computed_only_from_numeric_rows(self, client: TestClient) -> None:
        body = client.get("/api/operator/orders?limit=25").json()
        assert body["available"] is True
        if body["count"] == 0:
            assert body["latency"] is None
            return
        if body["latency"] is not None:
            lat = body["latency"]
            assert lat["n"] >= 1
            assert lat["p50_ms"] <= lat["p95_ms"] <= lat["p99_ms"]

    def test_orders_limit_clamped(self, client: TestClient) -> None:
        body = client.get("/api/operator/orders?limit=100000").json()
        assert body["count"] <= 200


# ---------------------------------------------------------------------------
# Security: no secrets / no stack traces reach the response
# ---------------------------------------------------------------------------


class TestSanitization:
    def test_error_envelope_has_no_traceback(self, client: TestClient) -> None:
        body = client.get("/api/operator/decisions/999999999").json()
        text = str(body)
        assert "Traceback" not in text
        assert "sqlite3." not in text

    def test_list_rows_never_carry_raw_payload_blob(self, client: TestClient) -> None:
        rows = client.get("/api/operator/decisions?limit=5").json()["rows"]
        for row in rows:
            assert "payload" not in row, "raw blob must stay server-side in list views"
